// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vladify.DataAccess;

#nullable disable

namespace Vladify.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312134013_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Album = "Practical Plastic Table",
                            Author = "Viva Moen",
                            Duration = new TimeSpan(0, 0, 2, 44, 0),
                            Title = "backing up the"
                        },
                        new
                        {
                            Id = new Guid("e943fb26-4d85-83c6-3c08-7e1147e1f117"),
                            Album = "Refined Fresh Bike",
                            Author = "Daphney Schneider",
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "I'll compress the"
                        },
                        new
                        {
                            Id = new Guid("2be77ccd-e177-00e7-a24d-0dd3d8dd0b91"),
                            Album = "Fantastic Wooden Chicken",
                            Author = "Katrine Hintz",
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Title = "The GB card"
                        },
                        new
                        {
                            Id = new Guid("10ef0fbc-c412-c0b5-2153-9a65f9f07585"),
                            Album = "Rustic Steel Salad",
                            Author = "Cortney Boyer",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Title = "The RSS matrix"
                        },
                        new
                        {
                            Id = new Guid("ab9eaf0f-006e-9244-5efd-c113274a70a2"),
                            Album = "Practical Concrete Bacon",
                            Author = "Marley Schroeder",
                            Duration = new TimeSpan(0, 0, 3, 6, 0),
                            Title = "indexing the array"
                        },
                        new
                        {
                            Id = new Guid("d993c1d1-0d5e-71b0-b4ee-f7f9ace2261f"),
                            Album = "Gorgeous Granite Table",
                            Author = "Madaline Hirthe",
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "overriding the monitor"
                        },
                        new
                        {
                            Id = new Guid("9841a693-344d-9dc1-69e7-b51a99feed43"),
                            Album = "Sleek Frozen Gloves",
                            Author = "Laila Stark",
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Title = "The THX monitor"
                        },
                        new
                        {
                            Id = new Guid("a3aba8c4-8813-0ede-ac5f-ab782189b5eb"),
                            Album = "Licensed Soft Sausages",
                            Author = "Ronaldo Pagac",
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Title = "You can't compress"
                        },
                        new
                        {
                            Id = new Guid("84392580-8c61-c0d8-3c11-061120df963b"),
                            Album = "Practical Wooden Gloves",
                            Author = "Marina Watsica",
                            Duration = new TimeSpan(0, 0, 3, 10, 0),
                            Title = "Try to connect"
                        },
                        new
                        {
                            Id = new Guid("e6e78d59-4620-878d-2527-1695b0f4ae86"),
                            Album = "Practical Cotton Tuna",
                            Author = "Alessandro Kertzmann",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Title = "overriding the microchip"
                        },
                        new
                        {
                            Id = new Guid("cd0936a2-cc05-ae67-291f-f0d9510e163e"),
                            Album = "Incredible Granite Fish",
                            Author = "Maxie Kuphal",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "If we calculate"
                        },
                        new
                        {
                            Id = new Guid("f065b2d5-46f5-efe4-1d49-90e38d005c36"),
                            Album = "Fantastic Metal Sausages",
                            Author = "Columbus Sipes",
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Title = "I'll hack the"
                        },
                        new
                        {
                            Id = new Guid("4d56cd88-22e4-77d9-ba00-e40a2a262126"),
                            Album = "Awesome Plastic Ball",
                            Author = "Dereck Beahan",
                            Duration = new TimeSpan(0, 0, 2, 38, 0),
                            Title = "I'll parse the"
                        },
                        new
                        {
                            Id = new Guid("f547f9ec-3e8c-4f66-f342-ff6a26e57c4c"),
                            Album = "Handcrafted Granite Pants",
                            Author = "Gayle Cole",
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Title = "If we program"
                        },
                        new
                        {
                            Id = new Guid("101323dd-7edb-c08a-b8ef-7eebc0d13343"),
                            Album = "Gorgeous Fresh Bike",
                            Author = "Kaylah Gaylord",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("5cb84213-5438-cf71-2fef-8fa85bbb9470"),
                            Album = "Incredible Cotton Pizza",
                            Author = "Willard Bernier",
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Title = "You can't hack"
                        },
                        new
                        {
                            Id = new Guid("6b254b51-3c7b-75ac-3622-b26b5f6314b4"),
                            Album = "Fantastic Granite Car",
                            Author = "Wallace Lehner",
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("ec91d5e0-363d-e37d-c923-2c1e0f1e3ad1"),
                            Album = "Refined Wooden Pizza",
                            Author = "Polly Hamill",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("00133a77-3a59-6194-90c5-2d29e630eba5"),
                            Album = "Gorgeous Frozen Shoes",
                            Author = "Theresa Towne",
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Title = "overriding the panel"
                        },
                        new
                        {
                            Id = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Album = "Incredible Cotton Towels",
                            Author = "Bette Bins",
                            Duration = new TimeSpan(0, 0, 3, 19, 0),
                            Title = "Try to program"
                        },
                        new
                        {
                            Id = new Guid("7ead679b-6056-0da5-c5c8-2058c35c9662"),
                            Album = "Generic Plastic Soap",
                            Author = "Devante Will",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "The XSS alarm"
                        },
                        new
                        {
                            Id = new Guid("cbbe5302-f9c4-a7f3-7e45-7d293332c0b6"),
                            Album = "Handmade Rubber Chicken",
                            Author = "Wilton Corkery",
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("d0c5583a-5eec-720b-0954-94ca69eee435"),
                            Album = "Rustic Steel Computer",
                            Author = "Bert Windler",
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Title = "You can't navigate"
                        },
                        new
                        {
                            Id = new Guid("49f27222-7147-266d-80ac-3dd5264eac89"),
                            Album = "Rustic Metal Keyboard",
                            Author = "Arne Moen",
                            Duration = new TimeSpan(0, 0, 3, 25, 0),
                            Title = "If we parse"
                        },
                        new
                        {
                            Id = new Guid("dce4d4e0-26f4-974f-624a-82f780bdb531"),
                            Album = "Tasty Plastic Pants",
                            Author = "Peter Parisian",
                            Duration = new TimeSpan(0, 0, 3, 21, 0),
                            Title = "I'll parse the"
                        },
                        new
                        {
                            Id = new Guid("26e95505-aa46-ac45-c860-e000ff1526e9"),
                            Album = "Handcrafted Plastic Sausages",
                            Author = "Hannah Wuckert",
                            Duration = new TimeSpan(0, 0, 2, 32, 0),
                            Title = "Try to generate"
                        },
                        new
                        {
                            Id = new Guid("79c6c817-277b-0c91-615b-b1d67808699e"),
                            Album = "Ergonomic Granite Shoes",
                            Author = "Ivy Bailey",
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Title = "If we transmit"
                        },
                        new
                        {
                            Id = new Guid("256eceb8-52b2-0095-9967-84d7831987f1"),
                            Album = "Gorgeous Frozen Towels",
                            Author = "Devan Robel",
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Title = "The SDD array"
                        },
                        new
                        {
                            Id = new Guid("4a6cb4f9-c745-9254-ec8b-2326736804fd"),
                            Album = "Licensed Cotton Fish",
                            Author = "Adeline Maggio",
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Title = "If we connect"
                        },
                        new
                        {
                            Id = new Guid("700d1f19-5126-e507-fa3a-92bbc5f404c5"),
                            Album = "Licensed Rubber Chips",
                            Author = "Ellsworth Barton",
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Title = "Use the virtual"
                        },
                        new
                        {
                            Id = new Guid("a01cf8f3-9cd0-cc79-7eb3-ff22611e03a9"),
                            Album = "Refined Concrete Fish",
                            Author = "Blake Hodkiewicz",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "Use the virtual"
                        },
                        new
                        {
                            Id = new Guid("a86028b5-eb5a-01f1-1df1-eb287b3747c1"),
                            Album = "Small Plastic Chips",
                            Author = "Else Ullrich",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Title = "I'll reboot the"
                        },
                        new
                        {
                            Id = new Guid("42c4cbf8-16de-5617-5257-c7762d018cad"),
                            Album = "Intelligent Granite Table",
                            Author = "Benjamin Abshire",
                            Duration = new TimeSpan(0, 0, 2, 44, 0),
                            Title = "Try to navigate"
                        },
                        new
                        {
                            Id = new Guid("bb12c7e2-f9a8-5109-2da9-4a6420f16e85"),
                            Album = "Small Rubber Keyboard",
                            Author = "Brittany Schulist",
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Title = "indexing the card"
                        },
                        new
                        {
                            Id = new Guid("fdbb9057-2368-8b74-440c-cd33f83b80e2"),
                            Album = "Handmade Frozen Salad",
                            Author = "Josianne VonRueden",
                            Duration = new TimeSpan(0, 0, 3, 11, 0),
                            Title = "Try to generate"
                        },
                        new
                        {
                            Id = new Guid("06f83bb9-4eb4-9dfa-ed4c-fbfc7de340d3"),
                            Album = "Incredible Rubber Soap",
                            Author = "Effie Turcotte",
                            Duration = new TimeSpan(0, 0, 2, 30, 0),
                            Title = "I'll reboot the"
                        },
                        new
                        {
                            Id = new Guid("6dcbc63b-2a63-09d2-13c7-7fa941e3f428"),
                            Album = "Small Granite Tuna",
                            Author = "Maybell Nikolaus",
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "I'll bypass the"
                        },
                        new
                        {
                            Id = new Guid("32e4acda-9163-2661-808e-99521037bffc"),
                            Album = "Handcrafted Fresh Bacon",
                            Author = "Myah Halvorson",
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            Album = "Incredible Metal Towels",
                            Author = "Ursula Smitham",
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Title = "You can't override"
                        },
                        new
                        {
                            Id = new Guid("65f546dc-a7d5-6b91-62fc-59cb08581aaf"),
                            Album = "Practical Frozen Shoes",
                            Author = "Dagmar Waters",
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Title = "connecting the bandwidth"
                        },
                        new
                        {
                            Id = new Guid("fb8efa5b-8cef-9b8a-57e1-dada3c3d8bee"),
                            Album = "Unbranded Granite Computer",
                            Author = "Eugenia Vandervort",
                            Duration = new TimeSpan(0, 0, 3, 25, 0),
                            Title = "If we override"
                        },
                        new
                        {
                            Id = new Guid("9041ab93-2fae-6810-6e5d-dc7bcd7f57e8"),
                            Album = "Refined Fresh Salad",
                            Author = "Mabel Weissnat",
                            Duration = new TimeSpan(0, 0, 3, 21, 0),
                            Title = "The RAM hard"
                        },
                        new
                        {
                            Id = new Guid("03b18792-8f7a-ac07-9f49-2c0d2c237f3b"),
                            Album = "Refined Frozen Soap",
                            Author = "Tessie Harris",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "You can't copy"
                        },
                        new
                        {
                            Id = new Guid("1eb82dfa-c0e7-e6d5-acd9-013d77ab48e3"),
                            Album = "Practical Rubber Chips",
                            Author = "Tanner Boehm",
                            Duration = new TimeSpan(0, 0, 3, 29, 0),
                            Title = "Use the primary"
                        },
                        new
                        {
                            Id = new Guid("bb433fae-39eb-71b1-910e-256c4d998f5a"),
                            Album = "Fantastic Frozen Pizza",
                            Author = "Tamara Ritchie",
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("392ad14d-c224-6c37-9545-523ef9d7529d"),
                            Album = "Fantastic Concrete Cheese",
                            Author = "Josue Orn",
                            Duration = new TimeSpan(0, 0, 3, 19, 0),
                            Title = "If we hack"
                        },
                        new
                        {
                            Id = new Guid("7a23a379-2cb0-bf24-e3eb-488a6222c4ab"),
                            Album = "Refined Plastic Chicken",
                            Author = "Patricia Harvey",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("90ad94db-7de6-f2f2-21d8-8dccb292ba0e"),
                            Album = "Ergonomic Wooden Towels",
                            Author = "Isaiah Blanda",
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("d3ef43fd-5d8e-4fe3-3db7-a3e42fd28932"),
                            Album = "Rustic Soft Salad",
                            Author = "Gregg Marks",
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Title = "synthesizing the alarm"
                        },
                        new
                        {
                            Id = new Guid("680c0509-a266-def4-e8b9-3e54af6bd0b9"),
                            Album = "Fantastic Granite Chicken",
                            Author = "Earnest Armstrong",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "If we bypass"
                        },
                        new
                        {
                            Id = new Guid("b340c0d5-5357-3745-ab3b-7d8dddaa4a9b"),
                            Album = "Handcrafted Cotton Bike",
                            Author = "Janie Fisher",
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "You can't generate"
                        },
                        new
                        {
                            Id = new Guid("5f98c9b3-8ec0-2708-788a-fd5b25980e7c"),
                            Album = "Rustic Frozen Soap",
                            Author = "Gunnar Gaylord",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "The THX firewall"
                        },
                        new
                        {
                            Id = new Guid("416d134a-9485-e184-a21e-cd4fa2232278"),
                            Album = "Handmade Rubber Gloves",
                            Author = "Bria Nolan",
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Title = "The HTTP interface"
                        },
                        new
                        {
                            Id = new Guid("e1b81f8a-e7ef-65dd-1dbb-d690142cdac9"),
                            Album = "Intelligent Rubber Sausages",
                            Author = "Andre Rohan",
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Title = "Try to connect"
                        },
                        new
                        {
                            Id = new Guid("ce3c2ecd-87f1-8357-65eb-60bb46bd5b9f"),
                            Album = "Gorgeous Rubber Towels",
                            Author = "Deondre Emard",
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Title = "The JBOD hard"
                        },
                        new
                        {
                            Id = new Guid("7ee11701-8c6c-ee97-7f08-9f8cd556634d"),
                            Album = "Unbranded Frozen Car",
                            Author = "Ophelia Bernhard",
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Title = "Try to back"
                        },
                        new
                        {
                            Id = new Guid("378bf827-931e-4e82-09e2-4eb9256c1f26"),
                            Album = "Incredible Wooden Salad",
                            Author = "Titus Gerhold",
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Title = "Use the neural"
                        },
                        new
                        {
                            Id = new Guid("6b272fa4-465b-86c7-7c67-6e41d314447f"),
                            Album = "Fantastic Metal Sausages",
                            Author = "Virginie Barton",
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Title = "hacking the array"
                        },
                        new
                        {
                            Id = new Guid("8b220216-0039-d9aa-bbe2-5edfa598a947"),
                            Album = "Gorgeous Steel Hat",
                            Author = "Arvel Pacocha",
                            Duration = new TimeSpan(0, 0, 3, 11, 0),
                            Title = "If we copy"
                        },
                        new
                        {
                            Id = new Guid("f30f5d2c-570e-7a70-44e2-08d36a6ac388"),
                            Album = "Generic Wooden Cheese",
                            Author = "Francesca Harris",
                            Duration = new TimeSpan(0, 0, 3, 23, 0),
                            Title = "The PNG bus"
                        },
                        new
                        {
                            Id = new Guid("dea8f8e4-52dd-5dad-d26a-d14d282f023c"),
                            Album = "Practical Soft Gloves",
                            Author = "Barbara Stanton",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "navigating the hard"
                        },
                        new
                        {
                            Id = new Guid("da8016b2-bd5c-4b96-3929-f517bd65b521"),
                            Album = "Incredible Frozen Cheese",
                            Author = "Velma Hand",
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Title = "Try to index"
                        },
                        new
                        {
                            Id = new Guid("81dc975b-3c9d-bcab-eaf6-f16a99b60231"),
                            Album = "Practical Wooden Soap",
                            Author = "Jabari Dach",
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Title = "Try to generate"
                        },
                        new
                        {
                            Id = new Guid("6a422f78-47aa-a2f0-4c73-7980baf93708"),
                            Album = "Handmade Cotton Mouse",
                            Author = "Loy Feeney",
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "If we synthesize"
                        },
                        new
                        {
                            Id = new Guid("5cc4e584-6686-ba43-b486-bf51c65fe4b8"),
                            Album = "Ergonomic Plastic Table",
                            Author = "Llewellyn Botsford",
                            Duration = new TimeSpan(0, 0, 3, 17, 0),
                            Title = "If we calculate"
                        },
                        new
                        {
                            Id = new Guid("d0c42c0a-10da-671e-af1c-f953b57d5493"),
                            Album = "Gorgeous Wooden Tuna",
                            Author = "Kory Christiansen",
                            Duration = new TimeSpan(0, 0, 2, 33, 0),
                            Title = "Use the online"
                        },
                        new
                        {
                            Id = new Guid("d4f53a08-378e-87af-c2ee-76b5417d08ed"),
                            Album = "Handmade Soft Keyboard",
                            Author = "Deion Anderson",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Title = "If we generate"
                        },
                        new
                        {
                            Id = new Guid("5576e921-a374-745f-2725-c57dcdccd185"),
                            Album = "Small Cotton Hat",
                            Author = "Patience Ortiz",
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Title = "I'll program the"
                        },
                        new
                        {
                            Id = new Guid("c35e1626-10b3-d866-7821-419e1e94c5ab"),
                            Album = "Refined Wooden Soap",
                            Author = "Ramiro Harvey",
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("9e0146df-a0dd-114e-c601-c9bd66f80df0"),
                            Album = "Gorgeous Concrete Pants",
                            Author = "Ola Mraz",
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "If we program"
                        },
                        new
                        {
                            Id = new Guid("3ac37149-62d5-31f9-1fa2-c07e45b4e464"),
                            Album = "Ergonomic Wooden Computer",
                            Author = "Anahi Kassulke",
                            Duration = new TimeSpan(0, 0, 2, 52, 0),
                            Title = "You can't copy"
                        },
                        new
                        {
                            Id = new Guid("00c1627d-b759-55c7-3d8f-e703fedbd0a4"),
                            Album = "Licensed Steel Chips",
                            Author = "Abigail Howe",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "calculating the feed"
                        },
                        new
                        {
                            Id = new Guid("69abf1cb-79b7-bdb4-e1c0-248dec8f275a"),
                            Album = "Incredible Rubber Bike",
                            Author = "Milo Pollich",
                            Duration = new TimeSpan(0, 0, 2, 32, 0),
                            Title = "Use the 1080p"
                        },
                        new
                        {
                            Id = new Guid("92a61fad-5aa2-4b89-e47e-4b852713c3ac"),
                            Album = "Sleek Granite Ball",
                            Author = "Aletha Kunze",
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Title = "If we navigate"
                        },
                        new
                        {
                            Id = new Guid("af878b8c-9b73-c10f-1991-eb9105db76d5"),
                            Album = "Sleek Cotton Hat",
                            Author = "Ardella Powlowski",
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("334cccd0-bff9-58bf-f79c-128c030193b7"),
                            Album = "Tasty Steel Salad",
                            Author = "Dewayne Hyatt",
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Title = "I'll compress the"
                        },
                        new
                        {
                            Id = new Guid("595fa0b3-bcbf-4df1-45b8-98461c1dde97"),
                            Album = "Practical Steel Computer",
                            Author = "Rod Kautzer",
                            Duration = new TimeSpan(0, 0, 2, 59, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("90430125-eb32-56a4-3db8-cc4710467157"),
                            Album = "Unbranded Soft Cheese",
                            Author = "Elyssa Schiller",
                            Duration = new TimeSpan(0, 0, 3, 6, 0),
                            Title = "If we calculate"
                        },
                        new
                        {
                            Id = new Guid("452534ca-994c-4328-7508-133178875a30"),
                            Album = "Tasty Metal Ball",
                            Author = "Dedric Gislason",
                            Duration = new TimeSpan(0, 0, 2, 59, 0),
                            Title = "Use the cross-platform"
                        },
                        new
                        {
                            Id = new Guid("e21b469f-113c-088c-9386-fa771d2ee184"),
                            Album = "Gorgeous Metal Sausages",
                            Author = "Marianna Hettinger",
                            Duration = new TimeSpan(0, 0, 3, 29, 0),
                            Title = "The ADP interface"
                        },
                        new
                        {
                            Id = new Guid("a3119096-12dd-2fa4-ed31-f467fb519d9f"),
                            Album = "Unbranded Fresh Salad",
                            Author = "Luciano Blick",
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("6cbd5370-412b-0272-7556-990b89b2975a"),
                            Album = "Rustic Metal Hat",
                            Author = "Buster Botsford",
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Title = "The SAS feed"
                        },
                        new
                        {
                            Id = new Guid("3447f187-36b2-99bf-7388-3bbade9b295b"),
                            Album = "Rustic Steel Shoes",
                            Author = "Tyrique Langworth",
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Title = "Use the 1080p"
                        },
                        new
                        {
                            Id = new Guid("c65e4c3e-f594-847a-0f65-5853f2fee697"),
                            Album = "Rustic Metal Table",
                            Author = "Fritz Grady",
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("b6a4d1f1-855b-265b-2974-26e820a54cb5"),
                            Album = "Refined Rubber Gloves",
                            Author = "Arturo O'Kon",
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "If we index"
                        },
                        new
                        {
                            Id = new Guid("d25805f6-a1fa-3d92-c0a2-f76da2bf6d35"),
                            Album = "Awesome Fresh Soap",
                            Author = "Michel Keebler",
                            Duration = new TimeSpan(0, 0, 3, 25, 0),
                            Title = "The JBOD protocol"
                        },
                        new
                        {
                            Id = new Guid("79407105-d659-2430-1c53-ee7f130ef4ba"),
                            Album = "Refined Plastic Pants",
                            Author = "Randi Schiller",
                            Duration = new TimeSpan(0, 0, 2, 33, 0),
                            Title = "Try to connect"
                        },
                        new
                        {
                            Id = new Guid("820a8d0a-098f-4f37-617d-13cc8f4918e4"),
                            Album = "Awesome Frozen Computer",
                            Author = "Donald Hirthe",
                            Duration = new TimeSpan(0, 0, 2, 49, 0),
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("936f6676-dabe-8e1a-496b-ef09d7a5592e"),
                            Album = "Fantastic Wooden Computer",
                            Author = "Maximillia Abbott",
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Title = "The JSON firewall"
                        },
                        new
                        {
                            Id = new Guid("86ebcd6f-c87b-fad8-0e80-0eb52f8a9a43"),
                            Album = "Incredible Concrete Tuna",
                            Author = "Jovany Satterfield",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "Use the neural"
                        },
                        new
                        {
                            Id = new Guid("0421bd3c-5030-7c1f-7f69-8d0ecd5e20f7"),
                            Album = "Awesome Metal Salad",
                            Author = "Gia Anderson",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "The CSS circuit"
                        },
                        new
                        {
                            Id = new Guid("9df56807-78d6-50be-5f09-85de6a1ec4ff"),
                            Album = "Awesome Cotton Computer",
                            Author = "Ed Feeney",
                            Duration = new TimeSpan(0, 0, 3, 24, 0),
                            Title = "The JSON program"
                        },
                        new
                        {
                            Id = new Guid("8cd1f973-a06e-1674-73ef-3854a0cf97fc"),
                            Album = "Small Frozen Pizza",
                            Author = "Shanel Yundt",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "I'll bypass the"
                        },
                        new
                        {
                            Id = new Guid("d84128ea-6894-65dd-37f8-6fc9aaad8ccc"),
                            Album = "Awesome Plastic Sausages",
                            Author = "Sophie Konopelski",
                            Duration = new TimeSpan(0, 0, 3, 8, 0),
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("1522168e-3af0-4a2b-ae5f-c037f231c445"),
                            Album = "Fantastic Steel Cheese",
                            Author = "Jailyn Yundt",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "I'll compress the"
                        },
                        new
                        {
                            Id = new Guid("0d638898-b334-20d7-d559-d86f81411edf"),
                            Album = "Practical Steel Chicken",
                            Author = "Gilbert Prohaska",
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Title = "I'll compress the"
                        },
                        new
                        {
                            Id = new Guid("40a69d9b-c237-25b1-fcb3-023f5aa36fd8"),
                            Album = "Ergonomic Plastic Shoes",
                            Author = "Enoch Price",
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("7639ae02-e647-3785-b398-37bf8ff9e270"),
                            Album = "Unbranded Metal Fish",
                            Author = "Blair Terry",
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Title = "bypassing the hard"
                        },
                        new
                        {
                            Id = new Guid("399ce73c-6315-4e23-7a8c-f7731e37254e"),
                            Album = "Sleek Granite Shirt",
                            Author = "Leanna Boehm",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Title = "Use the digital"
                        },
                        new
                        {
                            Id = new Guid("58aba9e0-8575-cbfb-fbfd-a92cd594f622"),
                            Album = "Rustic Wooden Sausages",
                            Author = "Marlee Schneider",
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Title = "synthesizing the interface"
                        });
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a55571c-5026-c92b-f08e-d2467b19eb3b"),
                            Age = 100,
                            Auth0Id = "auth0|2f51113811b58582f0f6b953",
                            EmailAddress = "Rocky.Schneider51@hotmail.com",
                            Gender = "Male",
                            Name = "Maiya"
                        },
                        new
                        {
                            Id = new Guid("0cf19b61-ead8-4a1f-dedf-253b1a19f953"),
                            Age = 73,
                            Auth0Id = "auth0|708b8e9a26246dc8c180428a",
                            EmailAddress = "Devin26@gmail.com",
                            Gender = "Female",
                            Name = "Hudson"
                        },
                        new
                        {
                            Id = new Guid("0b327472-1f14-2c4f-f4b9-57c2e58e042b"),
                            Age = 51,
                            Auth0Id = "auth0|6c2eb9758e47a3adb6059897",
                            EmailAddress = "Darien47@yahoo.com",
                            Gender = "Male",
                            Name = "Eleonore"
                        },
                        new
                        {
                            Id = new Guid("f0ccfb89-f1bb-d438-69d3-84d968ca1de4"),
                            Age = 98,
                            Auth0Id = "auth0|005c3a0e2b925d10715035cf",
                            EmailAddress = "Oceane_Ruecker40@yahoo.com",
                            Gender = "Male",
                            Name = "Irwin"
                        },
                        new
                        {
                            Id = new Guid("265efd82-23e1-5055-0ec1-99e1909eee51"),
                            Age = 68,
                            Auth0Id = "auth0|baff45a455ed41a5afb4ded2",
                            EmailAddress = "Camilla_Goyette@yahoo.com",
                            Gender = "Female",
                            Name = "Ryann"
                        },
                        new
                        {
                            Id = new Guid("b4565a79-c451-e1fa-a2fe-dfc6ff8952d4"),
                            Age = 26,
                            Auth0Id = "auth0|608da6edcc2d35d9bec40cea",
                            EmailAddress = "Domenic57@yahoo.com",
                            Gender = "Male",
                            Name = "Annamae"
                        },
                        new
                        {
                            Id = new Guid("78cc6070-4980-07c1-2d55-e70d9db375be"),
                            Age = 15,
                            Auth0Id = "auth0|1381d1fa2ec420b3aeb0885f",
                            EmailAddress = "Cleo.Romaguera80@gmail.com",
                            Gender = "Male",
                            Name = "Kylee"
                        },
                        new
                        {
                            Id = new Guid("ecd1ff1b-e67b-6ec1-86a6-d504a97024a3"),
                            Age = 73,
                            Auth0Id = "auth0|dff5029d98ae3fe1cf84c2a7",
                            EmailAddress = "Eldridge_Heller52@hotmail.com",
                            Gender = "Male",
                            Name = "Milton"
                        },
                        new
                        {
                            Id = new Guid("866293ea-f419-3c74-37a3-acfa8809bb01"),
                            Age = 64,
                            Auth0Id = "auth0|431fbbb4792d4ea0fb02931b",
                            EmailAddress = "Ola72@gmail.com",
                            Gender = "Female",
                            Name = "Alexa"
                        },
                        new
                        {
                            Id = new Guid("e2c7bad6-e520-2637-bf5f-1655295e33a9"),
                            Age = 46,
                            Auth0Id = "auth0|d7b6e1a126e9ff1c04c23e94",
                            EmailAddress = "Zechariah_McCullough63@yahoo.com",
                            Gender = "Male",
                            Name = "Edna"
                        },
                        new
                        {
                            Id = new Guid("3e2e7eff-03ed-fb51-8b66-f9f7e90b5a76"),
                            Age = 54,
                            Auth0Id = "auth0|81cdcefe7262032c85516cd4",
                            EmailAddress = "Malachi.Harris@hotmail.com",
                            Gender = "Male",
                            Name = "Serena"
                        },
                        new
                        {
                            Id = new Guid("c2246c1d-89ab-1cb3-5de1-80fbc7452042"),
                            Age = 72,
                            Auth0Id = "auth0|6447208c38f13950a546d3f0",
                            EmailAddress = "Chyna84@yahoo.com",
                            Gender = "Male",
                            Name = "Sid"
                        },
                        new
                        {
                            Id = new Guid("379cf832-8f81-a957-af5e-eced582074a6"),
                            Age = 62,
                            Auth0Id = "auth0|765480824399de75eedfb0ea",
                            EmailAddress = "Dejuan_Haag@yahoo.com",
                            Gender = "Female",
                            Name = "Jermaine"
                        },
                        new
                        {
                            Id = new Guid("929ce18a-987f-8050-daa7-a68a5b66bdc9"),
                            Age = 36,
                            Auth0Id = "auth0|156988978ac0c3aab17fb8d7",
                            EmailAddress = "Clint1@yahoo.com",
                            Gender = "Male",
                            Name = "Enos"
                        },
                        new
                        {
                            Id = new Guid("86a5f586-9356-c520-56cf-a74d613d8d83"),
                            Age = 85,
                            Auth0Id = "auth0|1535cf887f4e5a78687c076b",
                            EmailAddress = "Name2@hotmail.com",
                            Gender = "Female",
                            Name = "Bella"
                        },
                        new
                        {
                            Id = new Guid("c3d55153-3986-d237-762e-2a76fc42d63d"),
                            Age = 17,
                            Auth0Id = "auth0|4d611989f74d395718abccb8",
                            EmailAddress = "Giuseppe.Jaskolski4@hotmail.com",
                            Gender = "Female",
                            Name = "Blanca"
                        },
                        new
                        {
                            Id = new Guid("5dc8ad76-49f7-80c2-bd08-8d65dad270bb"),
                            Age = 63,
                            Auth0Id = "auth0|43268d72ef231de6321e0d6d",
                            EmailAddress = "Jay_Cummerata@yahoo.com",
                            Gender = "Female",
                            Name = "Alva"
                        },
                        new
                        {
                            Id = new Guid("e4cfc815-3aa1-7b93-2173-b65f52b832fe"),
                            Age = 37,
                            Auth0Id = "auth0|be664f36c55f55b068af6199",
                            EmailAddress = "Marie68@hotmail.com",
                            Gender = "Female",
                            Name = "Ulises"
                        },
                        new
                        {
                            Id = new Guid("c21587eb-a5ce-fc9f-b788-85944d7805cb"),
                            Age = 44,
                            Auth0Id = "auth0|7b4fb00a4d7846411b64d384",
                            EmailAddress = "Annette5@gmail.com",
                            Gender = "Female",
                            Name = "Daniela"
                        },
                        new
                        {
                            Id = new Guid("2bc16a08-bd79-3f4c-78f5-82f459651adf"),
                            Age = 61,
                            Auth0Id = "auth0|cf68da0320cafa947cb71dbd",
                            EmailAddress = "Coy86@hotmail.com",
                            Gender = "Male",
                            Name = "Rigoberto"
                        },
                        new
                        {
                            Id = new Guid("289aeedd-ea39-f13c-de85-52c7ea8161d0"),
                            Age = 44,
                            Auth0Id = "auth0|3f3f1d6f39be703485f6099a",
                            EmailAddress = "Moses.Witting@yahoo.com",
                            Gender = "Female",
                            Name = "Thora"
                        },
                        new
                        {
                            Id = new Guid("b5f6a58e-161c-3ad5-265d-89020ae34f9c"),
                            Age = 16,
                            Auth0Id = "auth0|dfc1415a5808166d318a32ae",
                            EmailAddress = "Casper_Jerde57@gmail.com",
                            Gender = "Female",
                            Name = "Austin"
                        },
                        new
                        {
                            Id = new Guid("2f3191fb-7b43-e21c-1ef7-3a0bdf30ef5e"),
                            Age = 45,
                            Auth0Id = "auth0|0d06f8a5d03ffecf0915d30b",
                            EmailAddress = "Akeem.Kub@gmail.com",
                            Gender = "Male",
                            Name = "Darrick"
                        },
                        new
                        {
                            Id = new Guid("131551d9-8b51-aa9b-5f4f-60149b73ce36"),
                            Age = 65,
                            Auth0Id = "auth0|e382a76cd42b83d8af9c2165",
                            EmailAddress = "Stefan_OKon@hotmail.com",
                            Gender = "Female",
                            Name = "Lottie"
                        },
                        new
                        {
                            Id = new Guid("0e59f64a-393f-8e5f-c0b9-727020618505"),
                            Age = 89,
                            Auth0Id = "auth0|5382bb1cc37f9b50b3fc99b7",
                            EmailAddress = "Abdiel12@hotmail.com",
                            Gender = "Male",
                            Name = "Friedrich"
                        },
                        new
                        {
                            Id = new Guid("a72240dd-7e82-3f97-9241-3474c8a08aaf"),
                            Age = 76,
                            Auth0Id = "auth0|9d94419b81c0bd8a512e61b4",
                            EmailAddress = "Boyd7@hotmail.com",
                            Gender = "Female",
                            Name = "Arlene"
                        },
                        new
                        {
                            Id = new Guid("a69b52b6-c94c-8597-3caa-d96c3f343546"),
                            Age = 73,
                            Auth0Id = "auth0|4c4a76a71424fc97509b211b",
                            EmailAddress = "Rebekah_Schimmel@yahoo.com",
                            Gender = "Female",
                            Name = "Tyshawn"
                        },
                        new
                        {
                            Id = new Guid("bea1547b-b9d1-f09e-93b5-fda972d6c8f6"),
                            Age = 22,
                            Auth0Id = "auth0|03d889a3a9af9d1893aa44a4",
                            EmailAddress = "Hailey_Welch28@yahoo.com",
                            Gender = "Female",
                            Name = "Nova"
                        },
                        new
                        {
                            Id = new Guid("c77b6191-dd09-bdfd-02c2-b6293ab1188b"),
                            Age = 55,
                            Auth0Id = "auth0|cb330fc98cf2b7d49400ed7d",
                            EmailAddress = "Alek_McLaughlin@gmail.com",
                            Gender = "Male",
                            Name = "Laila"
                        },
                        new
                        {
                            Id = new Guid("dff46f0a-6755-3f32-8800-9bed12a121e3"),
                            Age = 54,
                            Auth0Id = "auth0|dfd0773f359ff22a4e4e8b2b",
                            EmailAddress = "Alda.Hegmann@yahoo.com",
                            Gender = "Female",
                            Name = "Kathlyn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
