// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vladify.DataAccess;

#nullable disable

namespace Vladify.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429190046_addedRelations")]
    partial class addedRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlaylistsId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("PlaylistSong");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Album = "Practical Plastic Table",
                            AuthorId = new Guid("26ee05f4-43fb-85e9-4dc6-833c087e1147"),
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Title = "backing up the"
                        },
                        new
                        {
                            Id = new Guid("2ad217f1-3a68-3f7a-3e33-fa753b02cd7c"),
                            Album = "Ergonomic Fresh Towels",
                            AuthorId = new Guid("0bddd8d3-f591-f8cc-039c-246c388ccb73"),
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("10ef0fbc-c412-c0b5-2153-9a65f9f07585"),
                            Album = "Rustic Steel Salad",
                            AuthorId = new Guid("0fa86638-9eaf-6eab-0044-925efdc11327"),
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "The RSS matrix"
                        },
                        new
                        {
                            Id = new Guid("9231a270-ab09-e7af-1bf8-69d5b20fd1c1"),
                            Album = "Handmade Soft Tuna",
                            AuthorId = new Guid("26e2acf9-d21f-764d-e93c-9bfcea2ebaf9"),
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "You can't parse"
                        },
                        new
                        {
                            Id = new Guid("9841a693-344d-9dc1-69e7-b51a99feed43"),
                            Album = "Sleek Frozen Gloves",
                            AuthorId = new Guid("c435d2c9-aba8-13a3-88de-0eac5fab7821"),
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Title = "The THX monitor"
                        },
                        new
                        {
                            Id = new Guid("5c98ebb5-3e4f-b9ae-4f1d-bb2c67978025"),
                            Album = "Gorgeous Metal Shirt",
                            AuthorId = new Guid("96df2011-653b-ab86-3746-3a83037a9486"),
                            Duration = new TimeSpan(0, 0, 3, 10, 0),
                            Title = "Try to input"
                        },
                        new
                        {
                            Id = new Guid("e6e78d59-4620-878d-2527-1695b0f4ae86"),
                            Album = "Practical Cotton Tuna",
                            AuthorId = new Guid("a2465130-0936-05cd-cc67-ae291ff0d951"),
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Title = "overriding the microchip"
                        },
                        new
                        {
                            Id = new Guid("15703e16-5187-fc8b-ad3c-76b7e845d5b2"),
                            Album = "Ergonomic Granite Chair",
                            AuthorId = new Guid("5c008de3-4c36-7d44-14fe-7ac56ba800ba"),
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Title = "Try to connect"
                        },
                        new
                        {
                            Id = new Guid("4d56cd88-22e4-77d9-ba00-e40a2a262126"),
                            Album = "Awesome Plastic Ball",
                            AuthorId = new Guid("ec5b47d4-47f9-8cf5-3e66-4ff342ff6a26"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Title = "I'll parse the"
                        },
                        new
                        {
                            Id = new Guid("72604c7c-d7ea-9e58-e505-3c2f0611dd23"),
                            Album = "Gorgeous Concrete Chips",
                            AuthorId = new Guid("33d1c0eb-a443-6458-bafa-a2d2c7ea6f02"),
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("5cb84213-5438-cf71-2fef-8fa85bbb9470"),
                            Album = "Incredible Cotton Pizza",
                            AuthorId = new Guid("513b174b-254b-7b6b-3cac-753622b26b5f"),
                            Duration = new TimeSpan(0, 0, 3, 29, 0),
                            Title = "You can't hack"
                        },
                        new
                        {
                            Id = new Guid("bbc9b414-3f5f-610d-d4eb-587ae271e0d5"),
                            Album = "Gorgeous Granite Salad",
                            AuthorId = new Guid("3a1e0f1e-4cd1-27ac-078d-ac190fecd72d"),
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "connecting the feed"
                        },
                        new
                        {
                            Id = new Guid("00133a77-3a59-6194-90c5-2d29e630eba5"),
                            Album = "Gorgeous Frozen Shoes",
                            AuthorId = new Guid("bb34e3da-ff82-0965-8d6c-8e0f2bc4d489"),
                            Duration = new TimeSpan(0, 0, 2, 32, 0),
                            Title = "overriding the panel"
                        },
                        new
                        {
                            Id = new Guid("fe7e8640-5d21-73c0-80ac-a73ec9739b67"),
                            Album = "Handmade Steel Car",
                            AuthorId = new Guid("965cc358-7b62-655b-4ec2-182d55b98673"),
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "You can't parse"
                        },
                        new
                        {
                            Id = new Guid("cbbe5302-f9c4-a7f3-7e45-7d293332c0b6"),
                            Album = "Handmade Rubber Chicken",
                            AuthorId = new Guid("3a82b17a-c558-ecd0-5e0b-72095494ca69"),
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("3cde35e4-901a-7757-77f1-ec1069e42272"),
                            Album = "Awesome Fresh Chair",
                            AuthorId = new Guid("ac4e26d5-3489-facf-ef39-fa6d9c60212a"),
                            Duration = new TimeSpan(0, 0, 3, 25, 0),
                            Title = "You can't index"
                        },
                        new
                        {
                            Id = new Guid("dce4d4e0-26f4-974f-624a-82f780bdb531"),
                            Album = "Tasty Plastic Pants",
                            AuthorId = new Guid("0527ab7a-e955-4626-aa45-acc860e000ff"),
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "I'll parse the"
                        },
                        new
                        {
                            Id = new Guid("024de926-7b6e-3b45-9d1a-b721f7f317c8"),
                            Album = "Handcrafted Metal Bike",
                            AuthorId = new Guid("690878d6-659e-0969-b5c7-d3cf120c30e2"),
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Title = "I'll transmit the"
                        },
                        new
                        {
                            Id = new Guid("256eceb8-52b2-0095-9967-84d7831987f1"),
                            Album = "Gorgeous Frozen Towels",
                            AuthorId = new Guid("f9432b42-6cb4-454a-c754-92ec8b232673"),
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Title = "The SDD array"
                        },
                        new
                        {
                            Id = new Guid("31e4fd04-ad32-dd4c-c074-2da5f7b8191f"),
                            Album = "Incredible Concrete Shirt",
                            AuthorId = new Guid("04f4c5bb-74c5-c9dc-69fb-b76ae50f7ef7"),
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Title = "The ADP panel"
                        },
                        new
                        {
                            Id = new Guid("a01cf8f3-9cd0-cc79-7eb3-ff22611e03a9"),
                            Album = "Refined Concrete Fish",
                            AuthorId = new Guid("b562bd8e-6028-5aa8-ebf1-011df1eb287b"),
                            Duration = new TimeSpan(0, 0, 3, 27, 0),
                            Title = "Use the virtual"
                        },
                        new
                        {
                            Id = new Guid("a7dcc147-dc07-c0b4-4699-959f42f8f8cb"),
                            Album = "Generic Concrete Table",
                            AuthorId = new Guid("8c012d76-8bad-dcbf-a0b3-3e743486e1ae"),
                            Duration = new TimeSpan(0, 0, 2, 44, 0),
                            Title = "The GB feed"
                        },
                        new
                        {
                            Id = new Guid("bb12c7e2-f9a8-5109-2da9-4a6420f16e85"),
                            Album = "Small Rubber Keyboard",
                            AuthorId = new Guid("57ba44a2-bb90-68fd-2374-8b440ccd33f8"),
                            Duration = new TimeSpan(0, 0, 2, 35, 0),
                            Title = "indexing the card"
                        },
                        new
                        {
                            Id = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Album = "Sleek Cotton Tuna",
                            AuthorId = new Guid("40e37dfc-c3d3-b97b-f918-2b614b2182ea"),
                            Duration = new TimeSpan(0, 0, 2, 30, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("6dcbc63b-2a63-09d2-13c7-7fa941e3f428"),
                            Album = "Small Granite Tuna",
                            AuthorId = new Guid("da8d31c6-e4ac-6332-9161-26808e995210"),
                            Duration = new TimeSpan(0, 0, 3, 6, 0),
                            Title = "I'll bypass the"
                        },
                        new
                        {
                            Id = new Guid("0ffcfcbf-34b8-3837-cf9d-3cfebbba9515"),
                            Album = "Rustic Steel Mouse",
                            AuthorId = new Guid("a8cd81b0-eaed-dbf2-76c1-34ba310efc55"),
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Title = "compressing the transmitter"
                        },
                        new
                        {
                            Id = new Guid("65f546dc-a7d5-6b91-62fc-59cb08581aaf"),
                            Album = "Practical Frozen Shoes",
                            AuthorId = new Guid("5b61f845-8efa-effb-8c8a-9b57e1dada3c"),
                            Duration = new TimeSpan(0, 0, 2, 35, 0),
                            Title = "connecting the bandwidth"
                        },
                        new
                        {
                            Id = new Guid("0f99ee8b-696d-0b19-6706-4aec11fa93ab"),
                            Album = "Rustic Frozen Bike",
                            AuthorId = new Guid("577fcd7b-2de8-2cd8-5256-c5b013d78f47"),
                            Duration = new TimeSpan(0, 0, 3, 21, 0),
                            Title = "Use the digital"
                        },
                        new
                        {
                            Id = new Guid("03b18792-8f7a-ac07-9f49-2c0d2c237f3b"),
                            Album = "Refined Frozen Soap",
                            AuthorId = new Guid("facea4be-b82d-e71e-c0d5-e6acd9013d77"),
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "You can't copy"
                        },
                        new
                        {
                            Id = new Guid("1fabe348-3326-7545-e0e6-f3ad9c12ae3f"),
                            Album = "Fantastic Steel Shoes",
                            AuthorId = new Guid("8f994d6c-f05a-225d-0836-f5c69f987088"),
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Title = "You can't reboot"
                        },
                        new
                        {
                            Id = new Guid("392ad14d-c224-6c37-9545-523ef9d7529d"),
                            Album = "Fantastic Concrete Cheese",
                            AuthorId = new Guid("79b9dc93-23a3-b07a-2c24-bfe3eb488a62"),
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Title = "If we hack"
                        },
                        new
                        {
                            Id = new Guid("e30babc4-5f0e-28a2-a5df-8adc9ec7db94"),
                            Album = "Tasty Wooden Pizza",
                            AuthorId = new Guid("ba92b2cc-710e-495b-c3c1-4b8ba8847d17"),
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Title = "I'll hack the"
                        },
                        new
                        {
                            Id = new Guid("d3ef43fd-5d8e-4fe3-3db7-a3e42fd28932"),
                            Album = "Rustic Soft Salad",
                            AuthorId = new Guid("099005da-0c05-6668-a2f4-dee8b93e54af"),
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Title = "synthesizing the alarm"
                        },
                        new
                        {
                            Id = new Guid("65b8b9d0-ef94-58c2-5242-d007e266d5c0"),
                            Album = "Practical Steel Bacon",
                            AuthorId = new Guid("4aaadd8d-039b-6057-03c6-b4762d4616ce"),
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "I'll reboot the"
                        },
                        new
                        {
                            Id = new Guid("5f98c9b3-8ec0-2708-788a-fd5b25980e7c"),
                            Album = "Rustic Frozen Soap",
                            AuthorId = new Guid("4a219fde-6d13-8541-9484-e1a21ecd4fa2"),
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "The THX firewall"
                        },
                        new
                        {
                            Id = new Guid("055a7822-2ede-f9a6-453f-05b7a3fc8a1f"),
                            Album = "Small Rubber Shirt",
                            AuthorId = new Guid("da2c1490-39c9-74c1-ea93-c61ea1ff717a"),
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Title = "The IB bandwidth"
                        },
                        new
                        {
                            Id = new Guid("ce3c2ecd-87f1-8357-65eb-60bb46bd5b9f"),
                            Album = "Gorgeous Rubber Towels",
                            AuthorId = new Guid("01c469b9-e117-6c7e-8c97-ee7f089f8cd5"),
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Title = "The JBOD hard"
                        },
                        new
                        {
                            Id = new Guid("b9614d63-d6a4-7f6a-72b1-5700315127f8"),
                            Album = "Awesome Plastic Towels",
                            AuthorId = new Guid("1f6c25b9-ae26-a48d-c919-b8e289149259"),
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Title = "Use the cross-platform"
                        },
                        new
                        {
                            Id = new Guid("6b272fa4-465b-86c7-7c67-6e41d314447f"),
                            Album = "Fantastic Metal Sausages",
                            AuthorId = new Guid("166f3867-2202-398b-00aa-d9bbe25edfa5"),
                            Duration = new TimeSpan(0, 0, 3, 17, 0),
                            Title = "hacking the array"
                        },
                        new
                        {
                            Id = new Guid("621f47a9-04f5-6374-1e2a-e25b22572c5d"),
                            Album = "Handcrafted Fresh Car",
                            AuthorId = new Guid("c36a6ad3-8c88-58d0-c6a2-bcaaf97233fb"),
                            Duration = new TimeSpan(0, 0, 3, 23, 0),
                            Title = "transmitting the monitor"
                        },
                        new
                        {
                            Id = new Guid("dea8f8e4-52dd-5dad-d26a-d14d282f023c"),
                            Album = "Practical Soft Gloves",
                            AuthorId = new Guid("b270b45c-8016-5cda-bd96-4b3929f517bd"),
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "navigating the hard"
                        },
                        new
                        {
                            Id = new Guid("0bff21b5-739e-6eba-9e50-98f1134e5b97"),
                            Album = "Ergonomic Rubber Car",
                            AuthorId = new Guid("02b6996a-2c31-4b83-39e0-7b12f7bd41b6"),
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Title = "Use the mobile"
                        },
                        new
                        {
                            Id = new Guid("6a422f78-47aa-a2f0-4c73-7980baf93708"),
                            Album = "Handmade Cotton Mouse",
                            AuthorId = new Guid("84df6dd9-c4e5-865c-6643-bab486bf51c6"),
                            Duration = new TimeSpan(0, 0, 2, 51, 0),
                            Title = "If we synthesize"
                        },
                        new
                        {
                            Id = new Guid("cb0ab8e4-e77f-0943-dd89-67b2d80b0a2c"),
                            Album = "Generic Metal Chips",
                            AuthorId = new Guid("547db553-7493-3d88-0c87-6c0bdb5a859c"),
                            Duration = new TimeSpan(0, 0, 2, 33, 0),
                            Title = "You can't navigate"
                        },
                        new
                        {
                            Id = new Guid("d4f53a08-378e-87af-c2ee-76b5417d08ed"),
                            Album = "Handmade Soft Keyboard",
                            AuthorId = new Guid("219e84cb-76e9-7455-a35f-742725c57dcd"),
                            Duration = new TimeSpan(0, 0, 2, 59, 0),
                            Title = "If we generate"
                        },
                        new
                        {
                            Id = new Guid("881185d1-0acb-1d63-0a2f-53d5c5be2616"),
                            Album = "Awesome Granite Chair",
                            AuthorId = new Guid("c5941e9e-66ab-f8b4-e878-8eccedff793b"),
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Title = "I'll program the"
                        },
                        new
                        {
                            Id = new Guid("9e0146df-a0dd-114e-c601-c9bd66f80df0"),
                            Album = "Gorgeous Concrete Pants",
                            AuthorId = new Guid("499746dc-c371-d53a-62f9-311fa2c07e45"),
                            Duration = new TimeSpan(0, 0, 2, 55, 0),
                            Title = "If we program"
                        },
                        new
                        {
                            Id = new Guid("3bea64e4-7f82-dc81-a6d2-8e6cab807d62"),
                            Album = "Awesome Frozen Fish",
                            AuthorId = new Guid("d0dbfe03-6ca4-896d-a37a-64b4a259c715"),
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "Try to hack"
                        },
                        new
                        {
                            Id = new Guid("69abf1cb-79b7-bdb4-e1c0-248dec8f275a"),
                            Album = "Incredible Rubber Bike",
                            AuthorId = new Guid("ad190507-a61f-a292-5a89-4be47e4b8527"),
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Title = "Use the 1080p"
                        },
                        new
                        {
                            Id = new Guid("fb49acc3-ebb7-5a3d-4eda-466f61ca8c8b"),
                            Album = "Fantastic Soft Salad",
                            AuthorId = new Guid("76db0591-33d5-7ffb-f83d-b8d7e6501adb"),
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("334cccd0-bff9-58bf-f79c-128c030193b7"),
                            Album = "Tasty Steel Salad",
                            AuthorId = new Guid("b3d38c69-5fa0-bf59-bcf1-4d45b898461c"),
                            Duration = new TimeSpan(0, 0, 3, 14, 0),
                            Title = "I'll compress the"
                        },
                        new
                        {
                            Id = new Guid("f3e997de-3cf4-2025-d62b-34796f572501"),
                            Album = "Ergonomic Granite Towels",
                            AuthorId = new Guid("71461047-8d57-459f-c69b-0f61fc7450ae"),
                            Duration = new TimeSpan(0, 0, 3, 6, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("452534ca-994c-4328-7508-133178875a30"),
                            Album = "Tasty Metal Ball",
                            AuthorId = new Guid("9f15bca9-1b46-3ce2-118c-089386fa771d"),
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Title = "Use the cross-platform"
                        },
                        new
                        {
                            Id = new Guid("148b84e1-134d-31b5-d6c7-24cfe54a9690"),
                            Album = "Ergonomic Plastic Fish",
                            AuthorId = new Guid("9d51fb67-b29f-c1b4-809d-19081f5ba860"),
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "Try to copy"
                        },
                        new
                        {
                            Id = new Guid("6cbd5370-412b-0272-7556-990b89b2975a"),
                            Album = "Rustic Metal Hat",
                            AuthorId = new Guid("877cad65-47f1-b234-36bf-9973883bbade"),
                            Duration = new TimeSpan(0, 0, 2, 44, 0),
                            Title = "The SAS feed"
                        },
                        new
                        {
                            Id = new Guid("b51a5b29-ebf6-ae81-0076-90fbda393e4c"),
                            Album = "Rustic Steel Fish",
                            AuthorId = new Guid("e6fef253-aa97-855d-f80c-b956586ec1fb"),
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("b6a4d1f1-855b-265b-2974-26e820a54cb5"),
                            Album = "Refined Rubber Gloves",
                            AuthorId = new Guid("f6842ce2-5805-fad2-a192-3dc0a2f76da2"),
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Title = "If we index"
                        },
                        new
                        {
                            Id = new Guid("9c37356d-66d7-a06d-fbca-c87711880571"),
                            Album = "Practical Granite Car",
                            AuthorId = new Guid("f40e137f-acba-e08b-08fa-96fad90ac517"),
                            Duration = new TimeSpan(0, 0, 2, 33, 0),
                            Title = "Try to compress"
                        },
                        new
                        {
                            Id = new Guid("820a8d0a-098f-4f37-617d-13cc8f4918e4"),
                            Album = "Awesome Frozen Computer",
                            AuthorId = new Guid("766f8e09-6f66-be93-da1a-8e496bef09d7"),
                            Duration = new TimeSpan(0, 0, 2, 57, 0),
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("13772e59-b078-167d-2ab2-72b9aac96fcd"),
                            Album = "Rustic Rubber Ball",
                            AuthorId = new Guid("9a8a2fb5-6843-864a-06e7-efc58390ddf1"),
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "navigating the interface"
                        },
                        new
                        {
                            Id = new Guid("0421bd3c-5030-7c1f-7f69-8d0ecd5e20f7"),
                            Album = "Awesome Metal Salad",
                            AuthorId = new Guid("077fe2a3-f568-d69d-78be-505f0985de6a"),
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Title = "The CSS circuit"
                        },
                        new
                        {
                            Id = new Guid("77bcffc4-8939-cecf-7dcd-5cfee45573f9"),
                            Album = "Gorgeous Fresh Gloves",
                            AuthorId = new Guid("97cfa054-3dfc-89a2-5d22-4a6bba6958af"),
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "calculating the system"
                        },
                        new
                        {
                            Id = new Guid("d84128ea-6894-65dd-37f8-6fc9aaad8ccc"),
                            Album = "Awesome Plastic Sausages",
                            AuthorId = new Guid("8e293386-2216-f015-3a2b-4aae5fc037f2"),
                            Duration = new TimeSpan(0, 0, 3, 25, 0),
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("bf3245c4-75b3-9ebd-7b85-6fb002699888"),
                            Album = "Handcrafted Frozen Cheese",
                            AuthorId = new Guid("1e41816f-23df-0cb1-04bc-4a86b5d3be6b"),
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Title = "You can't input"
                        },
                        new
                        {
                            Id = new Guid("40a69d9b-c237-25b1-fcb3-023f5aa36fd8"),
                            Album = "Ergonomic Plastic Shoes",
                            AuthorId = new Guid("024eacfe-39ae-4776-e685-37b39837bf8f"),
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("cdae70e2-19a9-adda-cd8f-caef70ff3ce7"),
                            Album = "Rustic Wooden Mouse",
                            AuthorId = new Guid("25371e73-0c4e-ed34-86b8-f00fd5549374"),
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Title = "compressing the sensor"
                        },
                        new
                        {
                            Id = new Guid("58aba9e0-8575-cbfb-fbfd-a92cd594f622"),
                            Album = "Rustic Wooden Sausages",
                            AuthorId = new Guid("d84b46ea-e5c7-ef82-ce6d-d0e09efd983c"),
                            Duration = new TimeSpan(0, 0, 2, 39, 0),
                            Title = "synthesizing the interface"
                        },
                        new
                        {
                            Id = new Guid("c18b0e52-24b0-ecfa-fe1e-98d1cc612615"),
                            Album = "Handcrafted Plastic Salad",
                            AuthorId = new Guid("42252606-3838-6661-2f2c-740a403a2251"),
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Title = "hacking the pixel"
                        },
                        new
                        {
                            Id = new Guid("1de9c6c8-0c02-caa9-4772-5a8d651ef663"),
                            Album = "Ergonomic Concrete Computer",
                            AuthorId = new Guid("0ab2349c-5115-5d1c-086b-513e1e031a7c"),
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("d807c5f0-0ec9-a67e-bc90-257c4002e0b1"),
                            Album = "Awesome Fresh Cheese",
                            AuthorId = new Guid("25a4b25d-a565-58e3-33d5-202f92d32633"),
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "connecting the transmitter"
                        },
                        new
                        {
                            Id = new Guid("e0f6c059-69c7-8c70-6c9d-4284b7bea4c9"),
                            Album = "Ergonomic Cotton Bike",
                            AuthorId = new Guid("82c02c0d-9220-c3b1-5bd8-61474e964833"),
                            Duration = new TimeSpan(0, 0, 2, 43, 0),
                            Title = "I'll navigate the"
                        },
                        new
                        {
                            Id = new Guid("d4a007f9-177b-657c-e966-cb59e201d5b4"),
                            Album = "Rustic Concrete Sausages",
                            AuthorId = new Guid("8242e65b-d659-a612-e85e-e3a150921544"),
                            Duration = new TimeSpan(0, 0, 3, 14, 0),
                            Title = "Use the bluetooth"
                        },
                        new
                        {
                            Id = new Guid("69e52b37-d679-928b-92dc-0a828fadfc0f"),
                            Album = "Handmade Wooden Pants",
                            AuthorId = new Guid("12f1a3fa-276c-6c28-ed14-dfab57e20fb6"),
                            Duration = new TimeSpan(0, 0, 2, 38, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("2308f9c7-b058-92e6-3d72-e40a39a79b2d"),
                            Album = "Intelligent Granite Table",
                            AuthorId = new Guid("641d98a1-3dbb-8221-f2c7-97b08fa1f20b"),
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("6144b42f-6db3-7d43-a163-dc1c70a14425"),
                            Album = "Generic Plastic Ball",
                            AuthorId = new Guid("7d04df47-dd26-8f40-fff6-009eb4ee2bd9"),
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Title = "Try to override"
                        },
                        new
                        {
                            Id = new Guid("6544d91a-2682-8a52-82ea-da4152ae7e80"),
                            Album = "Tasty Soft Salad",
                            AuthorId = new Guid("8743ab70-c858-f0ec-4766-5b7f22c4b9b1"),
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Title = "You can't index"
                        },
                        new
                        {
                            Id = new Guid("4d65f3a4-48ac-1d81-db82-9e99e7a053a7"),
                            Album = "Incredible Plastic Shoes",
                            AuthorId = new Guid("0123470b-a7b6-8ed3-0cd6-923740c363c1"),
                            Duration = new TimeSpan(0, 0, 2, 55, 0),
                            Title = "The SMTP sensor"
                        },
                        new
                        {
                            Id = new Guid("564d467d-c660-d707-4bb3-3ea2ef7ad176"),
                            Album = "Intelligent Frozen Keyboard",
                            AuthorId = new Guid("6fc1cada-4d97-4d17-9aac-daa0faab811b"),
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "If we connect"
                        },
                        new
                        {
                            Id = new Guid("eb94f36b-5b1d-c0c0-4422-62624d586b83"),
                            Album = "Awesome Wooden Shirt",
                            AuthorId = new Guid("d6f7ce55-f501-437e-f2b8-e7361fbd6e00"),
                            Duration = new TimeSpan(0, 0, 2, 59, 0),
                            Title = "You can't program"
                        },
                        new
                        {
                            Id = new Guid("eab52a52-534c-1d6f-af25-85d4c1b78e6d"),
                            Album = "Tasty Metal Bike",
                            AuthorId = new Guid("4c84a05a-c82c-468d-b861-3a716b087b87"),
                            Duration = new TimeSpan(0, 0, 2, 44, 0),
                            Title = "You can't copy"
                        },
                        new
                        {
                            Id = new Guid("6ff9cf51-0130-c859-88f5-e236c50ffed1"),
                            Album = "Gorgeous Granite Chicken",
                            AuthorId = new Guid("fb535609-be2b-4111-30f1-5deaaf2a9f2a"),
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Title = "I'll copy the"
                        },
                        new
                        {
                            Id = new Guid("0faad2a3-51f2-a03c-a016-c89ce8ce7200"),
                            Album = "Handcrafted Metal Mouse",
                            AuthorId = new Guid("e7a11d94-c71b-c014-4ce0-8a4d7d160517"),
                            Duration = new TimeSpan(0, 0, 2, 44, 0),
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("a549a88a-2348-e9ea-cd03-f425b6459cda"),
                            Album = "Ergonomic Soft Bike",
                            AuthorId = new Guid("b3e8ee9b-1063-eea5-72d2-8e87504cfab6"),
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Title = "You can't back"
                        },
                        new
                        {
                            Id = new Guid("9a1fc44d-9a96-73ee-63b8-d17ba2055995"),
                            Album = "Practical Concrete Soap",
                            AuthorId = new Guid("520d7344-11ca-e439-bb37-8a94410554fa"),
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Title = "backing up the"
                        },
                        new
                        {
                            Id = new Guid("72d45700-cccf-f135-87a0-c5b4c7e3d0d0"),
                            Album = "Unbranded Fresh Sausages",
                            AuthorId = new Guid("01cecee6-a687-07e0-f669-9c7bc574a6d8"),
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "If we hack"
                        },
                        new
                        {
                            Id = new Guid("30737043-53f4-c3ba-deb4-2c191f67af3c"),
                            Album = "Awesome Rubber Bacon",
                            AuthorId = new Guid("55347ad0-dc9d-0880-bf56-372466f27a13"),
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Title = "You can't back"
                        },
                        new
                        {
                            Id = new Guid("eeb4f1a8-02d7-3eed-e98b-a8717143758f"),
                            Album = "Tasty Soft Towels",
                            AuthorId = new Guid("18771160-f674-5383-b257-0830bef97847"),
                            Duration = new TimeSpan(0, 0, 3, 8, 0),
                            Title = "Try to calculate"
                        },
                        new
                        {
                            Id = new Guid("97d851b3-124d-94c1-e3cf-a18dcf681908"),
                            Album = "Unbranded Granite Soap",
                            AuthorId = new Guid("5e6cebbe-29c4-3e61-578c-86d27a12feb5"),
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Title = "Use the neural"
                        },
                        new
                        {
                            Id = new Guid("c5e22791-eee3-27ef-e282-87d1f03ebcb4"),
                            Album = "Refined Steel Pizza",
                            AuthorId = new Guid("3592db77-6462-c0f2-a3e4-6d4257dbfc7d"),
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "Use the auxiliary"
                        },
                        new
                        {
                            Id = new Guid("6dd9a7e2-4e67-1eca-0083-d7604d7281a2"),
                            Album = "Handcrafted Fresh Car",
                            AuthorId = new Guid("724e5a4d-b321-d72a-ff3c-fe66e10f8dc7"),
                            Duration = new TimeSpan(0, 0, 2, 59, 0),
                            Title = "The GB program"
                        },
                        new
                        {
                            Id = new Guid("5f1be161-7155-9fec-e16f-e92044628944"),
                            Album = "Ergonomic Concrete Pants",
                            AuthorId = new Guid("3c82364e-5c95-9486-da1e-3c79b1f7e861"),
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "Use the bluetooth"
                        },
                        new
                        {
                            Id = new Guid("b7404440-d9ba-2175-84f4-994b6b82116d"),
                            Album = "Generic Concrete Salad",
                            AuthorId = new Guid("cb4d4469-23ab-1a0a-d99e-8b6cd1935d0d"),
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "Use the digital"
                        },
                        new
                        {
                            Id = new Guid("49ec6710-9c6f-0b2b-d9ef-adf86ef431dd"),
                            Album = "Refined Frozen Pants",
                            AuthorId = new Guid("0185e392-7406-5cde-483a-aa7642faa721"),
                            Duration = new TimeSpan(0, 0, 2, 59, 0),
                            Title = "You can't hack"
                        },
                        new
                        {
                            Id = new Guid("225c33d1-aa6a-8f5a-a542-c7e5c437955d"),
                            Album = "Awesome Granite Tuna",
                            AuthorId = new Guid("6686b925-55e8-06ed-9607-9e310f27382a"),
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Title = "The SDD firewall"
                        },
                        new
                        {
                            Id = new Guid("76163160-0284-1815-2b1d-ee7bb4ffb78d"),
                            Album = "Unbranded Fresh Shirt",
                            AuthorId = new Guid("2bf7302e-b508-7b80-9871-4ab924a1b671"),
                            Duration = new TimeSpan(0, 0, 3, 21, 0),
                            Title = "The ADP sensor"
                        },
                        new
                        {
                            Id = new Guid("8afe38bd-08e1-a4e6-88e1-485649a3443b"),
                            Album = "Handmade Cotton Tuna",
                            AuthorId = new Guid("d46d8d1c-a361-6239-daff-b4dc554c2810"),
                            Duration = new TimeSpan(0, 0, 2, 39, 0),
                            Title = "You can't calculate"
                        },
                        new
                        {
                            Id = new Guid("2437d480-ce4f-7d05-8d4b-e453609ad090"),
                            Album = "Handmade Frozen Towels",
                            AuthorId = new Guid("5e8fa46e-0842-0ca9-66a2-9336dccdbf67"),
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "Use the auxiliary"
                        },
                        new
                        {
                            Id = new Guid("0e5458d4-657a-4ce4-cb87-ad97b6599628"),
                            Album = "Rustic Soft Mouse",
                            AuthorId = new Guid("593df8fa-f7ad-11bc-7a52-e5b9e6f43fab"),
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Title = "hacking the protocol"
                        },
                        new
                        {
                            Id = new Guid("75fc8076-48af-0dfc-aced-95f13789141a"),
                            Album = "Gorgeous Granite Mouse",
                            AuthorId = new Guid("6eb0073c-eb49-caea-0cd4-c23ed24baf40"),
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("1f260a00-c843-9fd0-1f75-d2041f58f00a"),
                            Album = "Tasty Rubber Cheese",
                            AuthorId = new Guid("db52b52a-34f5-67bd-a71d-85ca66f93ee0"),
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "I'll reboot the"
                        });
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Age = 19,
                            EmailAddress = "Sabina.Marvin26@gmail.com",
                            ExternalId = "auth0|d8b0d2646f930a379fe684d8",
                            Gender = "Female",
                            Name = "Marianne"
                        },
                        new
                        {
                            Id = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Age = 99,
                            EmailAddress = "Jeanette.Bartoletti@hotmail.com",
                            ExternalId = "auth0|d8d5248b2594d52b85cd5352",
                            Gender = "Female",
                            Name = "Joanie"
                        },
                        new
                        {
                            Id = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Age = 94,
                            EmailAddress = "Larue46@hotmail.com",
                            ExternalId = "auth0|1b95a2b93ad5c83c5c75374d",
                            Gender = "Male",
                            Name = "Marley"
                        },
                        new
                        {
                            Id = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            Age = 41,
                            EmailAddress = "Kacie.Renner92@hotmail.com",
                            ExternalId = "auth0|e486a6697cad876bc62f970b",
                            Gender = "Female",
                            Name = "Louie"
                        },
                        new
                        {
                            Id = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Age = 44,
                            EmailAddress = "Darron70@yahoo.com",
                            ExternalId = "auth0|c0734263ccfdaafd54b28c4a",
                            Gender = "Female",
                            Name = "Greyson"
                        },
                        new
                        {
                            Id = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            Age = 88,
                            EmailAddress = "Clotilde_Swaniawski@gmail.com",
                            ExternalId = "auth0|52a0838fcdcce32176a06863",
                            Gender = "Male",
                            Name = "Vernice"
                        },
                        new
                        {
                            Id = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            Age = 50,
                            EmailAddress = "Thaddeus_Doyle90@yahoo.com",
                            ExternalId = "auth0|71464b4db7170a63f5f66302",
                            Gender = "Male",
                            Name = "Guadalupe"
                        },
                        new
                        {
                            Id = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            Age = 90,
                            EmailAddress = "Ines_Balistreri@gmail.com",
                            ExternalId = "auth0|7af854402fac00e8a384ef82",
                            Gender = "Female",
                            Name = "Tressa"
                        },
                        new
                        {
                            Id = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            Age = 73,
                            EmailAddress = "Cesar.Kertzmann58@gmail.com",
                            ExternalId = "auth0|409472f82d94d3841f5bacac",
                            Gender = "Female",
                            Name = "Ephraim"
                        },
                        new
                        {
                            Id = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Age = 74,
                            EmailAddress = "Norbert_Schroeder@gmail.com",
                            ExternalId = "auth0|e58f8575cf3f8b24e6571f8d",
                            Gender = "Female",
                            Name = "William"
                        },
                        new
                        {
                            Id = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            Age = 91,
                            EmailAddress = "Delia_Weissnat@gmail.com",
                            ExternalId = "auth0|dc5306dedbf39ac445bfd733",
                            Gender = "Female",
                            Name = "Bridget"
                        },
                        new
                        {
                            Id = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Age = 52,
                            EmailAddress = "Domenick_Steuber@hotmail.com",
                            ExternalId = "auth0|535aae56811c2e6ed5cfb00c",
                            Gender = "Male",
                            Name = "Jada"
                        },
                        new
                        {
                            Id = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            Age = 49,
                            EmailAddress = "Manley_Cronin40@gmail.com",
                            ExternalId = "auth0|8e7649d4282d97b9af274259",
                            Gender = "Male",
                            Name = "Gerhard"
                        },
                        new
                        {
                            Id = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            Age = 38,
                            EmailAddress = "Stephen48@yahoo.com",
                            ExternalId = "auth0|966e3969e00ea631cb22f2a2",
                            Gender = "Male",
                            Name = "Arne"
                        },
                        new
                        {
                            Id = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Age = 43,
                            EmailAddress = "Daniella_Senger@gmail.com",
                            ExternalId = "auth0|ff55cad7b4daa656cc153a24",
                            Gender = "Female",
                            Name = "Shirley"
                        },
                        new
                        {
                            Id = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            Age = 73,
                            EmailAddress = "Sammie.Kilback58@hotmail.com",
                            ExternalId = "auth0|c2300db4d17770e0fd3b514d",
                            Gender = "Male",
                            Name = "Elisa"
                        },
                        new
                        {
                            Id = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            Age = 43,
                            EmailAddress = "Leslie44@yahoo.com",
                            ExternalId = "auth0|bccf82be5b1f4667c6b098af",
                            Gender = "Male",
                            Name = "Marcia"
                        },
                        new
                        {
                            Id = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            Age = 28,
                            EmailAddress = "Miller.Carter@gmail.com",
                            ExternalId = "auth0|0998f7431d4181ce6e9a5bb1",
                            Gender = "Male",
                            Name = "Rhoda"
                        },
                        new
                        {
                            Id = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            Age = 75,
                            EmailAddress = "Elmer76@yahoo.com",
                            ExternalId = "auth0|a41e05f4e8bbb2dfa3a3731a",
                            Gender = "Male",
                            Name = "Lester"
                        },
                        new
                        {
                            Id = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            Age = 65,
                            EmailAddress = "Timmy_Considine@yahoo.com",
                            ExternalId = "auth0|1932dbc737460922d683bbf7",
                            Gender = "Male",
                            Name = "Brennon"
                        },
                        new
                        {
                            Id = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Age = 53,
                            EmailAddress = "Jett.Robel53@gmail.com",
                            ExternalId = "auth0|287a0086ac05cae7e30e4994",
                            Gender = "Male",
                            Name = "Sterling"
                        },
                        new
                        {
                            Id = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Age = 42,
                            EmailAddress = "Halle_Pfannerstill73@gmail.com",
                            ExternalId = "auth0|7aba268e3c08c9249e9ad2f2",
                            Gender = "Male",
                            Name = "Maryam"
                        },
                        new
                        {
                            Id = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            Age = 58,
                            EmailAddress = "Mariano.Braun85@gmail.com",
                            ExternalId = "auth0|7e41734a9fdfdf60a11356ca",
                            Gender = "Male",
                            Name = "Pearline"
                        },
                        new
                        {
                            Id = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            Age = 67,
                            EmailAddress = "Corine.Cormier98@gmail.com",
                            ExternalId = "auth0|26bc1501a4483e815ee97872",
                            Gender = "Female",
                            Name = "Lelah"
                        },
                        new
                        {
                            Id = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            Age = 72,
                            EmailAddress = "Letha_Ratke@gmail.com",
                            ExternalId = "auth0|c1ea939e82e2e265a0c4df9e",
                            Gender = "Male",
                            Name = "Ernie"
                        },
                        new
                        {
                            Id = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            Age = 86,
                            EmailAddress = "Elizabeth_Braun@yahoo.com",
                            ExternalId = "auth0|69fe1fec7f569e507938043b",
                            Gender = "Female",
                            Name = "Brenda"
                        },
                        new
                        {
                            Id = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            Age = 28,
                            EmailAddress = "Amelie.Pollich@gmail.com",
                            ExternalId = "auth0|59183f9253c8ad6726aa967b",
                            Gender = "Female",
                            Name = "Enrique"
                        },
                        new
                        {
                            Id = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            Age = 66,
                            EmailAddress = "Emery.Kunde76@hotmail.com",
                            ExternalId = "auth0|e2f2df7f262fee8312871a9d",
                            Gender = "Female",
                            Name = "Monique"
                        },
                        new
                        {
                            Id = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            Age = 100,
                            EmailAddress = "Earnest67@hotmail.com",
                            ExternalId = "auth0|53d2d94826faf10990721115",
                            Gender = "Female",
                            Name = "Julien"
                        },
                        new
                        {
                            Id = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            Age = 61,
                            EmailAddress = "Lizzie52@hotmail.com",
                            ExternalId = "auth0|9d8a637327a243676fb0a2a2",
                            Gender = "Male",
                            Name = "Zaria"
                        });
                });

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vladify.DataAccess.Entities.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Playlist", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.User", "Owner")
                        .WithMany("Playlists")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.User", "Owner")
                        .WithMany("OwnedSongs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Navigation("OwnedSongs");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
