// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vladify.DataAccess.Storage;

#nullable disable

namespace Vladify.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918120821_addUrlsToSong")]
    partial class addUrlsToSong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("MessageId", "ConsumerId");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlaylistsId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("PlaylistSong");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fdea678-4a21-6d13-4185-9484e1a21ecd"),
                            Album = "Small Cotton Mouse",
                            AudioUrl = "https://desiree.net/benchmark/invoice",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            CoverUrl = "http://callie.info/incredible-wooden-shirt/generic",
                            Duration = new TimeSpan(0, 0, 3, 11, 0),
                            Status = "Rejected",
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("93ea74c1-1ec6-ffa1-717a-50cd2e3ccef1"),
                            Album = "Rustic Steel Table",
                            AudioUrl = "http://ardith.com/toys-toys--home/home-loan-accoun",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            CoverUrl = "http://grant.name/generic/mountains/administrator",
                            Duration = new TimeSpan(0, 0, 2, 38, 0),
                            Status = "Approved",
                            Title = "Use the bluetooth"
                        },
                        new
                        {
                            Id = new Guid("4d6356d5-b961-d6a4-6a7f-72b157003151"),
                            Album = "Awesome Metal Towels",
                            AudioUrl = "http://deven.info/credit-card-account/engage/revol",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "http://consuelo.org/fresh/functionality",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Status = "Approved",
                            Title = "synthesizing the array"
                        },
                        new
                        {
                            Id = new Guid("465b6b27-86c7-677c-6e41-d314447f6aea"),
                            Album = "Tasty Frozen Chair",
                            AudioUrl = "https://cassie.name/experiences/macao/deposit",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            CoverUrl = "http://margie.com/synthesize/sports",
                            Duration = new TimeSpan(0, 0, 2, 41, 0),
                            Status = "Approved",
                            Title = "You can't synthesize"
                        },
                        new
                        {
                            Id = new Guid("e22a1e63-225b-2c57-5d0f-f30e57707a44"),
                            Album = "Rustic Metal Cheese",
                            AudioUrl = "http://schuyler.biz/checking-account/navigate",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            CoverUrl = "https://myron.info/ib/transmitting/unbranded",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Status = "Rejected",
                            Title = "I'll input the"
                        },
                        new
                        {
                            Id = new Guid("022f284d-5a3c-9a21-099f-969d11025cb4"),
                            Album = "Refined Steel Pizza",
                            AudioUrl = "http://stephany.info/trace",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            CoverUrl = "http://helen.biz/hungary",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("13f19850-5b4e-dc97-819d-3cabbceaf6f1"),
                            Album = "Fantastic Soft Chicken",
                            AudioUrl = "http://elise.info/locks",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            CoverUrl = "http://ruby.net/awesome/western-sahara",
                            Duration = new TimeSpan(0, 0, 3, 2, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("ba807973-37f9-1a08-34da-036c6c2415a6"),
                            Album = "Awesome Metal Salad",
                            AudioUrl = "http://ansel.com/jordanian-dinar/fantastic-frozen-",
                            AuthorId = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            CoverUrl = "http://llewellyn.com/alarm/incredible",
                            Duration = new TimeSpan(0, 0, 2, 55, 0),
                            Status = "Approved",
                            Title = "The SSL array"
                        },
                        new
                        {
                            Id = new Guid("c42c0a0b-dad0-1e10-67af-1cf953b57d54"),
                            Album = "Gorgeous Plastic Computer",
                            AudioUrl = "http://aryanna.net/systematic",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            CoverUrl = "https://gladyce.com/buckinghamshire/licensed-metal",
                            Duration = new TimeSpan(0, 0, 3, 5, 0),
                            Status = "Pending",
                            Title = "Use the bluetooth"
                        },
                        new
                        {
                            Id = new Guid("b5c6322b-1449-75de-cb84-9e21e9765574"),
                            Album = "Handmade Frozen Shoes",
                            AudioUrl = "http://shany.com/savings-account",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            CoverUrl = "http://duane.org/senegal/payment",
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Status = "Rejected",
                            Title = "If we back"
                        },
                        new
                        {
                            Id = new Guid("6610b3c3-78d8-4121-9e1e-94c5ab66b4f8"),
                            Album = "Licensed Plastic Towels",
                            AudioUrl = "https://jammie.org/e-services/money-market-account",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            CoverUrl = "http://johnnie.com/granite",
                            Duration = new TimeSpan(0, 0, 3, 19, 0),
                            Status = "Approved",
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("58cfeb2d-c95e-dd9f-dc46-974971c33ad5"),
                            Album = "Rustic Granite Shirt",
                            AudioUrl = "https://erick.com/calculate",
                            AuthorId = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            CoverUrl = "http://fredrick.name/steel",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Status = "Approved",
                            Title = "synthesizing the array"
                        },
                        new
                        {
                            Id = new Guid("5900c162-c7b7-3d55-8fe7-03fedbd0a46c"),
                            Album = "Ergonomic Frozen Chair",
                            AudioUrl = "http://amely.info/regional/solutions/pink",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            CoverUrl = "https://florence.name/bahamas/turquoise/lodge",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Status = "Rejected",
                            Title = "Use the wireless"
                        },
                        new
                        {
                            Id = new Guid("e2206501-0507-ad19-1fa6-92a25a894be4"),
                            Album = "Handmade Steel Pizza",
                            AudioUrl = "http://destinee.name/borders/3rd-generation",
                            AuthorId = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            CoverUrl = "https://catherine.name/metal",
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Status = "Approved",
                            Title = "Try to quantify"
                        },
                        new
                        {
                            Id = new Guid("eb9119c1-0591-76db-d533-fb7ff83db8d7"),
                            Album = "Rustic Cotton Car",
                            AudioUrl = "http://urban.info/white/shoes/navigate",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "http://golden.org/json/zero-administration/unbrand",
                            Duration = new TimeSpan(0, 0, 2, 39, 0),
                            Status = "Pending",
                            Title = "You can't input"
                        },
                        new
                        {
                            Id = new Guid("595fa0b3-bcbf-4df1-45b8-98461c1dde97"),
                            Album = "Practical Steel Computer",
                            AudioUrl = "http://nikki.biz/leverage",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            CoverUrl = "http://wilfred.com/cliffs/borders/models",
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("c6459f8d-0f9b-fc61-7450-ae93ca342545"),
                            Album = "Handmade Wooden Bacon",
                            AudioUrl = "https://edmund.biz/fantastic-wooden-bike/collabora",
                            AuthorId = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            CoverUrl = "http://donavon.info/berkshire",
                            Duration = new TimeSpan(0, 0, 2, 44, 0),
                            Status = "Rejected",
                            Title = "I'll navigate the"
                        },
                        new
                        {
                            Id = new Guid("088c113c-8693-77fa-1d2e-e1848b144d13"),
                            Album = "Fantastic Frozen Mouse",
                            AudioUrl = "http://mireya.name/home-loan-account/artificial-in",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            CoverUrl = "http://cassidy.biz/logistical/mountain",
                            Duration = new TimeSpan(0, 0, 2, 51, 0),
                            Status = "Approved",
                            Title = "You can't synthesize"
                        },
                        new
                        {
                            Id = new Guid("1f08199d-a85b-6e60-7053-bd6c2b417202"),
                            Album = "Generic Cotton Chicken",
                            AudioUrl = "http://ned.net/yuan-renminbi/payment/ergonomic-fro",
                            AuthorId = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            CoverUrl = "http://leilani.biz/sticky/saudi-arabia",
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Status = "Pending",
                            Title = "Use the 1080p"
                        },
                        new
                        {
                            Id = new Guid("5b299bde-b51a-ebf6-81ae-007690fbda39"),
                            Album = "Awesome Wooden Keyboard",
                            AudioUrl = "http://mollie.name/generic/djibouti-franc/investor",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "http://easter.biz/withdrawal",
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Status = "Pending",
                            Title = "You can't program"
                        },
                        new
                        {
                            Id = new Guid("b6a4d1f1-855b-265b-2974-26e820a54cb5"),
                            Album = "Refined Rubber Gloves",
                            AudioUrl = "http://robin.com/maine/malaysian-ringgit/reverse-e",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "https://tate.info/frozen",
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Status = "Rejected",
                            Title = "If we index"
                        },
                        new
                        {
                            Id = new Guid("66d79c37-a06d-cafb-c877-118805714079"),
                            Album = "Ergonomic Granite Keyboard",
                            AudioUrl = "http://juliet.info/home-loan-account",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            CoverUrl = "https://prudence.org/viral/neural/small-granite-co",
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Status = "Rejected",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("7d614f37-cc13-498f-18e4-ae58535eac40"),
                            Album = "Licensed Frozen Shirt",
                            AudioUrl = "http://margarett.biz/regional",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            CoverUrl = "https://makayla.org/crossroad",
                            Duration = new TimeSpan(0, 0, 2, 57, 0),
                            Status = "Pending",
                            Title = "Use the primary"
                        },
                        new
                        {
                            Id = new Guid("167db078-b22a-b972-aac9-6fcdeb867bc8"),
                            Album = "Practical Steel Bacon",
                            AudioUrl = "https://orrin.com/investment-account/virtual/olive",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "https://sophia.biz/dedicated/hack",
                            Duration = new TimeSpan(0, 0, 3, 5, 0),
                            Status = "Approved",
                            Title = "You can't index"
                        },
                        new
                        {
                            Id = new Guid("0e8d697f-5ecd-f720-05c3-81f37be64927"),
                            Album = "Refined Frozen Soap",
                            AudioUrl = "https://devin.info/bedfordshire/deposit",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "http://kelly.info/customer/concrete",
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Status = "Rejected",
                            Title = "I'll generate the"
                        },
                        new
                        {
                            Id = new Guid("55e4fe5c-f973-8cd1-6ea0-741673ef3854"),
                            Album = "Incredible Plastic Table",
                            AudioUrl = "http://alice.info/jbod/wisconsin/streets",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            CoverUrl = "https://samantha.info/calculate",
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Status = "Rejected",
                            Title = "If we input"
                        },
                        new
                        {
                            Id = new Guid("cc8cadaa-e43f-ffe9-3681-8fb974863329"),
                            Album = "Unbranded Fresh Chair",
                            AudioUrl = "https://dakota.com/global/customized",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            CoverUrl = "https://selmer.info/intuitive/handmade/ways",
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Status = "Approved",
                            Title = "Use the solid"
                        },
                        new
                        {
                            Id = new Guid("b3340d63-20d7-59d5-d86f-81411edf23b1"),
                            Album = "Handcrafted Cotton Chicken",
                            AudioUrl = "http://vaughn.name/synergized",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            CoverUrl = "http://virgil.name/credit-card-account/jewelery-ba",
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Status = "Rejected",
                            Title = "I'll back up"
                        },
                        new
                        {
                            Id = new Guid("619b7f7c-a3be-acfe-4e02-ae397647e685"),
                            Album = "Gorgeous Frozen Shirt",
                            AudioUrl = "https://meredith.net/nebraska",
                            AuthorId = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            CoverUrl = "https://sally.net/thx",
                            Duration = new TimeSpan(0, 0, 3, 29, 0),
                            Status = "Rejected",
                            Title = "navigating the protocol"
                        },
                        new
                        {
                            Id = new Guid("23631539-7a4e-f78c-731e-37254e0c34ed"),
                            Album = "Generic Steel Hat",
                            AudioUrl = "https://meagan.biz/technician/tasty-soft-pizza/evo",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "http://dortha.com/bypass/square",
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Status = "Rejected",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("46ea0196-d84b-e5c7-82ef-ce6dd0e09efd"),
                            Album = "Ergonomic Cotton Keyboard",
                            AudioUrl = "http://cecelia.name/specialist",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            CoverUrl = "https://enoch.org/copy/hacking/meadow",
                            Duration = new TimeSpan(0, 0, 3, 24, 0),
                            Status = "Rejected",
                            Title = "transmitting the monitor"
                        },
                        new
                        {
                            Id = new Guid("42252606-3838-6661-2f2c-740a403a2251"),
                            Album = "Handcrafted Soft Tuna",
                            AudioUrl = "http://lafayette.biz/maryland/unbranded",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "https://dee.net/withdrawal/gorgeous-wooden-pizza",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Status = "Pending",
                            Title = "You can't program"
                        },
                        new
                        {
                            Id = new Guid("5d1c5115-6b08-3e51-1e03-1a7c77f0c507"),
                            Album = "Handcrafted Cotton Pizza",
                            AudioUrl = "https://rogelio.net/auxiliary/exe/synthesizing",
                            AuthorId = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            CoverUrl = "https://alf.name/harbors/withdrawal",
                            Duration = new TimeSpan(0, 0, 2, 35, 0),
                            Status = "Rejected",
                            Title = "The SMS matrix"
                        },
                        new
                        {
                            Id = new Guid("2f20d533-d392-3326-6359-c0f6e0c76970"),
                            Album = "Licensed Wooden Salad",
                            AudioUrl = "http://irma.org/function/fantastic-concrete-fish/i",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "http://cordell.com/vista",
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Status = "Approved",
                            Title = "You can't input"
                        },
                        new
                        {
                            Id = new Guid("3348964e-f999-a007-d47b-177c65e966cb"),
                            Album = "Generic Rubber Hat",
                            AudioUrl = "http://stacey.net/accounts",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            CoverUrl = "http://carlos.com/tasty-rubber-computer/fault-tole",
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Status = "Pending",
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("e52b371c-7969-8bd6-9292-dc0a828fadfc"),
                            Album = "Practical Soft Mouse",
                            AudioUrl = "https://chaya.biz/system/high-level/portals",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            CoverUrl = "https://marcella.com/scale/liaison",
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Status = "Approved",
                            Title = "You can't input"
                        },
                        new
                        {
                            Id = new Guid("e6b05823-3d92-e472-0a39-a79b2db67e32"),
                            Album = "Handmade Soft Pants",
                            AudioUrl = "https://ardella.com/plain",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            CoverUrl = "http://miracle.info/buckinghamshire/grocery--healt",
                            Duration = new TimeSpan(0, 0, 3, 19, 0),
                            Status = "Pending",
                            Title = "If we index"
                        },
                        new
                        {
                            Id = new Guid("a17d436d-dc63-701c-a144-250db718c92d"),
                            Album = "Rustic Metal Tuna",
                            AudioUrl = "http://martina.info/buckinghamshire/models",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            CoverUrl = "https://laurence.biz/application/sky-blue/circles",
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Status = "Pending",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("5241daea-7eae-d980-6c8d-3fff7a859c8d"),
                            Album = "Fantastic Wooden Computer",
                            AudioUrl = "http://jalon.net/mobility/avon/incentivize",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            CoverUrl = "http://elton.info/sms",
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Status = "Pending",
                            Title = "bypassing the alarm"
                        },
                        new
                        {
                            Id = new Guid("53a0e799-d7a7-7a11-0e03-2921ee510b47"),
                            Album = "Handmade Steel Chicken",
                            AudioUrl = "http://laverna.org/redundant",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "https://kade.name/intelligent-frozen-cheese/gorgeo",
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Status = "Rejected",
                            Title = "If we navigate"
                        },
                        new
                        {
                            Id = new Guid("fc76d17a-00a1-1c5e-24db-ca0bdacac16f"),
                            Album = "Handmade Cotton Salad",
                            AudioUrl = "https://javonte.info/invoice/summit/plastic",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "http://michaela.org/way/universal/integrate",
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Status = "Pending",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("65b36746-5527-ce55-f7d6-01f57e43f2b8"),
                            Album = "Sleek Soft Chips",
                            AudioUrl = "http://paolo.name/virtual",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            CoverUrl = "http://jaylin.info/accounts",
                            Duration = new TimeSpan(0, 0, 2, 39, 0),
                            Status = "Rejected",
                            Title = "Try to navigate"
                        },
                        new
                        {
                            Id = new Guid("e9c98cc7-2c43-1fe3-5aa0-844c2cc88d46"),
                            Album = "Gorgeous Fresh Bike",
                            AudioUrl = "http://rhett.name/avon/refined-fresh-soap",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            CoverUrl = "https://emanuel.biz/automotive--industrial/front-l",
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Status = "Approved",
                            Title = "Try to synthesize"
                        },
                        new
                        {
                            Id = new Guid("56098df8-fb53-be2b-1141-30f15deaaf2a"),
                            Album = "Handcrafted Soft Tuna",
                            AudioUrl = "http://elisabeth.biz/kids--garden/uganda-shilling/",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "https://adolph.biz/solomon-islands-dollar/cyan",
                            Duration = new TimeSpan(0, 0, 2, 51, 0),
                            Status = "Pending",
                            Title = "If we program"
                        },
                        new
                        {
                            Id = new Guid("c014c71b-e04c-4d8a-7d16-05175b8aa849"),
                            Album = "Sleek Rubber Tuna",
                            AudioUrl = "https://jimmy.com/cambridgeshire",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            CoverUrl = "http://troy.info/licensed",
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Status = "Pending",
                            Title = "If we input"
                        },
                        new
                        {
                            Id = new Guid("1063b3e8-eea5-d272-8e87-504cfab6fd4d"),
                            Album = "Practical Granite Sausages",
                            AudioUrl = "http://rick.info/handcrafted/bypassing/supervisor",
                            AuthorId = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            CoverUrl = "http://maximo.org/prairie",
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Status = "Pending",
                            Title = "If we hack"
                        },
                        new
                        {
                            Id = new Guid("e43911ca-37bb-948a-4105-54fa3f0057d4"),
                            Album = "Handmade Granite Tuna",
                            AudioUrl = "http://bethel.org/incredible/hub",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            CoverUrl = "http://troy.org/dynamic/avon/glens",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Status = "Approved",
                            Title = "Try to copy"
                        },
                        new
                        {
                            Id = new Guid("7b9c69f6-74c5-d8a6-6143-707330f453ba"),
                            Album = "Incredible Wooden Pants",
                            AudioUrl = "https://lawson.net/small",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            CoverUrl = "http://ashlee.com/emulation/impactful/wells",
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Status = "Pending",
                            Title = "calculating the feed"
                        },
                        new
                        {
                            Id = new Guid("f2662437-137a-a83d-f1b4-eed702ed3ee9"),
                            Album = "Intelligent Plastic Mouse",
                            AudioUrl = "http://jayda.biz/producer/florida",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "http://xzavier.info/oval/loop",
                            Duration = new TimeSpan(0, 0, 2, 30, 0),
                            Status = "Approved",
                            Title = "You can't synthesize"
                        },
                        new
                        {
                            Id = new Guid("4778f9be-b316-d851-974d-12c194e3cfa1"),
                            Album = "Rustic Fresh Cheese",
                            AudioUrl = "https://marlee.name/terrace/assurance",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            CoverUrl = "https://stefanie.net/interactions",
                            Duration = new TimeSpan(0, 0, 2, 47, 0),
                            Status = "Rejected",
                            Title = "generating the sensor"
                        },
                        new
                        {
                            Id = new Guid("b5fe127a-9183-e227-c5e3-eeef27e28287"),
                            Album = "Unbranded Steel Bike",
                            AudioUrl = "http://martina.net/css",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "http://ali.com/sensor",
                            Duration = new TimeSpan(0, 0, 3, 14, 0),
                            Status = "Rejected",
                            Title = "Try to quantify"
                        },
                        new
                        {
                            Id = new Guid("db57426d-7dfc-e236-a7d9-6d674eca1e00"),
                            Album = "Gorgeous Soft Mouse",
                            AudioUrl = "http://alycia.org/invoice/rustic-granite-table/fro",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "http://connie.info/handcrafted",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Status = "Pending",
                            Title = "You can't compress"
                        },
                        new
                        {
                            Id = new Guid("6117c78d-1be1-555f-71ec-9fe16fe92044"),
                            Album = "Gorgeous Fresh Ball",
                            AudioUrl = "http://kailee.net/benchmark",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            CoverUrl = "http://henri.net/monitor",
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Status = "Approved",
                            Title = "generating the hard"
                        },
                        new
                        {
                            Id = new Guid("61e8f7b1-40d2-4044-b7ba-d9752184f499"),
                            Album = "Handcrafted Concrete Salad",
                            AudioUrl = "http://bethel.biz/json",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            CoverUrl = "https://unique.name/metal/dot-com",
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Status = "Approved",
                            Title = "The COM capacitor"
                        },
                        new
                        {
                            Id = new Guid("0d5d93d1-101a-ec67-496f-9c2b0bd9efad"),
                            Album = "Handcrafted Steel Chips",
                            AudioUrl = "http://chris.info/optimize/white/local",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "https://jazmyn.org/reboot/trail/reboot",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Status = "Rejected",
                            Title = "If we index"
                        },
                        new
                        {
                            Id = new Guid("6a225c33-5aaa-a58f-42c7-e5c437955d17"),
                            Album = "Awesome Metal Hat",
                            AudioUrl = "http://jade.org/corporate/granite",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            CoverUrl = "https://yvonne.org/fresh",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Status = "Rejected",
                            Title = "If we quantify"
                        },
                        new
                        {
                            Id = new Guid("84761631-1502-2b18-1dee-7bb4ffb78d86"),
                            Album = "Refined Cotton Table",
                            AudioUrl = "https://dejon.info/paradigm/open-source",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            CoverUrl = "http://dayana.info/tunnel/tennessee/concept",
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Status = "Rejected",
                            Title = "You can't reboot"
                        },
                        new
                        {
                            Id = new Guid("88a4e608-48e1-4956-a344-3b9755d21ded"),
                            Album = "Awesome Wooden Pizza",
                            AudioUrl = "https://kale.net/monitor/initiatives",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "http://alan.org/gorgeous-fresh-pants",
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Status = "Pending",
                            Title = "The USB system"
                        },
                        new
                        {
                            Id = new Guid("e44b8d7d-6053-d09a-9089-c57b79d0263d"),
                            Album = "Incredible Metal Cheese",
                            AudioUrl = "https://betty.name/green/canyon",
                            AuthorId = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            CoverUrl = "http://angel.biz/director",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Status = "Approved",
                            Title = "I'll reboot the"
                        },
                        new
                        {
                            Id = new Guid("ad87cb4c-b697-9659-282f-e029761f4b43"),
                            Album = "Incredible Rubber Chair",
                            AudioUrl = "http://jorge.net/integration/digital",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "http://elise.biz/capacity/e-enable/branding",
                            Duration = new TimeSpan(0, 0, 2, 47, 0),
                            Status = "Pending",
                            Title = "hacking the driver"
                        },
                        new
                        {
                            Id = new Guid("148937f1-c71a-6c7f-a7f2-1e90f1863c07"),
                            Album = "Awesome Plastic Shirt",
                            AudioUrl = "https://emmie.net/licensed",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "http://christelle.name/maximized/auto-loan-account",
                            Duration = new TimeSpan(0, 0, 2, 32, 0),
                            Status = "Pending",
                            Title = "I'll input the"
                        },
                        new
                        {
                            Id = new Guid("ee0af058-4172-9e4b-6201-aa262ab552db"),
                            Album = "Tasty Soft Ball",
                            AudioUrl = "http://kendra.com/avon",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            CoverUrl = "http://susan.info/quality/rustic/senior",
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Status = "Pending",
                            Title = "If we connect"
                        },
                        new
                        {
                            Id = new Guid("1318f97c-c47e-402a-149d-783b6a408879"),
                            Album = "Intelligent Granite Pants",
                            AudioUrl = "https://lesley.com/bandwidth/rubber",
                            AuthorId = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            CoverUrl = "https://myrl.name/idaho/granite",
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Status = "Pending",
                            Title = "You can't compress"
                        },
                        new
                        {
                            Id = new Guid("f3674074-5e5a-886b-dd65-7ce998dbdafd"),
                            Album = "Practical Fresh Table",
                            AudioUrl = "https://quentin.name/cultivate/open-source",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "https://damon.net/distributed",
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Status = "Rejected",
                            Title = "If we compress"
                        },
                        new
                        {
                            Id = new Guid("64011a1c-05d4-6451-efe8-513efff6857a"),
                            Album = "Awesome Plastic Pants",
                            AudioUrl = "http://marcellus.biz/interface",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            CoverUrl = "https://evalyn.info/schemas/cedi/cotton",
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("d2374f04-9e73-78b2-384f-6b03ecda0971"),
                            Album = "Rustic Cotton Cheese",
                            AudioUrl = "https://danielle.com/gorgeous-concrete-pizza/cotto",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "https://haylie.com/hard-drive",
                            Duration = new TimeSpan(0, 0, 3, 17, 0),
                            Status = "Approved",
                            Title = "The JBOD protocol"
                        },
                        new
                        {
                            Id = new Guid("11b45ed3-d583-15a1-244e-c799f1763d8f"),
                            Album = "Sleek Plastic Pants",
                            AudioUrl = "http://winfield.info/monitor/drive",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            CoverUrl = "http://karli.org/override",
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Status = "Approved",
                            Title = "calculating the card"
                        },
                        new
                        {
                            Id = new Guid("8716f5b5-b41a-df02-3578-66a550419ea6"),
                            Album = "Incredible Frozen Salad",
                            AudioUrl = "http://kaleb.name/sleek-soft-mouse",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            CoverUrl = "https://philip.org/new-mexico/frozen",
                            Duration = new TimeSpan(0, 0, 3, 8, 0),
                            Status = "Pending",
                            Title = "The EXE application"
                        },
                        new
                        {
                            Id = new Guid("ab7c1839-8897-6c26-93a0-e6cc79efabf5"),
                            Album = "Sleek Cotton Pants",
                            AudioUrl = "https://buddy.name/cape/re-contextualized/bedfords",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            CoverUrl = "https://eudora.com/palladium/bypassing",
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Status = "Pending",
                            Title = "I'll transmit the"
                        },
                        new
                        {
                            Id = new Guid("ed850750-b467-60a3-2a31-ea7144c2d9ff"),
                            Album = "Awesome Wooden Towels",
                            AudioUrl = "http://johanna.com/portugal/backing-up/algorithm",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "https://wava.biz/points",
                            Duration = new TimeSpan(0, 0, 3, 17, 0),
                            Status = "Pending",
                            Title = "The AGP monitor"
                        },
                        new
                        {
                            Id = new Guid("ad9936d9-6bfe-3313-766b-27fa059da01a"),
                            Album = "Unbranded Cotton Pants",
                            AudioUrl = "https://zakary.org/automotive/automotive/extensibl",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "https://ursula.com/dynamic/wisconsin",
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Status = "Rejected",
                            Title = "parsing the program"
                        },
                        new
                        {
                            Id = new Guid("51617a13-1e5a-44c6-6eac-6fcb0cfc319f"),
                            Album = "Ergonomic Concrete Shirt",
                            AudioUrl = "http://ernie.info/bleeding-edge",
                            AuthorId = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            CoverUrl = "http://madelyn.com/portals/executive/intelligent-g",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Status = "Approved",
                            Title = "Try to parse"
                        },
                        new
                        {
                            Id = new Guid("40d741bf-6c7a-e3ed-748a-1217fdfd82d9"),
                            Album = "Fantastic Cotton Cheese",
                            AudioUrl = "https://edyth.name/representative/generating/effic",
                            AuthorId = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            CoverUrl = "http://ulices.biz/usb",
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Status = "Pending",
                            Title = "Try to bypass"
                        },
                        new
                        {
                            Id = new Guid("0b585d74-a7bb-c43b-17b1-a10f472c160b"),
                            Album = "Licensed Granite Bike",
                            AudioUrl = "https://ignatius.info/handcrafted-concrete-keyboar",
                            AuthorId = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            CoverUrl = "https://raymundo.com/global/iterate/cyan",
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Status = "Rejected",
                            Title = "Try to calculate"
                        },
                        new
                        {
                            Id = new Guid("3705369e-c4cd-d022-ab94-e320ee79b812"),
                            Album = "Intelligent Soft Fish",
                            AudioUrl = "https://van.net/tasty-soft-sausages/haptic",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            CoverUrl = "http://rick.biz/interactive/views/guyana-dollar",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("4d46c271-12f1-9b0d-4af3-0f3e5e101ed8"),
                            Album = "Gorgeous Rubber Tuna",
                            AudioUrl = "https://krystel.org/jersey/avon",
                            AuthorId = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            CoverUrl = "http://ima.info/delaware",
                            Duration = new TimeSpan(0, 0, 2, 57, 0),
                            Status = "Pending",
                            Title = "compressing the monitor"
                        },
                        new
                        {
                            Id = new Guid("75809677-9813-2a27-8cab-0412577b3a90"),
                            Album = "Ergonomic Concrete Shirt",
                            AudioUrl = "https://kip.biz/purple/cambridgeshire/morph",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            CoverUrl = "https://deonte.net/alarm/plaza/networks",
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Status = "Pending",
                            Title = "hacking the transmitter"
                        },
                        new
                        {
                            Id = new Guid("7e8afab5-6838-09c8-0230-974927f9ddd0"),
                            Album = "Refined Granite Chair",
                            AudioUrl = "http://hilton.net/withdrawal/bypassing/buckinghams",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            CoverUrl = "http://earlene.biz/summit/district/virtual",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Status = "Approved",
                            Title = "I'll calculate the"
                        },
                        new
                        {
                            Id = new Guid("6f267ef7-fb91-6c26-9fed-85d09301ea22"),
                            Album = "Gorgeous Wooden Shirt",
                            AudioUrl = "http://easton.org/books",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "http://bryon.info/soft/solutions/solution-oriented",
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Status = "Approved",
                            Title = "Try to transmit"
                        },
                        new
                        {
                            Id = new Guid("8a4b59b0-69cc-6bfc-070e-6ddf37a5c205"),
                            Album = "Sleek Concrete Pizza",
                            AudioUrl = "https://lynn.biz/east-caribbean-dollar/infrastruct",
                            AuthorId = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            CoverUrl = "https://elta.com/web-enabled/anguilla/deposit",
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Status = "Pending",
                            Title = "Use the neural"
                        },
                        new
                        {
                            Id = new Guid("8b3a8081-f889-ef69-6468-0b1a3f63f3ef"),
                            Album = "Generic Granite Car",
                            AudioUrl = "https://tyreek.net/philippine-peso",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            CoverUrl = "https://lauriane.org/garden/consultant/bypassing",
                            Duration = new TimeSpan(0, 0, 2, 41, 0),
                            Status = "Pending",
                            Title = "The THX firewall"
                        },
                        new
                        {
                            Id = new Guid("f829be8f-25ac-9d2b-cb3b-20f4ec2fea70"),
                            Album = "Handmade Concrete Sausages",
                            AudioUrl = "http://randal.net/deploy/principal/buckinghamshire",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            CoverUrl = "http://rosanna.com/compress",
                            Duration = new TimeSpan(0, 0, 2, 55, 0),
                            Status = "Approved",
                            Title = "Try to connect"
                        },
                        new
                        {
                            Id = new Guid("72e500c7-0b3e-3660-5e12-76430aaef98e"),
                            Album = "Tasty Concrete Table",
                            AudioUrl = "https://karson.biz/georgia/orchid/investment-accou",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            CoverUrl = "http://zula.com/garden-beauty--jewelery",
                            Duration = new TimeSpan(0, 0, 2, 39, 0),
                            Status = "Approved",
                            Title = "You can't override"
                        },
                        new
                        {
                            Id = new Guid("a27e6baf-f99d-2b63-97e5-dc0f34f8b90d"),
                            Album = "Licensed Rubber Keyboard",
                            AudioUrl = "https://beryl.biz/deposit/practical/designer",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            CoverUrl = "https://micaela.info/tan/invoice/cross-platform",
                            Duration = new TimeSpan(0, 0, 2, 57, 0),
                            Status = "Rejected",
                            Title = "hacking the hard"
                        },
                        new
                        {
                            Id = new Guid("b71bd510-8c6f-b431-7029-458a8a8cebf8"),
                            Album = "Ergonomic Rubber Bike",
                            AudioUrl = "https://vergie.biz/engineer/cambridgeshire/gorgeou",
                            AuthorId = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            CoverUrl = "https://eli.org/investment-account",
                            Duration = new TimeSpan(0, 0, 3, 10, 0),
                            Status = "Rejected",
                            Title = "I'll generate the"
                        },
                        new
                        {
                            Id = new Guid("58f4d901-224e-1c87-e5b8-839472ec0cf1"),
                            Album = "Refined Cotton Salad",
                            AudioUrl = "http://hazel.org/personal-loan-account/bedfordshir",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "https://rosanna.com/program",
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("3a8e96f9-3bd7-3dd8-50fd-a9c192cfad91"),
                            Album = "Handmade Concrete Towels",
                            AudioUrl = "https://reta.com/computers--kids",
                            AuthorId = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            CoverUrl = "http://raphaelle.info/swiss-franc/fuchsia/gorgeous",
                            Duration = new TimeSpan(0, 0, 2, 43, 0),
                            Status = "Pending",
                            Title = "Try to reboot"
                        },
                        new
                        {
                            Id = new Guid("60d4c70e-37e7-694d-d953-d12191be06fd"),
                            Album = "Fantastic Metal Chicken",
                            AudioUrl = "https://eulalia.info/parsing/paradigms",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "http://brando.info/iterate/tonga",
                            Duration = new TimeSpan(0, 0, 3, 24, 0),
                            Status = "Rejected",
                            Title = "I'll reboot the"
                        },
                        new
                        {
                            Id = new Guid("4f30f008-936c-0edb-662e-04409ea576ef"),
                            Album = "Awesome Metal Keyboard",
                            AudioUrl = "http://idella.name/handcrafted/soft/orchestrator",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            CoverUrl = "https://nikko.info/project/tanzania",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("b8d0d8cf-6880-b9b1-d3d6-58fb9cd313cc"),
                            Album = "Fantastic Cotton Bacon",
                            AudioUrl = "https://lessie.com/identity/uic-franc",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            CoverUrl = "https://annette.info/reduced/direct/sdd",
                            Duration = new TimeSpan(0, 0, 3, 3, 0),
                            Status = "Rejected",
                            Title = "Use the haptic"
                        },
                        new
                        {
                            Id = new Guid("e55730a3-0c67-81e5-5146-5953901790b1"),
                            Album = "Rustic Soft Bacon",
                            AudioUrl = "https://della.com/future-proofed/maine/hardware",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            CoverUrl = "http://mayra.net/group/incredible-wooden-chair/vir",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Status = "Approved",
                            Title = "Use the redundant"
                        },
                        new
                        {
                            Id = new Guid("8670a9ee-efab-ea25-5684-97bf26e6fe29"),
                            Album = "Tasty Granite Sausages",
                            AudioUrl = "https://samanta.net/cambridgeshire/personal-loan-a",
                            AuthorId = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            CoverUrl = "http://demarco.net/borders",
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Status = "Pending",
                            Title = "If we connect"
                        },
                        new
                        {
                            Id = new Guid("2483b133-f373-d74e-c183-e57bc4e5d39c"),
                            Album = "Intelligent Frozen Gloves",
                            AudioUrl = "http://lorna.com/texas/flats",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            CoverUrl = "http://okey.net/wooden",
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Status = "Approved",
                            Title = "If we program"
                        },
                        new
                        {
                            Id = new Guid("43baf9ce-cb90-e502-f1ac-858f3e9c4725"),
                            Album = "Small Rubber Chicken",
                            AudioUrl = "http://justina.biz/accountability/greens",
                            AuthorId = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            CoverUrl = "http://santos.biz/tools--music/rustic-plastic-pizz",
                            Duration = new TimeSpan(0, 0, 3, 27, 0),
                            Status = "Pending",
                            Title = "Try to override"
                        },
                        new
                        {
                            Id = new Guid("581db257-4981-f568-789a-4d1f2b834f73"),
                            Album = "Gorgeous Soft Car",
                            AudioUrl = "https://fatima.org/congolese-franc/arkansas",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "http://gregg.info/channels",
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Status = "Approved",
                            Title = "compressing the interface"
                        },
                        new
                        {
                            Id = new Guid("3a33e040-6b33-76c2-224b-5fac1d9f5a2e"),
                            Album = "Unbranded Concrete Shirt",
                            AudioUrl = "http://arvid.com/mountains/optical/electronics--he",
                            AuthorId = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            CoverUrl = "http://raheem.org/incredible/feed",
                            Duration = new TimeSpan(0, 0, 3, 27, 0),
                            Status = "Rejected",
                            Title = "If we calculate"
                        },
                        new
                        {
                            Id = new Guid("86347e32-1e93-2457-8b9d-ada993ffafbe"),
                            Album = "Handmade Metal Bike",
                            AudioUrl = "https://callie.net/awesome-frozen-bike",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            CoverUrl = "http://janice.biz/savings-account",
                            Duration = new TimeSpan(0, 0, 3, 2, 0),
                            Status = "Rejected",
                            Title = "I'll reboot the"
                        },
                        new
                        {
                            Id = new Guid("3b341fed-0782-7b8b-961c-0d8be4500dd9"),
                            Album = "Sleek Plastic Shirt",
                            AudioUrl = "http://kelly.net/synergized/virtual/texas",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            CoverUrl = "https://erika.org/capacity",
                            Duration = new TimeSpan(0, 0, 2, 33, 0),
                            Status = "Rejected",
                            Title = "The SCSI bandwidth"
                        },
                        new
                        {
                            Id = new Guid("3fe77a9a-553a-af5d-317f-10bdc02e98ba"),
                            Album = "Generic Rubber Car",
                            AudioUrl = "http://rhea.net/road/programmable/antarctica-the-t",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            CoverUrl = "https://ibrahim.net/e-tailers/san-marino",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Status = "Rejected",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("74aff791-59fa-2e7a-afad-17d8e37fa2a1"),
                            Album = "Licensed Fresh Chips",
                            AudioUrl = "http://lamont.info/generic-fresh-mouse",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            CoverUrl = "http://valentina.org/human-resource",
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Status = "Pending",
                            Title = "The XSS interface"
                        });
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Age = 19,
                            EmailAddress = "Sabina.Marvin26@gmail.com",
                            ExternalId = "auth0|d8b0d2646f930a379fe684d8",
                            Gender = "Female",
                            Name = "Marianne"
                        },
                        new
                        {
                            Id = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Age = 99,
                            EmailAddress = "Jeanette.Bartoletti@hotmail.com",
                            ExternalId = "auth0|d8d5248b2594d52b85cd5352",
                            Gender = "Female",
                            Name = "Joanie"
                        },
                        new
                        {
                            Id = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Age = 94,
                            EmailAddress = "Larue46@hotmail.com",
                            ExternalId = "auth0|1b95a2b93ad5c83c5c75374d",
                            Gender = "Male",
                            Name = "Marley"
                        },
                        new
                        {
                            Id = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            Age = 41,
                            EmailAddress = "Kacie.Renner92@hotmail.com",
                            ExternalId = "auth0|e486a6697cad876bc62f970b",
                            Gender = "Female",
                            Name = "Louie"
                        },
                        new
                        {
                            Id = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Age = 44,
                            EmailAddress = "Darron70@yahoo.com",
                            ExternalId = "auth0|c0734263ccfdaafd54b28c4a",
                            Gender = "Female",
                            Name = "Greyson"
                        },
                        new
                        {
                            Id = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            Age = 88,
                            EmailAddress = "Clotilde_Swaniawski@gmail.com",
                            ExternalId = "auth0|52a0838fcdcce32176a06863",
                            Gender = "Male",
                            Name = "Vernice"
                        },
                        new
                        {
                            Id = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            Age = 50,
                            EmailAddress = "Thaddeus_Doyle90@yahoo.com",
                            ExternalId = "auth0|71464b4db7170a63f5f66302",
                            Gender = "Male",
                            Name = "Guadalupe"
                        },
                        new
                        {
                            Id = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            Age = 90,
                            EmailAddress = "Ines_Balistreri@gmail.com",
                            ExternalId = "auth0|7af854402fac00e8a384ef82",
                            Gender = "Female",
                            Name = "Tressa"
                        },
                        new
                        {
                            Id = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            Age = 73,
                            EmailAddress = "Cesar.Kertzmann58@gmail.com",
                            ExternalId = "auth0|409472f82d94d3841f5bacac",
                            Gender = "Female",
                            Name = "Ephraim"
                        },
                        new
                        {
                            Id = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Age = 74,
                            EmailAddress = "Norbert_Schroeder@gmail.com",
                            ExternalId = "auth0|e58f8575cf3f8b24e6571f8d",
                            Gender = "Female",
                            Name = "William"
                        },
                        new
                        {
                            Id = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            Age = 91,
                            EmailAddress = "Delia_Weissnat@gmail.com",
                            ExternalId = "auth0|dc5306dedbf39ac445bfd733",
                            Gender = "Female",
                            Name = "Bridget"
                        },
                        new
                        {
                            Id = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Age = 52,
                            EmailAddress = "Domenick_Steuber@hotmail.com",
                            ExternalId = "auth0|535aae56811c2e6ed5cfb00c",
                            Gender = "Male",
                            Name = "Jada"
                        },
                        new
                        {
                            Id = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            Age = 49,
                            EmailAddress = "Manley_Cronin40@gmail.com",
                            ExternalId = "auth0|8e7649d4282d97b9af274259",
                            Gender = "Male",
                            Name = "Gerhard"
                        },
                        new
                        {
                            Id = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            Age = 38,
                            EmailAddress = "Stephen48@yahoo.com",
                            ExternalId = "auth0|966e3969e00ea631cb22f2a2",
                            Gender = "Male",
                            Name = "Arne"
                        },
                        new
                        {
                            Id = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Age = 43,
                            EmailAddress = "Daniella_Senger@gmail.com",
                            ExternalId = "auth0|ff55cad7b4daa656cc153a24",
                            Gender = "Female",
                            Name = "Shirley"
                        },
                        new
                        {
                            Id = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            Age = 73,
                            EmailAddress = "Sammie.Kilback58@hotmail.com",
                            ExternalId = "auth0|c2300db4d17770e0fd3b514d",
                            Gender = "Male",
                            Name = "Elisa"
                        },
                        new
                        {
                            Id = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            Age = 43,
                            EmailAddress = "Leslie44@yahoo.com",
                            ExternalId = "auth0|bccf82be5b1f4667c6b098af",
                            Gender = "Male",
                            Name = "Marcia"
                        },
                        new
                        {
                            Id = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            Age = 28,
                            EmailAddress = "Miller.Carter@gmail.com",
                            ExternalId = "auth0|0998f7431d4181ce6e9a5bb1",
                            Gender = "Male",
                            Name = "Rhoda"
                        },
                        new
                        {
                            Id = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            Age = 75,
                            EmailAddress = "Elmer76@yahoo.com",
                            ExternalId = "auth0|a41e05f4e8bbb2dfa3a3731a",
                            Gender = "Male",
                            Name = "Lester"
                        },
                        new
                        {
                            Id = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            Age = 65,
                            EmailAddress = "Timmy_Considine@yahoo.com",
                            ExternalId = "auth0|1932dbc737460922d683bbf7",
                            Gender = "Male",
                            Name = "Brennon"
                        },
                        new
                        {
                            Id = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Age = 53,
                            EmailAddress = "Jett.Robel53@gmail.com",
                            ExternalId = "auth0|287a0086ac05cae7e30e4994",
                            Gender = "Male",
                            Name = "Sterling"
                        },
                        new
                        {
                            Id = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Age = 42,
                            EmailAddress = "Halle_Pfannerstill73@gmail.com",
                            ExternalId = "auth0|7aba268e3c08c9249e9ad2f2",
                            Gender = "Male",
                            Name = "Maryam"
                        },
                        new
                        {
                            Id = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            Age = 58,
                            EmailAddress = "Mariano.Braun85@gmail.com",
                            ExternalId = "auth0|7e41734a9fdfdf60a11356ca",
                            Gender = "Male",
                            Name = "Pearline"
                        },
                        new
                        {
                            Id = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            Age = 67,
                            EmailAddress = "Corine.Cormier98@gmail.com",
                            ExternalId = "auth0|26bc1501a4483e815ee97872",
                            Gender = "Female",
                            Name = "Lelah"
                        },
                        new
                        {
                            Id = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            Age = 72,
                            EmailAddress = "Letha_Ratke@gmail.com",
                            ExternalId = "auth0|c1ea939e82e2e265a0c4df9e",
                            Gender = "Male",
                            Name = "Ernie"
                        },
                        new
                        {
                            Id = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            Age = 86,
                            EmailAddress = "Elizabeth_Braun@yahoo.com",
                            ExternalId = "auth0|69fe1fec7f569e507938043b",
                            Gender = "Female",
                            Name = "Brenda"
                        },
                        new
                        {
                            Id = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            Age = 28,
                            EmailAddress = "Amelie.Pollich@gmail.com",
                            ExternalId = "auth0|59183f9253c8ad6726aa967b",
                            Gender = "Female",
                            Name = "Enrique"
                        },
                        new
                        {
                            Id = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            Age = 66,
                            EmailAddress = "Emery.Kunde76@hotmail.com",
                            ExternalId = "auth0|e2f2df7f262fee8312871a9d",
                            Gender = "Female",
                            Name = "Monique"
                        },
                        new
                        {
                            Id = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            Age = 100,
                            EmailAddress = "Earnest67@hotmail.com",
                            ExternalId = "auth0|53d2d94826faf10990721115",
                            Gender = "Female",
                            Name = "Julien"
                        },
                        new
                        {
                            Id = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            Age = 61,
                            EmailAddress = "Lizzie52@hotmail.com",
                            ExternalId = "auth0|9d8a637327a243676fb0a2a2",
                            Gender = "Male",
                            Name = "Zaria"
                        });
                });

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vladify.DataAccess.Entities.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Playlist", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.User", "Owner")
                        .WithMany("Playlists")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.User", "Owner")
                        .WithMany("OwnedSongs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Navigation("OwnedSongs");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
