// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vladify.DataAccess;

#nullable disable

namespace Vladify.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116110958_AddSeedData3")]
    partial class AddSeedData3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            Album = "Awesome Frozen Cheese",
                            Author = "Reese Schmidt",
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "Try to override"
                        },
                        new
                        {
                            Id = new Guid("1423cf1d-35b8-3081-5146-a23609cd05cc"),
                            Album = "Licensed Frozen Chair",
                            Author = "Emily Auer",
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Title = "Use the optical"
                        },
                        new
                        {
                            Id = new Guid("fc8b5187-3cad-b776-e845-d5b265f0f546"),
                            Album = "Fantastic Concrete Chips",
                            Author = "Enrique Zemlak",
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Title = "The RSS driver"
                        },
                        new
                        {
                            Id = new Guid("7afe147d-6bc5-00a8-baa5-88cd564de422"),
                            Album = "Intelligent Rubber Bike",
                            Author = "Julian Ziemann",
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Title = "Try to parse"
                        },
                        new
                        {
                            Id = new Guid("769f8bc3-32ef-d43a-475b-ecf947f58c3e"),
                            Album = "Tasty Granite Keyboard",
                            Author = "Tressa Borer",
                            Duration = new TimeSpan(0, 0, 2, 57, 0),
                            Title = "Use the open-source"
                        },
                        new
                        {
                            Id = new Guid("9e58d7ea-05e5-2f3c-0611-dd231310db7e"),
                            Album = "Small Rubber Gloves",
                            Author = "Jennyfer Corkery",
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Title = "You can't copy"
                        },
                        new
                        {
                            Id = new Guid("a2faba64-c7d2-6fea-024e-1342b85c3854"),
                            Album = "Small Rubber Chicken",
                            Author = "Ronny Krajcik",
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Title = "hacking the system"
                        },
                        new
                        {
                            Id = new Guid("a26b8717-e361-4bca-173b-514b256b7b3c"),
                            Album = "Licensed Frozen Bike",
                            Author = "Wayne Legros",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Title = "Use the haptic"
                        },
                        new
                        {
                            Id = new Guid("610d3f5f-ebd4-7a58-e271-e0d591ec3d36"),
                            Album = "Small Soft Ball",
                            Author = "Bridget Flatley",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "The SCSI circuit"
                        },
                        new
                        {
                            Id = new Guid("ac8d0727-0f19-d7ec-2df0-773a1300593a"),
                            Album = "Gorgeous Plastic Chicken",
                            Author = "Wilmer Shanahan",
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Title = "I'll compress the"
                        },
                        new
                        {
                            Id = new Guid("0327ef30-ab9f-da53-e334-bb82ff65098d"),
                            Album = "Licensed Steel Towels",
                            Author = "Kaylie Haley",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Title = "parsing the transmitter"
                        },
                        new
                        {
                            Id = new Guid("73c05d21-ac80-3ea7-c973-9b67ad7e5660"),
                            Album = "Practical Fresh Ball",
                            Author = "Rupert O'Conner",
                            Duration = new TimeSpan(0, 0, 3, 27, 0),
                            Title = "backing up the"
                        },
                        new
                        {
                            Id = new Guid("18c24e65-552d-86b9-7347-0253becbc4f9"),
                            Album = "Gorgeous Rubber Bacon",
                            Author = "Don Corkery",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Title = "The IB sensor"
                        },
                        new
                        {
                            Id = new Guid("1ddd639a-4b30-7ad8-b182-3a58c5d0ec5e"),
                            Album = "Ergonomic Cotton Gloves",
                            Author = "Nelle Kris",
                            Duration = new TimeSpan(0, 0, 2, 30, 0),
                            Title = "The GB interface"
                        },
                        new
                        {
                            Id = new Guid("7757901a-f177-10ec-69e4-2272f2494771"),
                            Album = "Unbranded Metal Table",
                            Author = "Clara Carroll",
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "Use the multi-byte"
                        });
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Age = 41,
                            EmailAddress = "Megane.Barrows41@yahoo.com",
                            Gender = "Male",
                            Name = "Rocio",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("26ee05f4-43fb-85e9-4dc6-833c087e1147"),
                            Age = 19,
                            EmailAddress = "Kiera26@hotmail.com",
                            Gender = "Female",
                            Name = "Dorcas",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Age = 62,
                            EmailAddress = "Rashawn25@yahoo.com",
                            Gender = "Female",
                            Name = "Reuben",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("9c03f8cc-6c24-8c38-cb73-e6bc0fef1012"),
                            Age = 99,
                            EmailAddress = "Jeanette.Bartoletti@hotmail.com",
                            Gender = "Female",
                            Name = "Joanie",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Age = 75,
                            EmailAddress = "Leonard.Hansen@hotmail.com",
                            Gender = "Female",
                            Name = "Arlene",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("2713c1fd-704a-31a2-9209-abafe71bf869"),
                            Age = 94,
                            EmailAddress = "Larue46@hotmail.com",
                            Gender = "Male",
                            Name = "Marley",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            Age = 50,
                            EmailAddress = "Jocelyn.Keebler@gmail.com",
                            Gender = "Female",
                            Name = "Sim",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("4d9841a6-c134-699d-e7b5-1a99feed439a"),
                            Age = 41,
                            EmailAddress = "Kacie.Renner92@hotmail.com",
                            Gender = "Female",
                            Name = "Louie",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Age = 49,
                            EmailAddress = "Jayne17@gmail.com",
                            Gender = "Male",
                            Name = "Nicolas",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        },
                        new
                        {
                            Id = new Guid("2cbb1d4f-9767-2580-3984-618cd8c03c11"),
                            Age = 44,
                            EmailAddress = "Darron70@yahoo.com",
                            Gender = "Female",
                            Name = "Greyson",
                            PasswordHash = "$2a$11$DvROBdylWGmrlJGDJUF/7.0.yl.qgxDvExr.uxUoozh6GcgBTWzoK"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
