// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vladify.DataAccess;

#nullable disable

namespace Vladify.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528123645_addPlaylistEntity")]
    partial class addPlaylistEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlaylistsId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("PlaylistSong");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fdea678-4a21-6d13-4185-9484e1a21ecd"),
                            Album = "Small Cotton Mouse",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Duration = new TimeSpan(0, 0, 3, 11, 0),
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("b7053f45-fca3-1f8a-b8e1-efe7dd651dbb"),
                            Album = "Incredible Metal Soap",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Title = "You can't hack"
                        },
                        new
                        {
                            Id = new Guid("ffa11ec6-7a71-cd50-2e3c-cef187578365"),
                            Album = "Rustic Metal Chips",
                            AuthorId = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Duration = new TimeSpan(0, 0, 3, 29, 0),
                            Title = "You can't calculate"
                        },
                        new
                        {
                            Id = new Guid("43067c1f-b942-c469-0117-e17e6c8c97ee"),
                            Album = "Incredible Fresh Gloves",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            Duration = new TimeSpan(0, 0, 2, 52, 0),
                            Title = "You can't connect"
                        },
                        new
                        {
                            Id = new Guid("727f6ad6-57b1-3100-5127-f88b371e9382"),
                            Album = "Generic Metal Shirt",
                            AuthorId = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            Duration = new TimeSpan(0, 0, 2, 52, 0),
                            Title = "The COM hard"
                        },
                        new
                        {
                            Id = new Guid("b819c9a4-89e2-9214-5982-a42f276b5b46"),
                            Album = "Unbranded Rubber Gloves",
                            AuthorId = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("5ffeb0ea-034c-5bc9-6738-6f1602228b39"),
                            Album = "Generic Cotton Cheese",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Duration = new TimeSpan(0, 0, 2, 30, 0),
                            Title = "Use the bluetooth"
                        },
                        new
                        {
                            Id = new Guid("04f5621f-6374-2a1e-e25b-22572c5d0ff3"),
                            Album = "Small Cotton Car",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("58d08c88-a2c6-aabc-f972-33fbb2e4f8a8"),
                            Album = "Handmade Cotton Soap",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Title = "bypassing the circuit"
                        },
                        new
                        {
                            Id = new Guid("215a3c02-099a-969f-9d11-025cb470b216"),
                            Album = "Tasty Concrete Hat",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            Duration = new TimeSpan(0, 0, 3, 6, 0),
                            Title = "The IB protocol"
                        },
                        new
                        {
                            Id = new Guid("ff21b565-9e0b-ba73-6e9e-5098f1134e5b"),
                            Album = "Ergonomic Steel Towels",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Duration = new TimeSpan(0, 0, 2, 43, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("3102b699-832c-394b-e07b-12f7bd41b644"),
                            Album = "Practical Fresh Chicken",
                            AuthorId = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Title = "You can't parse"
                        },
                        new
                        {
                            Id = new Guid("37f9ba80-1a08-da34-036c-6c2415a6d96d"),
                            Album = "Refined Rubber Table",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Duration = new TimeSpan(0, 0, 3, 2, 0),
                            Title = "hacking the firewall"
                        },
                        new
                        {
                            Id = new Guid("5fc651bf-b8e4-cb0a-7fe7-4309dd8967b2"),
                            Album = "Handmade Rubber Keyboard",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Title = "If we program"
                        },
                        new
                        {
                            Id = new Guid("b553f91c-547d-7493-883d-0c876c0bdb5a"),
                            Album = "Ergonomic Soft Bacon",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Duration = new TimeSpan(0, 0, 3, 17, 0),
                            Title = "Use the auxiliary"
                        },
                        new
                        {
                            Id = new Guid("b576eec2-7d41-ed08-d12b-32c6b54914de"),
                            Album = "Gorgeous Wooden Table",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("c5252774-cd7d-d1cc-8511-88cb0a631d0a"),
                            Album = "Gorgeous Frozen Towels",
                            AuthorId = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "You can't hack"
                        },
                        new
                        {
                            Id = new Guid("2178d866-9e41-941e-c5ab-66b4f8e8788e"),
                            Album = "Gorgeous Soft Tuna",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            Duration = new TimeSpan(0, 0, 2, 55, 0),
                            Title = "synthesizing the array"
                        },
                        new
                        {
                            Id = new Guid("c6114ea0-c901-66bd-f80d-f0472debcf58"),
                            Album = "Rustic Cotton Bacon",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            Duration = new TimeSpan(0, 0, 2, 30, 0),
                            Title = "copying the application"
                        },
                        new
                        {
                            Id = new Guid("31f962d5-a21f-7ec0-45b4-e464ea3b827f"),
                            Album = "Practical Cotton Towels",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Title = "bypassing the bandwidth"
                        },
                        new
                        {
                            Id = new Guid("c7b75900-3d55-e78f-03fe-dbd0a46c6d89"),
                            Album = "Small Cotton Computer",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Title = "The SMTP protocol"
                        },
                        new
                        {
                            Id = new Guid("79b769ab-bdb4-c0e1-248d-ec8f275a537f"),
                            Album = "Intelligent Metal Chicken",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Duration = new TimeSpan(0, 0, 3, 11, 0),
                            Title = "indexing the card"
                        },
                        new
                        {
                            Id = new Guid("a292a61f-895a-e44b-7e4b-852713c3ac49"),
                            Album = "Awesome Concrete Chair",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Title = "copying the array"
                        },
                        new
                        {
                            Id = new Guid("af878b8c-9b73-c10f-1991-eb9105db76d5"),
                            Album = "Sleek Cotton Hat",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("4cccd053-f933-bfbf-58f7-9c128c030193"),
                            Album = "Gorgeous Frozen Computer",
                            AuthorId = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Title = "Try to reboot"
                        },
                        new
                        {
                            Id = new Guid("a0b3d38c-595f-bcbf-f14d-45b898461c1d"),
                            Album = "Intelligent Concrete Table",
                            AuthorId = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "If we bypass"
                        },
                        new
                        {
                            Id = new Guid("25576f79-4301-3290-eba4-563db8cc4710"),
                            Album = "Intelligent Concrete Tuna",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Title = "If we generate"
                        },
                        new
                        {
                            Id = new Guid("93ae5074-34ca-4525-4c99-284375081331"),
                            Album = "Fantastic Wooden Bike",
                            AuthorId = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Title = "quantifying the firewall"
                        },
                        new
                        {
                            Id = new Guid("bca93494-9f15-1b46-e23c-118c089386fa"),
                            Album = "Practical Plastic Soap",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Title = "If we synthesize"
                        },
                        new
                        {
                            Id = new Guid("cf24c7d6-4ae5-9096-11a3-dd12a42fed31"),
                            Album = "Sleek Plastic Keyboard",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            Duration = new TimeSpan(0, 0, 3, 23, 0),
                            Title = "The EXE pixel"
                        },
                        new
                        {
                            Id = new Guid("5b1f0819-60a8-706e-53bd-6c2b41720275"),
                            Album = "Practical Metal Bacon",
                            AuthorId = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("70153693-650e-7cad-87f1-4734b236bf99"),
                            Album = "Tasty Rubber Hat",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            Duration = new TimeSpan(0, 0, 3, 14, 0),
                            Title = "compressing the sensor"
                        },
                        new
                        {
                            Id = new Guid("00ae81eb-9076-dafb-393e-4c5ec694f57a"),
                            Album = "Ergonomic Metal Chicken",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            Duration = new TimeSpan(0, 0, 3, 24, 0),
                            Title = "If we parse"
                        },
                        new
                        {
                            Id = new Guid("b90cf885-5856-c16e-fbd9-f1d1a4b65b85"),
                            Album = "Handmade Fresh Shoes",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "If we calculate"
                        },
                        new
                        {
                            Id = new Guid("c783f8a3-cb68-7632-e22c-84f60558d2fa"),
                            Album = "Rustic Frozen Fish",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("66d79c37-a06d-cafb-c877-118805714079"),
                            Album = "Ergonomic Granite Keyboard",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("e08bacba-fa08-fa96-d90a-c517560a8d0a"),
                            Album = "Awesome Frozen Fish",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            Duration = new TimeSpan(0, 0, 3, 11, 0),
                            Title = "calculating the microchip"
                        },
                        new
                        {
                            Id = new Guid("58aee418-5e53-40ac-1e3c-97098e6f7666"),
                            Album = "Fantastic Concrete Chicken",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            Duration = new TimeSpan(0, 0, 2, 47, 0),
                            Title = "You can't reboot"
                        },
                        new
                        {
                            Id = new Guid("772e59a5-7813-7db0-162a-b272b9aac96f"),
                            Album = "Refined Wooden Soap",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            Duration = new TimeSpan(0, 0, 2, 55, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("439a8a2f-4a68-0686-e7ef-c58390ddf160"),
                            Album = "Unbranded Concrete Table",
                            AuthorId = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Title = "Use the open-source"
                        },
                        new
                        {
                            Id = new Guid("205ecd0e-05f7-81c3-f37b-e6492732a3e2"),
                            Album = "Gorgeous Plastic Salad",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            Duration = new TimeSpan(0, 0, 2, 59, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("1e6ade85-ffc4-77bc-3989-cfce7dcd5cfe"),
                            Album = "Licensed Metal Table",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("a05438ef-97cf-3dfc-a289-5d224a6bba69"),
                            Album = "Incredible Steel Shirt",
                            AuthorId = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "I'll program the"
                        },
                        new
                        {
                            Id = new Guid("c96ff837-adaa-cc8c-3fe4-e9ff36818fb9"),
                            Album = "Unbranded Fresh Chicken",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            Duration = new TimeSpan(0, 0, 3, 27, 0),
                            Title = "I'll program the"
                        },
                        new
                        {
                            Id = new Guid("c05fae4a-f237-c431-4532-bfb375bd9e7b"),
                            Album = "Sleek Cotton Keyboard",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Title = "If we program"
                        },
                        new
                        {
                            Id = new Guid("59d520d7-6fd8-4181-1edf-23b10c04bc4a"),
                            Album = "Practical Soft Keyboard",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            Duration = new TimeSpan(0, 0, 3, 23, 0),
                            Title = "You can't navigate"
                        },
                        new
                        {
                            Id = new Guid("fc25b1c2-02b3-5a3f-a36f-d8e743f37c7f"),
                            Album = "Handcrafted Steel Pants",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            Duration = new TimeSpan(0, 0, 3, 2, 0),
                            Title = "indexing the card"
                        },
                        new
                        {
                            Id = new Guid("3785e647-98b3-bf37-8ff9-e270aecda919"),
                            Album = "Refined Metal Fish",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Title = "Use the solid"
                        },
                        new
                        {
                            Id = new Guid("23631539-7a4e-f78c-731e-37254e0c34ed"),
                            Album = "Generic Steel Hat",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("857558ab-cbfb-fdfb-a92c-d594f622d636"),
                            Album = "Unbranded Metal Bacon",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            Duration = new TimeSpan(0, 0, 2, 52, 0),
                            Title = "Use the redundant"
                        },
                        new
                        {
                            Id = new Guid("ef82e5c7-6dce-e0d0-9efd-983c59520e8b"),
                            Album = "Gorgeous Frozen Ball",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "If we input"
                        },
                        new
                        {
                            Id = new Guid("8b561526-af3e-34f3-1827-3c0626254238"),
                            Album = "Refined Fresh Ball",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("e9c6c8eb-021d-a90c-ca47-725a8d651ef6"),
                            Album = "Practical Steel Bike",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "I'll calculate the"
                        },
                        new
                        {
                            Id = new Guid("150ab234-1c51-085d-6b51-3e1e031a7c77"),
                            Album = "Incredible Frozen Tuna",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "Use the 1080p"
                        },
                        new
                        {
                            Id = new Guid("e002407c-b2b1-d766-f7bf-31213d2f5db2"),
                            Album = "Ergonomic Fresh Shirt",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Duration = new TimeSpan(0, 0, 2, 52, 0),
                            Title = "Try to quantify"
                        },
                        new
                        {
                            Id = new Guid("633326d3-c059-e0f6-c769-708c6c9d4284"),
                            Album = "Awesome Frozen Gloves",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Duration = new TimeSpan(0, 0, 2, 33, 0),
                            Title = "The PNG capacitor"
                        },
                        new
                        {
                            Id = new Guid("2c0d2442-82c0-9220-b1c3-5bd861474e96"),
                            Album = "Ergonomic Plastic Car",
                            AuthorId = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Duration = new TimeSpan(0, 0, 3, 6, 0),
                            Title = "Use the digital"
                        },
                        new
                        {
                            Id = new Guid("59cb66e9-01e2-b4d5-bcb9-3db00a4b0b91"),
                            Album = "Rustic Frozen Soap",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Duration = new TimeSpan(0, 0, 2, 45, 0),
                            Title = "I'll parse the"
                        },
                        new
                        {
                            Id = new Guid("9250a1e3-4415-371c-2be5-6979d68b9292"),
                            Album = "Sleek Wooden Towels",
                            AuthorId = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "You can't generate"
                        },
                        new
                        {
                            Id = new Guid("b8908fe2-fab3-f1a3-126c-27286ced14df"),
                            Album = "Generic Metal Chair",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            Duration = new TimeSpan(0, 0, 3, 30, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("3d92e6b0-e472-390a-a79b-2db67e329a7f"),
                            Album = "Fantastic Concrete Bacon",
                            AuthorId = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Title = "I'll input the"
                        },
                        new
                        {
                            Id = new Guid("97c7f282-8fb0-f2a1-0b80-2fb44461b36d"),
                            Album = "Intelligent Metal Table",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Title = "I'll reboot the"
                        },
                        new
                        {
                            Id = new Guid("2dc918b7-3581-88c3-47df-047d26dd408f"),
                            Album = "Handcrafted Cotton Bacon",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Duration = new TimeSpan(0, 0, 3, 17, 0),
                            Title = "You can't navigate"
                        },
                        new
                        {
                            Id = new Guid("26826544-8a52-ea82-da41-52ae7e80d96c"),
                            Album = "Unbranded Soft Ball",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Title = "Try to input"
                        },
                        new
                        {
                            Id = new Guid("f0ecc858-6647-7f5b-22c4-b9b1f3a4f365"),
                            Album = "Incredible Cotton Hat",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Title = "You can't compress"
                        },
                        new
                        {
                            Id = new Guid("11d7a753-0e7a-2903-21ee-510b472301b6"),
                            Album = "Practical Cotton Chips",
                            AuthorId = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Duration = new TimeSpan(0, 0, 3, 19, 0),
                            Title = "If we synthesize"
                        },
                        new
                        {
                            Id = new Guid("4d467d69-6056-07c6-d74b-b33ea2ef7ad1"),
                            Album = "Sleek Concrete Salad",
                            AuthorId = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Title = "I'll override the"
                        },
                        new
                        {
                            Id = new Guid("976fc1ca-174d-9a4d-acda-a0faab811b29"),
                            Album = "Handmade Granite Table",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "The IB panel"
                        },
                        new
                        {
                            Id = new Guid("6b584d62-4b83-fb85-4667-b365275555ce"),
                            Album = "Fantastic Fresh Pants",
                            AuthorId = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Duration = new TimeSpan(0, 0, 2, 47, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("af006ebd-2a52-eab5-4c53-6f1daf2585d4"),
                            Album = "Handmade Granite Salad",
                            AuthorId = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Duration = new TimeSpan(0, 0, 3, 29, 0),
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("a05a1fe3-4c84-c82c-8d46-b8613a716b08"),
                            Album = "Awesome Granite Car",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("36e2f588-0fc5-d1fe-caf1-b3ebd0835df8"),
                            Album = "Unbranded Granite Tuna",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Title = "The HDD hard"
                        },
                        new
                        {
                            Id = new Guid("2aafea5d-2a9f-a383-d2aa-0ff2513ca0a0"),
                            Album = "Refined Fresh Pizza",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Title = "The TCP array"
                        },
                        new
                        {
                            Id = new Guid("d0365dcd-94f5-a11d-e71b-c714c04ce08a"),
                            Album = "Unbranded Concrete Shoes",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Duration = new TimeSpan(0, 0, 2, 32, 0),
                            Title = "The JBOD program"
                        },
                        new
                        {
                            Id = new Guid("cde9ea23-f403-b625-459c-da1a5d339bb9"),
                            Album = "Incredible Concrete Salad",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Title = "If we navigate"
                        },
                        new
                        {
                            Id = new Guid("8ed272ee-5087-fa4c-b6fd-4dc41f9a969a"),
                            Album = "Ergonomic Frozen Computer",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("360234ac-f369-374f-4473-0d52ca1139e4"),
                            Album = "Small Wooden Fish",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Title = "You can't reboot"
                        },
                        new
                        {
                            Id = new Guid("cccf72d4-f135-a087-c5b4-c7e3d0d06351"),
                            Album = "Unbranded Metal Shoes",
                            AuthorId = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Title = "Try to program"
                        },
                        new
                        {
                            Id = new Guid("07e0a687-69f6-7b9c-c574-a6d861437073"),
                            Album = "Generic Soft Chicken",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("e9db3caf-67fe-00f0-fae4-acd07a34559d"),
                            Album = "Ergonomic Soft Tuna",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Duration = new TimeSpan(0, 0, 3, 21, 0),
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("b4f1a83d-d7ee-ed02-3ee9-8ba871714375"),
                            Album = "Handcrafted Frozen Fish",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("74187711-83f6-b253-5708-30bef9784716"),
                            Album = "Tasty Fresh Shirt",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Title = "I'll parse the"
                        },
                        new
                        {
                            Id = new Guid("1968cf8d-dc08-f077-7526-7594241dbeeb"),
                            Album = "Unbranded Soft Salad",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            Duration = new TimeSpan(0, 0, 2, 54, 0),
                            Title = "The PNG program"
                        },
                        new
                        {
                            Id = new Guid("83b5fe12-2791-c5e2-e3ee-ef27e28287d1"),
                            Album = "Small Concrete Computer",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("db774e40-3592-6462-f2c0-a3e46d4257db"),
                            Album = "Handcrafted Metal Keyboard",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Duration = new TimeSpan(0, 0, 2, 44, 0),
                            Title = "I'll program the"
                        },
                        new
                        {
                            Id = new Guid("60d78300-724d-a281-766c-135cf27f1d94"),
                            Album = "Practical Steel Sausages",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Title = "If we quantify"
                        },
                        new
                        {
                            Id = new Guid("0fe166fe-c78d-6117-e11b-5f5571ec9fe1"),
                            Album = "Tasty Rubber Towels",
                            AuthorId = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Title = "Try to generate"
                        },
                        new
                        {
                            Id = new Guid("add0dfab-4e88-8236-3c95-5c8694da1e3c"),
                            Album = "Incredible Wooden Soap",
                            AuthorId = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Duration = new TimeSpan(0, 0, 3, 5, 0),
                            Title = "The RAM capacitor"
                        },
                        new
                        {
                            Id = new Guid("842175d9-99f4-6b4b-8211-6dd7073b6963"),
                            Album = "Ergonomic Concrete Shoes",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Title = "The THX capacitor"
                        },
                        new
                        {
                            Id = new Guid("8b9ed91a-d16c-5d93-0d1a-1067ec496f9c"),
                            Album = "Awesome Rubber Shoes",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("55279550-d1d9-318e-92e3-85010674de5c"),
                            Album = "Unbranded Fresh Shoes",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            Duration = new TimeSpan(0, 0, 2, 52, 0),
                            Title = "I'll input the"
                        },
                        new
                        {
                            Id = new Guid("aa6a225c-8f5a-42a5-c7e5-c437955d17dd"),
                            Album = "Handcrafted Granite Pizza",
                            AuthorId = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("06ed55e8-0796-319e-0f27-382a71603116"),
                            Album = "Handcrafted Metal Salad",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Title = "backing up the"
                        },
                        new
                        {
                            Id = new Guid("45868db7-d3f0-bd28-ecda-df2e30f72b08"),
                            Album = "Incredible Soft Table",
                            AuthorId = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "I'll compress the"
                        },
                        new
                        {
                            Id = new Guid("fe38bd4d-e18a-e608-a488-e1485649a344"),
                            Album = "Handcrafted Soft Shirt",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            Duration = new TimeSpan(0, 0, 2, 56, 0),
                            Title = "Try to copy"
                        },
                        new
                        {
                            Id = new Guid("61d46d8d-39a3-da62-ffb4-dc554c281087"),
                            Album = "Refined Frozen Pants",
                            AuthorId = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("d09a6053-8990-7bc5-79d0-263d0ef46ea4"),
                            Album = "Rustic Granite Shoes",
                            AuthorId = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            Duration = new TimeSpan(0, 0, 2, 47, 0),
                            Title = "The JSON application"
                        },
                        new
                        {
                            Id = new Guid("5667bfcd-58d4-0e54-7a65-e44ccb87ad97"),
                            Album = "Licensed Wooden Car",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Title = "programming the transmitter"
                        },
                        new
                        {
                            Id = new Guid("f8fa473a-593d-f7ad-bc11-7a52e5b9e6f4"),
                            Album = "Rustic Cotton Salad",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            Duration = new TimeSpan(0, 0, 3, 10, 0),
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("f195edac-8937-1a14-c77f-6ca7f21e90f1"),
                            Album = "Incredible Rubber Fish",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            Duration = new TimeSpan(0, 0, 2, 47, 0),
                            Title = "We need to"
                        });
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Age = 19,
                            EmailAddress = "Sabina.Marvin26@gmail.com",
                            ExternalId = "auth0|d8b0d2646f930a379fe684d8",
                            Gender = "Female",
                            Name = "Marianne"
                        },
                        new
                        {
                            Id = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Age = 99,
                            EmailAddress = "Jeanette.Bartoletti@hotmail.com",
                            ExternalId = "auth0|d8d5248b2594d52b85cd5352",
                            Gender = "Female",
                            Name = "Joanie"
                        },
                        new
                        {
                            Id = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Age = 94,
                            EmailAddress = "Larue46@hotmail.com",
                            ExternalId = "auth0|1b95a2b93ad5c83c5c75374d",
                            Gender = "Male",
                            Name = "Marley"
                        },
                        new
                        {
                            Id = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            Age = 41,
                            EmailAddress = "Kacie.Renner92@hotmail.com",
                            ExternalId = "auth0|e486a6697cad876bc62f970b",
                            Gender = "Female",
                            Name = "Louie"
                        },
                        new
                        {
                            Id = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Age = 44,
                            EmailAddress = "Darron70@yahoo.com",
                            ExternalId = "auth0|c0734263ccfdaafd54b28c4a",
                            Gender = "Female",
                            Name = "Greyson"
                        },
                        new
                        {
                            Id = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            Age = 88,
                            EmailAddress = "Clotilde_Swaniawski@gmail.com",
                            ExternalId = "auth0|52a0838fcdcce32176a06863",
                            Gender = "Male",
                            Name = "Vernice"
                        },
                        new
                        {
                            Id = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            Age = 50,
                            EmailAddress = "Thaddeus_Doyle90@yahoo.com",
                            ExternalId = "auth0|71464b4db7170a63f5f66302",
                            Gender = "Male",
                            Name = "Guadalupe"
                        },
                        new
                        {
                            Id = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            Age = 90,
                            EmailAddress = "Ines_Balistreri@gmail.com",
                            ExternalId = "auth0|7af854402fac00e8a384ef82",
                            Gender = "Female",
                            Name = "Tressa"
                        },
                        new
                        {
                            Id = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            Age = 73,
                            EmailAddress = "Cesar.Kertzmann58@gmail.com",
                            ExternalId = "auth0|409472f82d94d3841f5bacac",
                            Gender = "Female",
                            Name = "Ephraim"
                        },
                        new
                        {
                            Id = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Age = 74,
                            EmailAddress = "Norbert_Schroeder@gmail.com",
                            ExternalId = "auth0|e58f8575cf3f8b24e6571f8d",
                            Gender = "Female",
                            Name = "William"
                        },
                        new
                        {
                            Id = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            Age = 91,
                            EmailAddress = "Delia_Weissnat@gmail.com",
                            ExternalId = "auth0|dc5306dedbf39ac445bfd733",
                            Gender = "Female",
                            Name = "Bridget"
                        },
                        new
                        {
                            Id = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Age = 52,
                            EmailAddress = "Domenick_Steuber@hotmail.com",
                            ExternalId = "auth0|535aae56811c2e6ed5cfb00c",
                            Gender = "Male",
                            Name = "Jada"
                        },
                        new
                        {
                            Id = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            Age = 49,
                            EmailAddress = "Manley_Cronin40@gmail.com",
                            ExternalId = "auth0|8e7649d4282d97b9af274259",
                            Gender = "Male",
                            Name = "Gerhard"
                        },
                        new
                        {
                            Id = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            Age = 38,
                            EmailAddress = "Stephen48@yahoo.com",
                            ExternalId = "auth0|966e3969e00ea631cb22f2a2",
                            Gender = "Male",
                            Name = "Arne"
                        },
                        new
                        {
                            Id = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Age = 43,
                            EmailAddress = "Daniella_Senger@gmail.com",
                            ExternalId = "auth0|ff55cad7b4daa656cc153a24",
                            Gender = "Female",
                            Name = "Shirley"
                        },
                        new
                        {
                            Id = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            Age = 73,
                            EmailAddress = "Sammie.Kilback58@hotmail.com",
                            ExternalId = "auth0|c2300db4d17770e0fd3b514d",
                            Gender = "Male",
                            Name = "Elisa"
                        },
                        new
                        {
                            Id = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            Age = 43,
                            EmailAddress = "Leslie44@yahoo.com",
                            ExternalId = "auth0|bccf82be5b1f4667c6b098af",
                            Gender = "Male",
                            Name = "Marcia"
                        },
                        new
                        {
                            Id = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            Age = 28,
                            EmailAddress = "Miller.Carter@gmail.com",
                            ExternalId = "auth0|0998f7431d4181ce6e9a5bb1",
                            Gender = "Male",
                            Name = "Rhoda"
                        },
                        new
                        {
                            Id = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            Age = 75,
                            EmailAddress = "Elmer76@yahoo.com",
                            ExternalId = "auth0|a41e05f4e8bbb2dfa3a3731a",
                            Gender = "Male",
                            Name = "Lester"
                        },
                        new
                        {
                            Id = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            Age = 65,
                            EmailAddress = "Timmy_Considine@yahoo.com",
                            ExternalId = "auth0|1932dbc737460922d683bbf7",
                            Gender = "Male",
                            Name = "Brennon"
                        },
                        new
                        {
                            Id = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Age = 53,
                            EmailAddress = "Jett.Robel53@gmail.com",
                            ExternalId = "auth0|287a0086ac05cae7e30e4994",
                            Gender = "Male",
                            Name = "Sterling"
                        },
                        new
                        {
                            Id = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Age = 42,
                            EmailAddress = "Halle_Pfannerstill73@gmail.com",
                            ExternalId = "auth0|7aba268e3c08c9249e9ad2f2",
                            Gender = "Male",
                            Name = "Maryam"
                        },
                        new
                        {
                            Id = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            Age = 58,
                            EmailAddress = "Mariano.Braun85@gmail.com",
                            ExternalId = "auth0|7e41734a9fdfdf60a11356ca",
                            Gender = "Male",
                            Name = "Pearline"
                        },
                        new
                        {
                            Id = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            Age = 67,
                            EmailAddress = "Corine.Cormier98@gmail.com",
                            ExternalId = "auth0|26bc1501a4483e815ee97872",
                            Gender = "Female",
                            Name = "Lelah"
                        },
                        new
                        {
                            Id = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            Age = 72,
                            EmailAddress = "Letha_Ratke@gmail.com",
                            ExternalId = "auth0|c1ea939e82e2e265a0c4df9e",
                            Gender = "Male",
                            Name = "Ernie"
                        },
                        new
                        {
                            Id = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            Age = 86,
                            EmailAddress = "Elizabeth_Braun@yahoo.com",
                            ExternalId = "auth0|69fe1fec7f569e507938043b",
                            Gender = "Female",
                            Name = "Brenda"
                        },
                        new
                        {
                            Id = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            Age = 28,
                            EmailAddress = "Amelie.Pollich@gmail.com",
                            ExternalId = "auth0|59183f9253c8ad6726aa967b",
                            Gender = "Female",
                            Name = "Enrique"
                        },
                        new
                        {
                            Id = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            Age = 66,
                            EmailAddress = "Emery.Kunde76@hotmail.com",
                            ExternalId = "auth0|e2f2df7f262fee8312871a9d",
                            Gender = "Female",
                            Name = "Monique"
                        },
                        new
                        {
                            Id = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            Age = 100,
                            EmailAddress = "Earnest67@hotmail.com",
                            ExternalId = "auth0|53d2d94826faf10990721115",
                            Gender = "Female",
                            Name = "Julien"
                        },
                        new
                        {
                            Id = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            Age = 61,
                            EmailAddress = "Lizzie52@hotmail.com",
                            ExternalId = "auth0|9d8a637327a243676fb0a2a2",
                            Gender = "Male",
                            Name = "Zaria"
                        });
                });

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vladify.DataAccess.Entities.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Playlist", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.User", "Owner")
                        .WithMany("Playlists")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.User", "Owner")
                        .WithMany("OwnedSongs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Navigation("OwnedSongs");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
