// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vladify.DataAccess.Storage;

#nullable disable

namespace Vladify.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasAlternateKey("MessageId", "ConsumerId");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlaylistsId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("PlaylistSong");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fdea678-4a21-6d13-4185-9484e1a21ecd"),
                            Album = "Small Cotton Mouse",
                            AudioUrl = "http://marlon.org/money-market-account/metal/globa",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            CoverUrl = "http://alvera.name/scalable",
                            Duration = new TimeSpan(0, 0, 3, 11, 0),
                            Status = "Approved",
                            Title = "Use the back-end"
                        },
                        new
                        {
                            Id = new Guid("da2c1490-39c9-74c1-ea93-c61ea1ff717a"),
                            Album = "Awesome Concrete Tuna",
                            AudioUrl = "https://abbey.org/small-cotton-tuna/metal",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            CoverUrl = "http://cristian.com/indiana/home-loan-account",
                            Duration = new TimeSpan(0, 0, 2, 57, 0),
                            Status = "Pending",
                            Title = "The SCSI bandwidth"
                        },
                        new
                        {
                            Id = new Guid("6c7ee117-978c-7fee-089f-8cd556634d61"),
                            Album = "Tasty Steel Cheese",
                            AudioUrl = "https://kenyatta.biz/mayotte/cross-platform/salmon",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "http://laury.info/vermont/credit-card-account",
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Status = "Rejected",
                            Title = "You can't reboot"
                        },
                        new
                        {
                            Id = new Guid("e2b819c9-1489-5992-82a4-2f276b5b46c7"),
                            Album = "Awesome Plastic Chair",
                            AudioUrl = "https://alfonzo.info/fantastic-granite-pants/plati",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            CoverUrl = "http://tillman.name/valley",
                            Duration = new TimeSpan(0, 0, 3, 19, 0),
                            Status = "Approved",
                            Title = "I'll reboot the"
                        },
                        new
                        {
                            Id = new Guid("5ee2bbd9-a5df-a998-471f-62f50474631e"),
                            Album = "Incredible Fresh Table",
                            AudioUrl = "https://okey.com/national/http/optimize",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            CoverUrl = "http://libby.com/input/street",
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Status = "Rejected",
                            Title = "If we quantify"
                        },
                        new
                        {
                            Id = new Guid("e4b2fb33-a8f8-ddde-52ad-5dd26ad14d28"),
                            Album = "Fantastic Rubber Computer",
                            AudioUrl = "http://mireille.net/refined",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "https://winifred.biz/connecting/backing-up",
                            Duration = new TimeSpan(0, 0, 3, 16, 0),
                            Status = "Approved",
                            Title = "You can't quantify"
                        },
                        new
                        {
                            Id = new Guid("b565bd17-ff21-9e0b-73ba-6e9e5098f113"),
                            Album = "Unbranded Concrete Computer",
                            AudioUrl = "http://crawford.name/innovative",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "https://roosevelt.name/drive",
                            Duration = new TimeSpan(0, 0, 3, 5, 0),
                            Status = "Approved",
                            Title = "If we parse"
                        },
                        new
                        {
                            Id = new Guid("b641bdf7-7844-422f-6aaa-47f0a24c7379"),
                            Album = "Gorgeous Steel Hat",
                            AudioUrl = "http://carolina.name/leverage/savings-account/sms",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            CoverUrl = "http://ambrose.info/hdd/supply-chains/philippines",
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Status = "Rejected",
                            Title = "The SMTP application"
                        },
                        new
                        {
                            Id = new Guid("7fcb0ab8-43e7-dd09-8967-b2d80b0a2cc4"),
                            Album = "Handmade Frozen Bacon",
                            AudioUrl = "https://jennie.org/new-jersey",
                            AuthorId = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            CoverUrl = "http://donald.org/extended/generic/crescent",
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Status = "Pending",
                            Title = "I'll calculate the"
                        },
                        new
                        {
                            Id = new Guid("af378ed4-c287-76ee-b541-7d08edd12b32"),
                            Album = "Gorgeous Steel Fish",
                            AudioUrl = "https://lizzie.org/practical-steel-car",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            CoverUrl = "http://golden.net/reboot",
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Status = "Rejected",
                            Title = "Try to hack"
                        },
                        new
                        {
                            Id = new Guid("630acb88-0a1d-532f-d5c5-be26165ec3b3"),
                            Album = "Rustic Granite Computer",
                            AudioUrl = "https://brandt.org/hardware",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            CoverUrl = "https://malvina.name/rubber/cross-platform/illinoi",
                            Duration = new TimeSpan(0, 0, 2, 39, 0),
                            Status = "Approved",
                            Title = "generating the sensor"
                        },
                        new
                        {
                            Id = new Guid("c6114ea0-c901-66bd-f80d-f0472debcf58"),
                            Album = "Rustic Cotton Bacon",
                            AudioUrl = "http://mazie.biz/bluetooth/transmit",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "http://olin.name/channels/interface",
                            Duration = new TimeSpan(0, 0, 2, 30, 0),
                            Status = "Rejected",
                            Title = "copying the application"
                        },
                        new
                        {
                            Id = new Guid("8ed2a6dc-ab6c-7d80-62c1-0059b7c7553d"),
                            Album = "Handcrafted Soft Hat",
                            AudioUrl = "https://stefan.info/sierra-leone/tasty-steel-shirt",
                            AuthorId = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            CoverUrl = "http://jamil.org/cohesive/proactive",
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Status = "Approved",
                            Title = "I'll synthesize the"
                        },
                        new
                        {
                            Id = new Guid("535a278f-807f-0ba6-0165-20e2070519ad"),
                            Album = "Handcrafted Steel Pants",
                            AudioUrl = "https://anita.org/engage",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            CoverUrl = "http://jerod.name/money-market-account",
                            Duration = new TimeSpan(0, 0, 3, 5, 0),
                            Status = "Pending",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("8cca616f-878b-73af-9b0f-c11991eb9105"),
                            Album = "Intelligent Fresh Towels",
                            AudioUrl = "http://isadore.com/handcrafted/bricks-and-clicks",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "http://aaliyah.com/rustic-metal-mouse",
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Status = "Rejected",
                            Title = "You can't hack"
                        },
                        new
                        {
                            Id = new Guid("0fb79301-e525-e361-79a6-4bef698cd3b3"),
                            Album = "Gorgeous Plastic Pizza",
                            AudioUrl = "http://cary.com/driver",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            CoverUrl = "http://bethany.org/intelligent/violet",
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Status = "Approved",
                            Title = "The GB card"
                        },
                        new
                        {
                            Id = new Guid("43012557-3290-a4eb-563d-b8cc47104671"),
                            Album = "Handcrafted Frozen Bacon",
                            AudioUrl = "https://breana.org/grove/cotton/personal-loan-acco",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            CoverUrl = "https://dayana.net/scale/fresh",
                            Duration = new TimeSpan(0, 0, 2, 49, 0),
                            Status = "Approved",
                            Title = "If we override"
                        },
                        new
                        {
                            Id = new Guid("aedf2bad-9d7f-3494-a9bc-159f461be23c"),
                            Album = "Ergonomic Frozen Chair",
                            AudioUrl = "https://tom.net/inlet/investment-account/direction",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "https://ethel.name/officer/array",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Status = "Approved",
                            Title = "Try to generate"
                        },
                        new
                        {
                            Id = new Guid("f431ed2f-fb67-9d51-9fb2-b4c1809d1908"),
                            Album = "Awesome Granite Fish",
                            AudioUrl = "http://leatha.info/distributed/legacy/infrastructu",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            CoverUrl = "https://johnnie.com/digital/metal/yuan-renminbi",
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Status = "Pending",
                            Title = "bypassing the microchip"
                        },
                        new
                        {
                            Id = new Guid("47f1877c-b234-bf36-9973-883bbade9b29"),
                            Album = "Sleek Wooden Car",
                            AudioUrl = "https://archibald.org/synergize/ssl",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "http://lou.net/rustic/handmade-wooden-sausages",
                            Duration = new TimeSpan(0, 0, 3, 27, 0),
                            Status = "Pending",
                            Title = "Use the optical"
                        },
                        new
                        {
                            Id = new Guid("0cf8855d-56b9-6e58-c1fb-d9f1d1a4b65b"),
                            Album = "Generic Metal Salad",
                            AudioUrl = "https://seamus.info/spring",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            CoverUrl = "https://furman.net/kansas/handcrafted/usb",
                            Duration = new TimeSpan(0, 0, 2, 57, 0),
                            Status = "Approved",
                            Title = "synthesizing the transmitter"
                        },
                        new
                        {
                            Id = new Guid("c03d92a1-f7a2-a26d-bf6d-35379cd7666d"),
                            Album = "Unbranded Soft Tuna",
                            AudioUrl = "http://isac.info/client-server",
                            AuthorId = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            CoverUrl = "https://lexi.org/avon",
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Status = "Pending",
                            Title = "The EXE monitor"
                        },
                        new
                        {
                            Id = new Guid("fa08e08b-fa96-0ad9-c517-560a8d0a828f"),
                            Album = "Handmade Granite Chicken",
                            AudioUrl = "https://bernadine.biz/realigned/ergonomic/nebraska",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "http://jada.com/project/coordinator",
                            Duration = new TimeSpan(0, 0, 2, 41, 0),
                            Status = "Pending",
                            Title = "transmitting the hard"
                        },
                        new
                        {
                            Id = new Guid("ef6b498e-d709-59a5-2e77-1378b07d162a"),
                            Album = "Rustic Soft Hat",
                            AudioUrl = "http://immanuel.com/hacking/money-market-account",
                            AuthorId = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            CoverUrl = "https://elmo.biz/hard-drive/station/investment-acc",
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Status = "Approved",
                            Title = "If we back"
                        },
                        new
                        {
                            Id = new Guid("3c60f1dd-21bd-3004-501f-7c7f698d0ecd"),
                            Album = "Sleek Fresh Chicken",
                            AudioUrl = "https://lavina.biz/implement/gold/vermont",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            CoverUrl = "http://elisabeth.name/pci",
                            Duration = new TimeSpan(0, 0, 3, 10, 0),
                            Status = "Pending",
                            Title = "Try to index"
                        },
                        new
                        {
                            Id = new Guid("bcffc41e-3977-cf89-ce7d-cd5cfee45573"),
                            Album = "Unbranded Concrete Pizza",
                            AudioUrl = "http://stefanie.net/russian-ruble",
                            AuthorId = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            CoverUrl = "https://roger.org/killer/small",
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Status = "Rejected",
                            Title = "Use the 1080p"
                        },
                        new
                        {
                            Id = new Guid("4128ea39-94d8-dd68-6537-f86fc9aaad8c"),
                            Album = "Fantastic Rubber Pants",
                            AudioUrl = "https://maxine.org/home-loan-account/scsi",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            CoverUrl = "https://juston.biz/backing-up/producer/home-loan-a",
                            Duration = new TimeSpan(0, 0, 3, 24, 0),
                            Status = "Rejected",
                            Title = "bypassing the firewall"
                        },
                        new
                        {
                            Id = new Guid("bd75b3bf-7b9e-6f85-b002-699888630d34"),
                            Album = "Gorgeous Cotton Pants",
                            AudioUrl = "http://marian.info/cambridgeshire/invoice/multi-ch",
                            AuthorId = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            CoverUrl = "http://vaughn.name/web-enabled/back-end/synergized",
                            Duration = new TimeSpan(0, 0, 3, 6, 0),
                            Status = "Approved",
                            Title = "Use the 1080p"
                        },
                        new
                        {
                            Id = new Guid("5a3f02b3-6fa3-e7d8-43f3-7c7f9b61bea3"),
                            Album = "Awesome Fresh Pizza",
                            AudioUrl = "https://una.com/holy-see-vatican-city-state/fantas",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "http://selmer.name/tonga/singapore-dollar",
                            Duration = new TimeSpan(0, 0, 3, 23, 0),
                            Status = "Rejected",
                            Title = "Try to connect"
                        },
                        new
                        {
                            Id = new Guid("15399ce7-2363-7a4e-8cf7-731e37254e0c"),
                            Album = "Sleek Cotton Soap",
                            AudioUrl = "https://carter.org/transmit/namibia-dollar",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "https://orie.com/navigating/licensed/algerian-dina",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Status = "Approved",
                            Title = "Use the digital"
                        },
                        new
                        {
                            Id = new Guid("837f88a2-0196-46ea-4bd8-c7e582efce6d"),
                            Album = "Rustic Fresh Fish",
                            AudioUrl = "http://zion.biz/granite/international",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            CoverUrl = "http://rodrigo.biz/generic-metal-cheese",
                            Duration = new TimeSpan(0, 0, 2, 35, 0),
                            Status = "Approved",
                            Title = "You can't calculate"
                        },
                        new
                        {
                            Id = new Guid("3c271834-2606-4225-3838-61662f2c740a"),
                            Album = "Unbranded Steel Sausages",
                            AudioUrl = "http://asha.org/payment/alabama/park",
                            AuthorId = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            CoverUrl = "https://malika.info/forks",
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Status = "Pending",
                            Title = "connecting the sensor"
                        },
                        new
                        {
                            Id = new Guid("349c6b37-0ab2-5115-1c5d-086b513e1e03"),
                            Album = "Handmade Metal Chair",
                            AudioUrl = "http://reynold.net/kenyan-shilling/synthesizing",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "http://emery.name/beauty-sports--jewelery/tennesse",
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Status = "Pending",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("3358e3a5-20d5-922f-d326-336359c0f6e0"),
                            Album = "Incredible Granite Fish",
                            AudioUrl = "http://gardner.biz/functionality/wall/function",
                            AuthorId = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            CoverUrl = "https://vilma.info/inverse/magnetic/hacking",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Status = "Pending",
                            Title = "Try to parse"
                        },
                        new
                        {
                            Id = new Guid("48964e47-9933-07f9-a0d4-7b177c65e966"),
                            Album = "Generic Rubber Soap",
                            AudioUrl = "https://zelma.com/concrete/accounts/superstructure",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "http://carlos.com/corner/fault-tolerant/deposit",
                            Duration = new TimeSpan(0, 0, 2, 36, 0),
                            Status = "Rejected",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("69e52b37-d679-928b-92dc-0a828fadfc0f"),
                            Album = "Handmade Wooden Pants",
                            AudioUrl = "https://chaya.biz/system/high-level/portals",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "https://marcella.com/scale/liaison",
                            Duration = new TimeSpan(0, 0, 3, 10, 0),
                            Status = "Rejected",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("92e6b058-723d-0ae4-39a7-9b2db67e329a"),
                            Album = "Handmade Cotton Ball",
                            AudioUrl = "https://ardella.com/plain",
                            AuthorId = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            CoverUrl = "http://miracle.info/buckinghamshire/grocery--healt",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Status = "Pending",
                            Title = "I'll input the"
                        },
                        new
                        {
                            Id = new Guid("63a17d43-1cdc-a170-4425-0db718c92d81"),
                            Album = "Handcrafted Metal Shoes",
                            AudioUrl = "http://martina.info/buckinghamshire/models",
                            AuthorId = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            CoverUrl = "https://laurence.biz/application/sky-blue/circles",
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Status = "Pending",
                            Title = "Use the open-source"
                        },
                        new
                        {
                            Id = new Guid("ae5241da-807e-6cd9-8d3f-ff7a859c8d70"),
                            Album = "Ergonomic Steel Shoes",
                            AudioUrl = "http://jalon.net/mobility/avon/incentivize",
                            AuthorId = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            CoverUrl = "http://elton.info/sms",
                            Duration = new TimeSpan(0, 0, 2, 41, 0),
                            Status = "Approved",
                            Title = "Try to index"
                        },
                        new
                        {
                            Id = new Guid("a753a0e7-11d7-0e7a-0329-21ee510b4723"),
                            Album = "Small Metal Table",
                            AudioUrl = "http://laverna.org/redundant",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            CoverUrl = "https://kade.name/intelligent-frozen-cheese/gorgeo",
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Status = "Rejected",
                            Title = "Use the primary"
                        },
                        new
                        {
                            Id = new Guid("a1fc76d1-5e00-241c-dbca-0bdacac16f97"),
                            Album = "Fantastic Fresh Hat",
                            AudioUrl = "https://javonte.info/invoice/summit/plastic",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            CoverUrl = "http://michaela.org/way/universal/integrate",
                            Duration = new TimeSpan(0, 0, 2, 33, 0),
                            Status = "Rejected",
                            Title = "The SAS program"
                        },
                        new
                        {
                            Id = new Guid("2765b367-5555-f7ce-d601-f57e43f2b8e7"),
                            Album = "Licensed Frozen Bike",
                            AudioUrl = "http://paolo.name/virtual",
                            AuthorId = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            CoverUrl = "http://jaylin.info/accounts",
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Status = "Approved",
                            Title = "Try to connect"
                        },
                        new
                        {
                            Id = new Guid("43e9c98c-e32c-5a1f-a084-4c2cc88d46b8"),
                            Album = "Unbranded Concrete Tuna",
                            AudioUrl = "http://rhett.name/avon/refined-fresh-soap",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "https://emanuel.biz/automotive--industrial/front-l",
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Status = "Approved",
                            Title = "If we compress"
                        },
                        new
                        {
                            Id = new Guid("5356098d-2bfb-11be-4130-f15deaaf2a9f"),
                            Album = "Licensed Metal Hat",
                            AudioUrl = "http://elisabeth.biz/kids--garden/uganda-shilling/",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            CoverUrl = "https://adolph.biz/solomon-islands-dollar/cyan",
                            Duration = new TimeSpan(0, 0, 2, 47, 0),
                            Status = "Pending",
                            Title = "I'll synthesize the"
                        },
                        new
                        {
                            Id = new Guid("4cc014c7-8ae0-7d4d-1605-175b8aa849a5"),
                            Album = "Generic Metal Chicken",
                            AudioUrl = "https://jimmy.com/cambridgeshire",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            CoverUrl = "http://troy.info/licensed",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Status = "Pending",
                            Title = "If we connect"
                        },
                        new
                        {
                            Id = new Guid("a51063b3-72ee-8ed2-8750-4cfab6fd4dc4"),
                            Album = "Sleek Frozen Mouse",
                            AudioUrl = "http://rick.info/handcrafted/bypassing/supervisor",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            CoverUrl = "http://maximo.org/prairie",
                            Duration = new TimeSpan(0, 0, 2, 35, 0),
                            Status = "Approved",
                            Title = "Use the auxiliary"
                        },
                        new
                        {
                            Id = new Guid("bbe43911-8a37-4194-0554-fa3f0057d472"),
                            Album = "Awesome Metal Shirt",
                            AudioUrl = "http://bethel.org/incredible/hub",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "http://troy.org/dynamic/avon/glens",
                            Duration = new TimeSpan(0, 0, 3, 10, 0),
                            Status = "Approved",
                            Title = "I'll input the"
                        },
                        new
                        {
                            Id = new Guid("c57b9c69-a674-61d8-4370-7330f453bac3"),
                            Album = "Rustic Plastic Shirt",
                            AudioUrl = "https://lawson.net/small",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            CoverUrl = "http://ashlee.com/emulation/impactful/wells",
                            Duration = new TimeSpan(0, 0, 2, 46, 0),
                            Status = "Approved",
                            Title = "You can't copy"
                        },
                        new
                        {
                            Id = new Guid("7af26624-3d13-f1a8-b4ee-d702ed3ee98b"),
                            Album = "Incredible Wooden Table",
                            AudioUrl = "http://jayda.biz/producer/florida",
                            AuthorId = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            CoverUrl = "http://xzavier.info/oval/loop",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Status = "Approved",
                            Title = "If we override"
                        },
                        new
                        {
                            Id = new Guid("164778f9-51b3-97d8-4d12-c194e3cfa18d"),
                            Album = "Licensed Soft Table",
                            AudioUrl = "https://marlee.name/terrace/assurance",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "https://stefanie.net/interactions",
                            Duration = new TimeSpan(0, 0, 3, 24, 0),
                            Status = "Approved",
                            Title = "If we hack"
                        },
                        new
                        {
                            Id = new Guid("83b5fe12-2791-c5e2-e3ee-ef27e28287d1"),
                            Album = "Small Concrete Computer",
                            AudioUrl = "http://martina.net/css",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "http://ali.com/sensor",
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Status = "Rejected",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("fcdb5742-367d-a7e2-d96d-674eca1e0083"),
                            Album = "Handmade Wooden Hat",
                            AudioUrl = "http://alycia.org/invoice/rustic-granite-table/fro",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "http://connie.info/handcrafted",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Status = "Pending",
                            Title = "Try to compress"
                        },
                        new
                        {
                            Id = new Guid("e16117c7-5f1b-7155-ec9f-e16fe9204462"),
                            Album = "Unbranded Concrete Car",
                            AudioUrl = "http://kailee.net/benchmark",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            CoverUrl = "http://henri.net/monitor",
                            Duration = new TimeSpan(0, 0, 2, 51, 0),
                            Status = "Pending",
                            Title = "Use the multi-byte"
                        },
                        new
                        {
                            Id = new Guid("d261e8f7-4440-b740-bad9-752184f4994b"),
                            Album = "Intelligent Fresh Pizza",
                            AudioUrl = "http://bethel.biz/json",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "https://unique.name/metal/dot-com",
                            Duration = new TimeSpan(0, 0, 3, 8, 0),
                            Status = "Pending",
                            Title = "Use the digital"
                        },
                        new
                        {
                            Id = new Guid("1a0d5d93-6710-49ec-6f9c-2b0bd9efadf8"),
                            Album = "Small Frozen Sausages",
                            AudioUrl = "http://chris.info/optimize/white/local",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            CoverUrl = "https://jazmyn.org/reboot/trail/reboot",
                            Duration = new TimeSpan(0, 0, 3, 20, 0),
                            Status = "Approved",
                            Title = "Use the online"
                        },
                        new
                        {
                            Id = new Guid("aa6a225c-8f5a-42a5-c7e5-c437955d17dd"),
                            Album = "Handcrafted Granite Pizza",
                            AudioUrl = "http://jade.org/corporate/granite",
                            AuthorId = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            CoverUrl = "https://yvonne.org/fresh",
                            Duration = new TimeSpan(0, 0, 3, 18, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("02847616-1815-1d2b-ee7b-b4ffb78d8645"),
                            Album = "Fantastic Granite Tuna",
                            AudioUrl = "https://dejon.info/paradigm/open-source",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "http://dayana.info/tunnel/tennessee/concept",
                            Duration = new TimeSpan(0, 0, 3, 11, 0),
                            Status = "Pending",
                            Title = "You can't program"
                        },
                        new
                        {
                            Id = new Guid("e188a4e6-5648-a349-443b-9755d21ded22"),
                            Album = "Ergonomic Fresh Chips",
                            AudioUrl = "https://kale.net/monitor/initiatives",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            CoverUrl = "http://alan.org/gorgeous-fresh-pants",
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Status = "Rejected",
                            Title = "The AI protocol"
                        },
                        new
                        {
                            Id = new Guid("53e44b8d-9a60-90d0-89c5-7b79d0263d0e"),
                            Album = "Handcrafted Soft Bacon",
                            AudioUrl = "https://betty.name/green/canyon",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            CoverUrl = "http://angel.biz/director",
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Status = "Approved",
                            Title = "Use the open-source"
                        },
                        new
                        {
                            Id = new Guid("97ad87cb-59b6-2896-2fe0-29761f4b433a"),
                            Album = "Generic Steel Table",
                            AudioUrl = "http://jorge.net/integration/digital",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "http://elise.biz/capacity/e-enable/branding",
                            Duration = new TimeSpan(0, 0, 2, 33, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("1a148937-7fc7-a76c-f21e-90f1863c07b0"),
                            Album = "Incredible Cotton Hat",
                            AudioUrl = "https://emmie.net/licensed",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            CoverUrl = "http://christelle.name/maximized/auto-loan-account",
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Status = "Approved",
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("72ee0af0-4b41-629e-01aa-262ab552dbf5"),
                            Album = "Handmade Plastic Bike",
                            AudioUrl = "http://kendra.com/avon",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "http://susan.info/quality/rustic/senior",
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Status = "Pending",
                            Title = "Use the digital"
                        },
                        new
                        {
                            Id = new Guid("7e1318f9-2ac4-1440-9d78-3b6a40887902"),
                            Album = "Practical Plastic Soap",
                            AudioUrl = "https://lesley.com/bandwidth/rubber",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            CoverUrl = "https://myrl.name/idaho/granite",
                            Duration = new TimeSpan(0, 0, 2, 30, 0),
                            Status = "Approved",
                            Title = "The XML port"
                        },
                        new
                        {
                            Id = new Guid("5af36740-6b5e-dd88-657c-e998dbdafd1c"),
                            Album = "Refined Cotton Hat",
                            AudioUrl = "https://quentin.name/cultivate/open-source",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            CoverUrl = "https://damon.net/distributed",
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Status = "Approved",
                            Title = "If we connect"
                        },
                        new
                        {
                            Id = new Guid("d464011a-5105-ef64-e851-3efff6857a02"),
                            Album = "Incredible Plastic Ball",
                            AudioUrl = "http://marcellus.biz/interface",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "https://evalyn.info/schemas/cedi/cotton",
                            Duration = new TimeSpan(0, 0, 3, 1, 0),
                            Status = "Rejected",
                            Title = "I'll quantify the"
                        },
                        new
                        {
                            Id = new Guid("73d2374f-b29e-3878-4f6b-03ecda0971f2"),
                            Album = "Practical Soft Sausages",
                            AudioUrl = "https://danielle.com/gorgeous-concrete-pizza/cotto",
                            AuthorId = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            CoverUrl = "https://haylie.com/hard-drive",
                            Duration = new TimeSpan(0, 0, 2, 59, 0),
                            Status = "Approved",
                            Title = "I'll override the"
                        },
                        new
                        {
                            Id = new Guid("8311b45e-a1d5-2415-4ec7-99f1763d8f0f"),
                            Album = "Incredible Plastic Cheese",
                            AudioUrl = "http://winfield.info/monitor/drive",
                            AuthorId = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            CoverUrl = "http://karli.org/override",
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Status = "Rejected",
                            Title = "The SDD firewall"
                        },
                        new
                        {
                            Id = new Guid("1a8716f5-02b4-35df-7866-a550419ea657"),
                            Album = "Tasty Fresh Table",
                            AudioUrl = "http://kaleb.name/sleek-soft-mouse",
                            AuthorId = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            CoverUrl = "https://philip.org/new-mexico/frozen",
                            Duration = new TimeSpan(0, 0, 2, 40, 0),
                            Status = "Rejected",
                            Title = "Use the auxiliary"
                        },
                        new
                        {
                            Id = new Guid("97ab7c18-2688-936c-a0e6-cc79efabf52a"),
                            Album = "Fantastic Plastic Mouse",
                            AudioUrl = "https://buddy.name/cape/re-contextualized/bedfords",
                            AuthorId = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            CoverUrl = "https://eudora.com/palladium/bypassing",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Status = "Pending",
                            Title = "Try to connect"
                        },
                        new
                        {
                            Id = new Guid("67ed8507-a3b4-2a60-31ea-7144c2d9ffca"),
                            Album = "Rustic Rubber Table",
                            AudioUrl = "http://johanna.com/portugal/backing-up/algorithm",
                            AuthorId = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            CoverUrl = "https://wava.biz/points",
                            Duration = new TimeSpan(0, 0, 2, 43, 0),
                            Status = "Pending",
                            Title = "Try to generate"
                        },
                        new
                        {
                            Id = new Guid("fead9936-136b-7633-6b27-fa059da01a28"),
                            Album = "Practical Plastic Ball",
                            AudioUrl = "https://zakary.org/automotive/automotive/extensibl",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "https://ursula.com/dynamic/wisconsin",
                            Duration = new TimeSpan(0, 0, 3, 13, 0),
                            Status = "Rejected",
                            Title = "You can't program"
                        },
                        new
                        {
                            Id = new Guid("5a51617a-c61e-6e44-ac6f-cb0cfc319fc4"),
                            Album = "Gorgeous Cotton Chair",
                            AudioUrl = "http://ernie.info/bleeding-edge",
                            AuthorId = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            CoverUrl = "http://madelyn.com/portals/executive/intelligent-g",
                            Duration = new TimeSpan(0, 0, 2, 50, 0),
                            Status = "Approved",
                            Title = "You can't bypass"
                        },
                        new
                        {
                            Id = new Guid("7a40d741-ed6c-74e3-8a12-17fdfd82d98f"),
                            Album = "Practical Soft Gloves",
                            AudioUrl = "https://edyth.name/representative/generating/effic",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "http://ulices.biz/usb",
                            Duration = new TimeSpan(0, 0, 2, 34, 0),
                            Status = "Rejected",
                            Title = "I'll index the"
                        },
                        new
                        {
                            Id = new Guid("bb0b585d-3ba7-17c4-b1a1-0f472c160bb2"),
                            Album = "Sleek Concrete Salad",
                            AudioUrl = "https://ignatius.info/handcrafted-concrete-keyboar",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            CoverUrl = "https://raymundo.com/global/iterate/cyan",
                            Duration = new TimeSpan(0, 0, 3, 14, 0),
                            Status = "Approved",
                            Title = "The RAM alarm"
                        },
                        new
                        {
                            Id = new Guid("cd370536-22c4-abd0-94e3-20ee79b81247"),
                            Album = "Handmade Soft Salad",
                            AudioUrl = "https://van.net/tasty-soft-sausages/haptic",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            CoverUrl = "http://rick.biz/interactive/views/guyana-dollar",
                            Duration = new TimeSpan(0, 0, 2, 53, 0),
                            Status = "Rejected",
                            Title = "You can't override"
                        },
                        new
                        {
                            Id = new Guid("f14d46c2-0d12-4a9b-f30f-3e5e101ed881"),
                            Album = "Awesome Metal Bacon",
                            AudioUrl = "https://krystel.org/jersey/avon",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "http://ima.info/delaware",
                            Duration = new TimeSpan(0, 0, 2, 41, 0),
                            Status = "Rejected",
                            Title = "Try to compress"
                        },
                        new
                        {
                            Id = new Guid("13758096-2798-8c2a-ab04-12577b3a903a"),
                            Album = "Intelligent Cotton Pants",
                            AudioUrl = "https://kip.biz/purple/cambridgeshire/morph",
                            AuthorId = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            CoverUrl = "https://deonte.net/alarm/plaza/networks",
                            Duration = new TimeSpan(0, 0, 2, 37, 0),
                            Status = "Approved",
                            Title = "synthesizing the array"
                        },
                        new
                        {
                            Id = new Guid("387e8afa-c868-0209-3097-4927f9ddd08d"),
                            Album = "Sleek Steel Tuna",
                            AudioUrl = "http://hilton.net/withdrawal/bypassing/buckinghams",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "http://earlene.biz/summit/district/virtual",
                            Duration = new TimeSpan(0, 0, 2, 51, 0),
                            Status = "Approved",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("916f267e-26fb-9f6c-ed85-d09301ea229b"),
                            Album = "Rustic Cotton Computer",
                            AudioUrl = "http://easton.org/books",
                            AuthorId = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            CoverUrl = "http://bryon.info/soft/solutions/solution-oriented",
                            Duration = new TimeSpan(0, 0, 3, 8, 0),
                            Status = "Rejected",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("cc8a4b59-fc69-076b-0e6d-df37a5c2059d"),
                            Album = "Gorgeous Fresh Soap",
                            AudioUrl = "https://lynn.biz/east-caribbean-dollar/infrastruct",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            CoverUrl = "https://elta.com/web-enabled/anguilla/deposit",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Status = "Rejected",
                            Title = "The IB feed"
                        },
                        new
                        {
                            Id = new Guid("898b3a80-69f8-64ef-680b-1a3f63f3ef3e"),
                            Album = "Sleek Steel Bike",
                            AudioUrl = "https://tyreek.net/philippine-peso",
                            AuthorId = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            CoverUrl = "https://lauriane.org/garden/consultant/bypassing",
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Status = "Pending",
                            Title = "The COM pixel"
                        },
                        new
                        {
                            Id = new Guid("acf829be-2b25-cb9d-3b20-f4ec2fea700c"),
                            Album = "Intelligent Frozen Salad",
                            AudioUrl = "http://randal.net/deploy/principal/buckinghamshire",
                            AuthorId = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            CoverUrl = "http://rosanna.com/compress",
                            Duration = new TimeSpan(0, 0, 3, 9, 0),
                            Status = "Rejected",
                            Title = "I'll input the"
                        },
                        new
                        {
                            Id = new Guid("3e72e500-600b-5e36-1276-430aaef98e88"),
                            Album = "Intelligent Cotton Keyboard",
                            AudioUrl = "https://karson.biz/georgia/orchid/investment-accou",
                            AuthorId = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            CoverUrl = "http://zula.com/garden-beauty--jewelery",
                            Duration = new TimeSpan(0, 0, 3, 4, 0),
                            Status = "Approved",
                            Title = "hacking the program"
                        },
                        new
                        {
                            Id = new Guid("9da27e6b-63f9-972b-e5dc-0f34f8b90d75"),
                            Album = "Generic Wooden Tuna",
                            AudioUrl = "https://beryl.biz/deposit/practical/designer",
                            AuthorId = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            CoverUrl = "https://micaela.info/tan/invoice/cross-platform",
                            Duration = new TimeSpan(0, 0, 3, 29, 0),
                            Status = "Rejected",
                            Title = "I'll transmit the"
                        },
                        new
                        {
                            Id = new Guid("6fb71bd5-318c-70b4-2945-8a8a8cebf891"),
                            Album = "Awesome Concrete Chair",
                            AudioUrl = "https://vergie.biz/engineer/cambridgeshire/gorgeou",
                            AuthorId = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            CoverUrl = "https://eli.org/investment-account",
                            Duration = new TimeSpan(0, 0, 3, 26, 0),
                            Status = "Pending",
                            Title = "If we bypass"
                        },
                        new
                        {
                            Id = new Guid("4e58f4d9-8722-e51c-b883-9472ec0cf175"),
                            Album = "Practical Fresh Table",
                            AudioUrl = "http://hazel.org/personal-loan-account/bedfordshir",
                            AuthorId = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            CoverUrl = "https://rosanna.com/program",
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Status = "Approved",
                            Title = "The TCP alarm"
                        },
                        new
                        {
                            Id = new Guid("d73a8e96-d83b-503d-fda9-c192cfad9108"),
                            Album = "Gorgeous Rubber Pizza",
                            AudioUrl = "https://reta.com/computers--kids",
                            AuthorId = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            CoverUrl = "http://raphaelle.info/swiss-franc/fuchsia/gorgeous",
                            Duration = new TimeSpan(0, 0, 2, 38, 0),
                            Status = "Rejected",
                            Title = "backing up the"
                        },
                        new
                        {
                            Id = new Guid("e760d4c7-4d37-d969-53d1-2191be06fd55"),
                            Album = "Generic Metal Computer",
                            AudioUrl = "https://eulalia.info/parsing/paradigms",
                            AuthorId = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            CoverUrl = "http://brando.info/iterate/tonga",
                            Duration = new TimeSpan(0, 0, 3, 22, 0),
                            Status = "Pending",
                            Title = "overriding the capacitor"
                        },
                        new
                        {
                            Id = new Guid("6c4f30f0-db93-660e-2e04-409ea576efa8"),
                            Album = "Handcrafted Wooden Hat",
                            AudioUrl = "http://idella.name/handcrafted/soft/orchestrator",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "https://nikko.info/project/tanzania",
                            Duration = new TimeSpan(0, 0, 3, 2, 0),
                            Status = "Rejected",
                            Title = "We need to"
                        },
                        new
                        {
                            Id = new Guid("80b8d0d8-b168-d3b9-d658-fb9cd313cc9c"),
                            Album = "Practical Soft Chicken",
                            AudioUrl = "https://lessie.com/identity/uic-franc",
                            AuthorId = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            CoverUrl = "https://annette.info/reduced/direct/sdd",
                            Duration = new TimeSpan(0, 0, 3, 15, 0),
                            Status = "Pending",
                            Title = "You can't navigate"
                        },
                        new
                        {
                            Id = new Guid("67e55730-e50c-5181-4659-53901790b11f"),
                            Album = "Handmade Soft Pants",
                            AudioUrl = "https://della.com/future-proofed/maine/hardware",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "http://mayra.net/group/incredible-wooden-chair/vir",
                            Duration = new TimeSpan(0, 0, 3, 7, 0),
                            Status = "Pending",
                            Title = "I'll hack the"
                        },
                        new
                        {
                            Id = new Guid("ab8670a9-25ef-56ea-8497-bf26e6fe2977"),
                            Album = "Sleek Frozen Salad",
                            AudioUrl = "https://samanta.net/cambridgeshire/personal-loan-a",
                            AuthorId = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            CoverUrl = "http://demarco.net/borders",
                            Duration = new TimeSpan(0, 0, 2, 31, 0),
                            Status = "Pending",
                            Title = "Use the online"
                        },
                        new
                        {
                            Id = new Guid("732483b1-4ef3-c1d7-83e5-7bc4e5d39ccc"),
                            Album = "Unbranded Plastic Shirt",
                            AudioUrl = "http://lorna.com/texas/flats",
                            AuthorId = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            CoverUrl = "http://okey.net/wooden",
                            Duration = new TimeSpan(0, 0, 2, 58, 0),
                            Status = "Pending",
                            Title = "If we compress"
                        },
                        new
                        {
                            Id = new Guid("9043baf9-02cb-f1e5-ac85-8f3e9c4725ba"),
                            Album = "Awesome Metal Soap",
                            AudioUrl = "http://justina.biz/accountability/greens",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "http://santos.biz/tools--music/rustic-plastic-pizz",
                            Duration = new TimeSpan(0, 0, 2, 48, 0),
                            Status = "Pending",
                            Title = "I'll back up"
                        },
                        new
                        {
                            Id = new Guid("81581db2-6849-78f5-9a4d-1f2b834f73d3"),
                            Album = "Handmade Steel Fish",
                            AudioUrl = "https://fatima.org/congolese-franc/arkansas",
                            AuthorId = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            CoverUrl = "http://gregg.info/channels",
                            Duration = new TimeSpan(0, 0, 3, 8, 0),
                            Status = "Pending",
                            Title = "The GB feed"
                        },
                        new
                        {
                            Id = new Guid("333a33e0-c26b-2276-4b5f-ac1d9f5a2e3c"),
                            Album = "Intelligent Cotton Chair",
                            AudioUrl = "http://arvid.com/mountains/optical/electronics--he",
                            AuthorId = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            CoverUrl = "http://raheem.org/incredible/feed",
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Status = "Rejected",
                            Title = "Try to reboot"
                        },
                        new
                        {
                            Id = new Guid("9386347e-571e-8b24-9dad-a993ffafbe62"),
                            Album = "Handcrafted Concrete Chicken",
                            AudioUrl = "https://callie.net/awesome-frozen-bike",
                            AuthorId = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            CoverUrl = "http://janice.biz/savings-account",
                            Duration = new TimeSpan(0, 0, 3, 12, 0),
                            Status = "Pending",
                            Title = "If we synthesize"
                        },
                        new
                        {
                            Id = new Guid("823b341f-8b07-967b-1c0d-8be4500dd903"),
                            Album = "Incredible Cotton Tuna",
                            AudioUrl = "http://kelly.net/synergized/virtual/texas",
                            AuthorId = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            CoverUrl = "https://erika.org/capacity",
                            Duration = new TimeSpan(0, 0, 3, 19, 0),
                            Status = "Pending",
                            Title = "I'll connect the"
                        },
                        new
                        {
                            Id = new Guid("3a3fe77a-5d55-31af-7f10-bdc02e98ba98"),
                            Album = "Generic Steel Chips",
                            AudioUrl = "http://rhea.net/road/programmable/antarctica-the-t",
                            AuthorId = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            CoverUrl = "https://ibrahim.net/e-tailers/san-marino",
                            Duration = new TimeSpan(0, 0, 3, 28, 0),
                            Status = "Approved",
                            Title = "The HDD array"
                        },
                        new
                        {
                            Id = new Guid("fa74aff7-7a59-af2e-ad17-d8e37fa2a1fc"),
                            Album = "Unbranded Frozen Pants",
                            AudioUrl = "http://lamont.info/generic-fresh-mouse",
                            AuthorId = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            CoverUrl = "http://valentina.org/human-resource",
                            Duration = new TimeSpan(0, 0, 2, 42, 0),
                            Status = "Pending",
                            Title = "I'll transmit the"
                        });
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49bb0990-7c20-0dcf-fce5-3793219f6047"),
                            Age = 19,
                            EmailAddress = "Sabina.Marvin26@gmail.com",
                            ExternalId = "auth0|d8b0d2646f930a379fe684d8",
                            Gender = "Female",
                            Name = "Marianne"
                        },
                        new
                        {
                            Id = new Guid("fa333e3f-3b75-cd02-7ce7-2b77e1e700a2"),
                            Age = 99,
                            EmailAddress = "Jeanette.Bartoletti@hotmail.com",
                            ExternalId = "auth0|d8d5248b2594d52b85cd5352",
                            Gender = "Female",
                            Name = "Joanie"
                        },
                        new
                        {
                            Id = new Guid("1c8575f0-6194-339d-ad3e-2e7c3866a80f"),
                            Age = 94,
                            EmailAddress = "Larue46@hotmail.com",
                            ExternalId = "auth0|1b95a2b93ad5c83c5c75374d",
                            Gender = "Male",
                            Name = "Marley"
                        },
                        new
                        {
                            Id = new Guid("b471b00d-f7ee-acf9-e226-1fd24d76e93c"),
                            Age = 41,
                            EmailAddress = "Kacie.Renner92@hotmail.com",
                            ExternalId = "auth0|e486a6697cad876bc62f970b",
                            Gender = "Female",
                            Name = "Louie"
                        },
                        new
                        {
                            Id = new Guid("a8c435d2-a3ab-8813-de0e-ac5fab782189"),
                            Age = 44,
                            EmailAddress = "Darron70@yahoo.com",
                            ExternalId = "auth0|c0734263ccfdaafd54b28c4a",
                            Gender = "Female",
                            Name = "Greyson"
                        },
                        new
                        {
                            Id = new Guid("3a4637ab-0383-947a-860b-598de7e62046"),
                            Age = 88,
                            EmailAddress = "Clotilde_Swaniawski@gmail.com",
                            ExternalId = "auth0|52a0838fcdcce32176a06863",
                            Gender = "Male",
                            Name = "Vernice"
                        },
                        new
                        {
                            Id = new Guid("0e51d9f0-3e16-1570-8751-8bfcad3c76b7"),
                            Age = 50,
                            EmailAddress = "Thaddeus_Doyle90@yahoo.com",
                            ExternalId = "auth0|71464b4db7170a63f5f66302",
                            Gender = "Male",
                            Name = "Guadalupe"
                        },
                        new
                        {
                            Id = new Guid("d922e44d-ba77-e400-0a2a-26212685a3c3"),
                            Age = 90,
                            EmailAddress = "Ines_Balistreri@gmail.com",
                            ExternalId = "auth0|7af854402fac00e8a384ef82",
                            Gender = "Female",
                            Name = "Tressa"
                        },
                        new
                        {
                            Id = new Guid("062f3c05-dd11-1323-10db-7e8ac0b8ef7e"),
                            Age = 73,
                            EmailAddress = "Cesar.Kertzmann58@gmail.com",
                            ExternalId = "auth0|409472f82d94d3841f5bacac",
                            Gender = "Female",
                            Name = "Ephraim"
                        },
                        new
                        {
                            Id = new Guid("8717fef3-a26b-e361-ca4b-173b514b256b"),
                            Age = 74,
                            EmailAddress = "Norbert_Schroeder@gmail.com",
                            ExternalId = "auth0|e58f8575cf3f8b24e6571f8d",
                            Gender = "Female",
                            Name = "William"
                        },
                        new
                        {
                            Id = new Guid("1e2c23c9-1e0f-d13a-4cac-27078dac190f"),
                            Age = 91,
                            EmailAddress = "Delia_Weissnat@gmail.com",
                            ExternalId = "auth0|dc5306dedbf39ac445bfd733",
                            Gender = "Female",
                            Name = "Bridget"
                        },
                        new
                        {
                            Id = new Guid("65ff82bb-8d09-8e6c-0f2b-c4d489d94086"),
                            Age = 52,
                            EmailAddress = "Domenick_Steuber@hotmail.com",
                            ExternalId = "auth0|535aae56811c2e6ed5cfb00c",
                            Gender = "Male",
                            Name = "Jada"
                        },
                        new
                        {
                            Id = new Guid("552d18c2-86b9-4773-0253-becbc4f9f3a7"),
                            Age = 49,
                            EmailAddress = "Manley_Cronin40@gmail.com",
                            ExternalId = "auth0|8e7649d4282d97b9af274259",
                            Gender = "Male",
                            Name = "Gerhard"
                        },
                        new
                        {
                            Id = new Guid("de35e4ee-1a3c-5790-7777-f1ec1069e422"),
                            Age = 38,
                            EmailAddress = "Stephen48@yahoo.com",
                            ExternalId = "auth0|966e3969e00ea631cb22f2a2",
                            Gender = "Male",
                            Name = "Arne"
                        },
                        new
                        {
                            Id = new Guid("62974f26-824a-80f7-bdb5-31fe456909ca"),
                            Age = 43,
                            EmailAddress = "Daniella_Senger@gmail.com",
                            ExternalId = "auth0|ff55cad7b4daa656cc153a24",
                            Gender = "Female",
                            Name = "Shirley"
                        },
                        new
                        {
                            Id = new Guid("17f3f721-c6c8-7b79-2791-0c615bb1d678"),
                            Age = 73,
                            EmailAddress = "Sammie.Kilback58@hotmail.com",
                            ExternalId = "auth0|c2300db4d17770e0fd3b514d",
                            Gender = "Male",
                            Name = "Elisa"
                        },
                        new
                        {
                            Id = new Guid("ffd23d02-4eb5-4217-2b43-f9b46c4a45c7"),
                            Age = 43,
                            EmailAddress = "Leslie44@yahoo.com",
                            ExternalId = "auth0|bccf82be5b1f4667c6b098af",
                            Gender = "Male",
                            Name = "Marcia"
                        },
                        new
                        {
                            Id = new Guid("f4c5bb92-c504-dc74-c969-fbb76ae50f7e"),
                            Age = 28,
                            EmailAddress = "Miller.Carter@gmail.com",
                            ExternalId = "auth0|0998f7431d4181ce6e9a5bb1",
                            Gender = "Male",
                            Name = "Rhoda"
                        },
                        new
                        {
                            Id = new Guid("eb5aa860-01f1-f11d-eb28-7b3747c1dca7"),
                            Age = 75,
                            EmailAddress = "Elmer76@yahoo.com",
                            ExternalId = "auth0|a41e05f4e8bbb2dfa3a3731a",
                            Gender = "Male",
                            Name = "Lester"
                        },
                        new
                        {
                            Id = new Guid("e1863474-f4ae-c7e2-12bb-a8f909512da9"),
                            Age = 65,
                            EmailAddress = "Timmy_Considine@yahoo.com",
                            ExternalId = "auth0|1932dbc737460922d683bbf7",
                            Gender = "Male",
                            Name = "Brennon"
                        },
                        new
                        {
                            Id = new Guid("7775e280-c280-eecf-54f4-31fbbf49b93b"),
                            Age = 53,
                            EmailAddress = "Jett.Robel53@gmail.com",
                            ExternalId = "auth0|287a0086ac05cae7e30e4994",
                            Gender = "Male",
                            Name = "Sterling"
                        },
                        new
                        {
                            Id = new Guid("7fc71309-41a9-f4e3-287b-8345ecad8131"),
                            Age = 42,
                            EmailAddress = "Halle_Pfannerstill73@gmail.com",
                            ExternalId = "auth0|7aba268e3c08c9249e9ad2f2",
                            Gender = "Male",
                            Name = "Maryam"
                        },
                        new
                        {
                            Id = new Guid("9c2b1595-45f8-672e-e24d-46b081cda8ed"),
                            Age = 58,
                            EmailAddress = "Mariano.Braun85@gmail.com",
                            ExternalId = "auth0|7e41734a9fdfdf60a11356ca",
                            Gender = "Male",
                            Name = "Pearline"
                        },
                        new
                        {
                            Id = new Guid("2349b3e1-f845-5b61-fa8e-fbef8c8a9b57"),
                            Age = 67,
                            EmailAddress = "Corine.Cormier98@gmail.com",
                            ExternalId = "auth0|26bc1501a4483e815ee97872",
                            Gender = "Female",
                            Name = "Lelah"
                        },
                        new
                        {
                            Id = new Guid("d82de857-522c-c556-b013-d78f474f9287"),
                            Age = 72,
                            EmailAddress = "Letha_Ratke@gmail.com",
                            ExternalId = "auth0|c1ea939e82e2e265a0c4df9e",
                            Gender = "Male",
                            Name = "Ernie"
                        },
                        new
                        {
                            Id = new Guid("d9ace6d5-3d01-ab77-48e3-ab1f26334575"),
                            Age = 86,
                            EmailAddress = "Elizabeth_Braun@yahoo.com",
                            ExternalId = "auth0|69fe1fec7f569e507938043b",
                            Gender = "Female",
                            Name = "Brenda"
                        },
                        new
                        {
                            Id = new Guid("d14d8488-392a-c224-376c-9545523ef9d7"),
                            Age = 28,
                            EmailAddress = "Amelie.Pollich@gmail.com",
                            ExternalId = "auth0|59183f9253c8ad6726aa967b",
                            Gender = "Female",
                            Name = "Enrique"
                        },
                        new
                        {
                            Id = new Guid("28a25f0e-dfa5-dc8a-9ec7-db94ad90e67d"),
                            Age = 66,
                            EmailAddress = "Emery.Kunde76@hotmail.com",
                            ExternalId = "auth0|e2f2df7f262fee8312871a9d",
                            Gender = "Female",
                            Name = "Monique"
                        },
                        new
                        {
                            Id = new Guid("89d22fe4-5532-ac42-0f6e-976e2e92da05"),
                            Age = 100,
                            EmailAddress = "Earnest67@hotmail.com",
                            ExternalId = "auth0|53d2d94826faf10990721115",
                            Gender = "Female",
                            Name = "Julien"
                        },
                        new
                        {
                            Id = new Guid("455357b3-ab37-7d3b-8ddd-aa4a9b035760"),
                            Age = 61,
                            EmailAddress = "Lizzie52@hotmail.com",
                            ExternalId = "auth0|9d8a637327a243676fb0a2a2",
                            Gender = "Male",
                            Name = "Zaria"
                        });
                });

            modelBuilder.Entity("PlaylistSong", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vladify.DataAccess.Entities.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Playlist", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.User", "Owner")
                        .WithMany("Playlists")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.Song", b =>
                {
                    b.HasOne("Vladify.DataAccess.Entities.User", "Owner")
                        .WithMany("OwnedSongs")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Vladify.DataAccess.Entities.User", b =>
                {
                    b.Navigation("OwnedSongs");

                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
